Repository woocommerce/woocommerce-android, pull requests merged in 2019-02, with the labels that each got.

#737 issue/687-order-details-casing
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: Order Details

#734 issue/733-illegal-state-review-detail
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
Labels: [Type] Crash

#736 Issue/735 nosuchelement notification ext
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NotificationModelExt.kt
Labels: [Type] Crash

#747 issue/746-resource-exception-login-2fa
  RELEASE-NOTES.txt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java
Labels: Epic: Login, [Type] Crash

#754 issue/753-login-illegal-argument-exception
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
Labels: Epic: Login, [Type] Crash

#756 Issue/sectioned recycler convert
  WooCommerce/src/main/java/com/woocommerce/android/widgets/Section.java
  WooCommerce/src/main/java/com/woocommerce/android/widgets/SectionParameters.java
  WooCommerce/src/main/java/com/woocommerce/android/widgets/SectionedRecyclerViewAdapter.java
  WooCommerce/src/main/java/com/woocommerce/android/widgets/StatelessSection.java
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/Section.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/SectionParameters.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/SectionedRecyclerViewAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/StatelessSection.kt
Labels: Epic: Notifications II, Epic: Order List

#731 Issue/728 notifs empty state
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt
  WooCommerce/src/main/res/layout/fragment_dashboard.xml
  WooCommerce/src/main/res/layout/fragment_notifs_list.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/wc_empty_view.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListPresenterTest.kt
Labels: Epic: Notifications II

#762 Fix missing sdkmanager license, if needed
  .travis.yml
Labels: Tools

#763 Issue/740 sales totals dont match calypso
  RELEASE-NOTES.txt
  build.gradle
Labels: Epic: Dashboard

#757 Issue/748 orderlist invalid section kotlin
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/SectionedRecyclerViewAdapter.kt
Labels: Epic: Notifications II, [Type] Crash

#759 Issue/758 update to supportlib v28.0.0
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  build.gradle
Labels: Size: S

#768 Issue/766 inflate exception top earners
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
Labels: [Type] Crash

#743 Feature/742 enable switching sites
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedActivityBindingModule.kt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/adapter/SiteListUnsupportedAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialog.kt
  WooCommerce/src/main/res/layout/activity_site_picker.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/site_list_unsupported_item.xml
  WooCommerce/src/main/res/layout/site_picker_item.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: App Settings, Epic: Login

#761 Issue/760 feature tooltip
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCFeatureTooltip.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Size: M

#775 Merge 1.1 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Tools

#788 Verify the TopLevelFragment is attached before attempting to call chi…
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
Labels: [Type] Crash

#772 Merge `release/1.2` into `develop`
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  fastlane/env.example
Labels: Tools

#797 issue/fluxc-zendesk-fix-1.2
  WooCommerce/build.gradle
  build.gradle
Labels: [Type] Crash

#799 Merge release/1.2 into master
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  build.gradle
Labels: Tools

#805 Add CircleCI config
  .circleci/config.yml
Labels: Tools

#778 issue/777-refresh-site-list
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
Labels: Epic: App Settings

#811 Add version number in RELEASE-NOTES.txt
  RELEASE-NOTES.txt
Labels: Tools

#776 Issue/771 refresh after switching sites
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
Labels: Epic: App Settings

#795 issue/793-bar-chart-colors
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
  WooCommerce/src/main/res/values/colors.xml
Labels: Epic: Dashboard

#798 Feature/792 chrome custom tabs everywhere
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AboutFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ChromeCustomTabUtils.kt
Labels: [Type] Enhancement

#790 Issue/785 show store name
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Epic: Dashboard

#804 Issue/786 update tracks
  WooCommerce/build.gradle
Labels: [Type] Crash

#807 issue/806-toolbar-back-arrow-nav
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: [Type] Bug

#821 Update lane name
  fastlane/Fastfile
Labels: Tools

#825 Upgrade gradle plugin to 4.10.1 (latest)
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  libs/login/WordPressLoginFlow/build.gradle
Labels: [Type] Task

#813 issue/750-clarify-login-username
  WooCommerce/src/main/res/values/strings.xml
Labels: [Type] Enhancement

#809 issue/787-state-loss-google-login-fragment
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
Labels: [Type] Crash

#810 issue/782-illegal-state-main-clearbackstack
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: [Type] Crash

#827 Manual order status change support
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailOrderStatusView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusFilterDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusSelectorDialog.kt
  WooCommerce/src/main/res/drawable/ic_edit_pencil.xml
  WooCommerce/src/main/res/layout/order_detail_order_status.xml
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: Epic: Order Details, Size: M, [Type] Enhancement

#832 issue/659-illegal-state-fragment-again
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
Labels: [Type] Crash

#819 issue/818-bottom-nav-hidden
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: [Type] Bug

#815 issue/814-add-order-note-capitalization
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/layout/activity_add_order_note.xml
Labels: [Type] Bug

#831 issue/828-logout-button-text
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: App Settings

#830 issue/829-top-performers-total
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: Dashboard

#835 Add comment for translators
  WooCommerce/metadata/PlayStoreStrings.pot
Labels: Tools

#839 Merge 1.2 into develop
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  tools/release-notes-language-codes.csv
Labels: Tools

#841 Add override for a login library string
  WooCommerce/src/main/res/values/strings.xml
Labels: Tools

#853 Remove Danger: Dangerfile, gem and CircleCI job
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: Tooling

#857 issue/834-notification-review-detail
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: [Type] Bug

#863 Merge 1.3 into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Tools

#836 issue/374-selected-site-get-exception
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
Labels: [Type] Crash

#842 Issue/837 empty review detail
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailPresenter.kt
Labels: [Type] Bug

#851 issue/816-notifs-index-out-of-bounds
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
Labels: Epic: Notifications II, [Type] Crash

#869 issue/update-fluxc-hash-1.3
  build.gradle
Labels: [Type] Bug
