Repository woocommerce/woocommerce-android, pull requests merged in 2019-06, with the labels that each got.

#1116 Merge release 1.9 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#1117 Merge Release/2.0 into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#1113 RTL support for order list/order note/product list divider
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  WooCommerce/src/main/res/layout/order_detail_note_item.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: [Type] Bug

#1104 Issue/1102 fragmentize add order note
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddNoteUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNotePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrdersViewRouter.kt
  WooCommerce/src/main/res/layout/fragment_add_order_note.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/AddOrderNotePresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
Labels: AndroidX

#1109 Issue/1108 fragmentize product detail
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailUIMessageResolver.kt
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: AndroidX

#1107 Shipment Tracking: Support Rtl changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/res/drawable/ic_back_white_24dp.xml
  WooCommerce/src/main/res/drawable/ic_done_purple_24dp.xml
  WooCommerce/src/main/res/layout/activity_add_shipment_tracking.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_item.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: Order Details, [Type] Bug

#1122 Issue/1112 fragment-ise shipment tracking
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedActivityBindingModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/MainActivityTestRule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/AddShipmentTrackingActivityTestRule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/AddShipmentTrackingFragmentTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/AddShipmentTrackingNavigationTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/MockedAddOrderShipmentTrackingModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentShipmentTrackingCardTest.kt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddShipmentTrackingUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrdersViewRouter.kt
  WooCommerce/src/main/res/layout/activity_add_shipment_tracking.xml
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
Labels: AndroidX

#1121 Part 1: Sign In Jetpack basic check and error messaging
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/res/drawable/img_login_jetpack_required.xml
  WooCommerce/src/main/res/drawable/login_site_address_help.xml
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_jetpack_required.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/main/res/menu/menu_login.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMode.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/gradle.properties-example
Labels: Login, [Status] Needs Design Review

#1125 Part 2: What is Jetpack Dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginWhatIsJetpackDialogFragment.kt
  WooCommerce/src/main/res/drawable/img_what_is_jetpack.xml
  WooCommerce/src/main/res/layout-land/fragment_login_what_is_jetpack.xml
  WooCommerce/src/main/res/layout/fragment_login_what_is_jetpack.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: Login

#1129 Release notes for 2.0
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#1114 Fix timezone issue when running UI tests for Order list
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/WCDateTimeTestUtils.kt
Labels: [Type] Bug

#1127 Added event for when shipment tracking provider list is loaded successfully
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
Labels: Order Details, [Type] Enhancement

#1128 Fix stats page blank when fragment is resumed after app is closed and opened again
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: Architecture, [Type] Bug

#1133 Issue/1132 settings nav component
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AboutFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/LicensesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/res/layout/activity_app_settings.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
Labels: AndroidX, App Settings, Architecture

#1138 Merge Sentry into 2.0
  .configure
  .gitignore
  WooCommerce/build.gradle
  WooCommerce/lint.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CrashUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CrashlyticsUtils.kt
  build.gradle
  gradle.properties-example
Labels: Tooling

#1143 Destroy child fragments of previously active fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: [Type] Bug

#1140 Product Detail: Add intrumentation tests
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedActivityBindingModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedCurrencyModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/WCMatchers.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/MainActivityTestRule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedOrderProductListModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/ProductDetailNavigationTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/ProductListCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/WcProductTestUtils.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/utils/WCSiteUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenter.kt
Labels: Product Details, [Type] Enhancement

#1146 Use a better Sentry DSN default for OSS devs
  gradle.properties-example
Labels: Tooling

#1126 Prevent direct commits into the master and develop branch
  build.gradle
  tools/team-props/git-hooks/pre-commit
Labels: Tooling

#1135 Part 3: Sign In post authentication validate url and auto-login
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEmailHelpDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/res/layout-land/view_login_epilogue_button_bar.xml
  WooCommerce/src/main/res/layout-land/view_login_no_stores.xml
  WooCommerce/src/main/res/layout/activity_site_picker.xml
  WooCommerce/src/main/res/layout/view_login_epilogue_button_bar.xml
  WooCommerce/src/main/res/layout/view_login_no_stores.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenterTest.kt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Login

#1148 Ignore sentry.properties file
  .gitignore
Labels: Tooling

#1137 Part 4: Sign in Milestone 1 Tracks Events
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginAnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEmailHelpDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginWhatIsJetpackDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginAnalyticsListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
Labels: Login

#1147 Part 5: Signin M1 - add jetpack support documentation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginWhatIsJetpackDialogFragment.kt
  WooCommerce/src/main/res/values/link_strings.xml
Labels: Login

#1150 Feature: Sign In Milestone 1
  .idea/vcs.xml
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginAnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEmailHelpDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginWhatIsJetpackDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/res/drawable/img_login_jetpack_required.xml
  WooCommerce/src/main/res/drawable/img_what_is_jetpack.xml
  WooCommerce/src/main/res/drawable/login_site_address_help.xml
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-land/fragment_login_what_is_jetpack.xml
  WooCommerce/src/main/res/layout-land/view_login_epilogue_button_bar.xml
  WooCommerce/src/main/res/layout-land/view_login_no_stores.xml
  WooCommerce/src/main/res/layout/activity_site_picker.xml
  WooCommerce/src/main/res/layout/fragment_login_jetpack_required.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_what_is_jetpack.xml
  WooCommerce/src/main/res/layout/view_login_epilogue_button_bar.xml
  WooCommerce/src/main/res/layout/view_login_no_stores.xml
  WooCommerce/src/main/res/menu/menu_login.xml
  WooCommerce/src/main/res/values/link_strings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenterTest.kt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginAnalyticsListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMode.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/gradle.properties-example
Labels: Login, [Type] Enhancement

#1157 Fix app title persistence issues
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: [Type] Bug

#1153 Added the proper style tag to style the review buttons per designs
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
Labels: Style

#1160 issue/1159-notification-glide-exception-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: [Type] Crash

#1162 Merge release/2.0 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#1163 Merge Release/2.1 into develop
  .configure
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/strings.xml
Labels: Releases

#1165 Fix localization crash on date shipped button in Add Order Tracking view
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
Labels: Woo Extensions, [Type] Bug

#1156 Display cached orders in the order list if available on first run
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListPresenterTest.kt
Labels: Order List, [Type] Enhancement

#1167 Merge Release/2.1 into develop
  .gitignore
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
Labels: Releases

#1170 Add the bottom overscroll animation to lists
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/ScrollChildSwipeRefreshLayout.kt
  WooCommerce/src/main/res/layout/fragment_dashboard.xml
Labels: Dashboard, Notifications, Order List

#1166 Update FluxC build hash to import notification table fix
  RELEASE-NOTES.txt
  build.gradle
Labels: Notifications, [Type] Bug

#1161 Order detail: Incorrect handling of empty shipping & billing
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentCustomerInfoCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Order Details, [Type] Enhancement

#1183 Update code freeze tooling
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  tools/update-name-core.sh
  tools/update-release-names.sh
Labels: Releases

#1191 Update release-toolkit to 0.4.0
  Gemfile.lock
  fastlane/Pluginfile
Labels: Releases
