Repository woocommerce/woocommerce-android, pull requests merged in 2019-04, with the labels that each got.

#914 Feature/product detail v1
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyLinkView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/layout/order_detail_product_list_item.xml
  WooCommerce/src/main/res/layout/product_property_cardview.xml
  WooCommerce/src/main/res/layout/product_property_link_view.xml
  WooCommerce/src/main/res/layout/product_property_view_horz.xml
  WooCommerce/src/main/res/layout/product_property_view_vert.xml
  WooCommerce/src/main/res/layout/skeleton_product_detail.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
  WooCommerce/src/main/res/menu/menu_share.xml
  WooCommerce/src/main/res/values/dimens.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  build.gradle
Labels: Product Details

#927 Feature/product detail image scrolling
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/SkeletonView.kt
  WooCommerce/src/main/res/drawable/product_detail_gradient_scrim.xml
  WooCommerce/src/main/res/drawable/product_detail_image_background.xml
  WooCommerce/src/main/res/layout/activity_product_detail.xml
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/layout/skeleton_product_detail.xml
  WooCommerce/src/main/res/values/dimens.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: Product Details

#959 issue/957-order-id-must-not-be-null
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: [Type] Crash

#958 issue/953-remove-site-switcher-promo
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCPromoDialog.kt
Labels: App Settings

#955 Issue/951 dashboard refreshes too often
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
Labels: Architecture, Dashboard

#965 Feature/product detail tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: Product Details

#960 Feature/product detail image viewer
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/imageviewer/ImageViewerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/res/anim/toolbar_fade_in_and_down.xml
  WooCommerce/src/main/res/anim/toolbar_fade_out_and_up.xml
  WooCommerce/src/main/res/layout/activity_image_viewer.xml
  WooCommerce/src/main/res/layout/activity_product_detail.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: Product Details, [Type] Enhancement

#962 Amanda/608 shipment tracking
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_item.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
  build.gradle
Labels: Order Details, [Type] Enhancement

#966 Account for nullability
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
Labels: Order List, [Type] Crash

#968 issue/967-site-picker-continue-analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
Labels: Usage Analytics

#961 Feature/product detail master
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/imageviewer/ImageViewerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyLinkView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/SkeletonView.kt
  WooCommerce/src/main/res/anim/toolbar_fade_in_and_down.xml
  WooCommerce/src/main/res/anim/toolbar_fade_out_and_up.xml
  WooCommerce/src/main/res/drawable/product_detail_gradient_scrim.xml
  WooCommerce/src/main/res/drawable/product_detail_image_background.xml
  WooCommerce/src/main/res/drawable/product_detail_status_badge.xml
  WooCommerce/src/main/res/layout/activity_image_viewer.xml
  WooCommerce/src/main/res/layout/activity_product_detail.xml
  WooCommerce/src/main/res/layout/order_detail_product_list_item.xml
  WooCommerce/src/main/res/layout/product_property_cardview.xml
  WooCommerce/src/main/res/layout/product_property_link_view.xml
  WooCommerce/src/main/res/layout/product_property_view_horz.xml
  WooCommerce/src/main/res/layout/product_property_view_vert.xml
  WooCommerce/src/main/res/layout/skeleton_product_detail.xml
  WooCommerce/src/main/res/menu/menu_share.xml
  WooCommerce/src/main/res/values/dimens.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: Product Details, [Type] Enhancement

#970 Merge 1.5 back into `develop`
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Tooling

#971 Merge 1.5 into `master`
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Tooling

#972 Merge 1.6 back to `develop`
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Tooling

#974 Change link to support documentation and update the name of the button
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/res/layout/activity_help.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: App Settings, [Type] Enhancement

#983 Fix crash in popToState
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
Labels: Notifications, Order Details, [Type] Crash

#985 issue/979-npe-clear-bar-data-1.6
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Dashboard, [Type] Crash

#984 feature/simple-product-variations
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  build.gradle
Labels: Product Details

#977 Hide button to open external tracking page when link not available
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
Labels: Order Details

#990 Merge latest 1.6 changes
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Tooling

#991 Import latest login library changes
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values/colors.xml
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java
  libs/login/WordPressLoginFlow/src/main/res/drawable-ldrtl-v18/ic_arrow_left_white_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_arrow_left_white_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_placeholder_blavatar_grey_lighten_20_40dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/login_toolbar_icon.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_username_password_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/values/colors.xml
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/res/values/styles.xml
Labels: Login

#986 Feature/product detail title
  .idea/codeStyles/Project.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductType.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product Details

#992 issue/develop-fluxc-hash
  build.gradle
Labels: Priority: High, [Type] Bug

#997 Feature/988 product detail design review
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyReadMoreView.kt
  WooCommerce/src/main/res/drawable/product_detail_image_background.xml
  WooCommerce/src/main/res/layout/activity_product_detail.xml
  WooCommerce/src/main/res/layout/product_property_read_more_view.xml
  WooCommerce/src/main/res/layout/product_property_view_horz.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Product Details

#998 feature/product-detail-for-all
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  build.gradle
Labels: Product Details

#996 Localize date formatting in shipment tracking card
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
Labels: Order Details

#1002 Import latest login library changes
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Login

#1004 issue/1003-product-ripple
  WooCommerce/src/main/res/layout/order_detail_product_list_item.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
Labels: Product Details

#1006 issue/1001-wcandroid-manage-stock
  build.gradle
Labels: Product Details

#1015 Updated Zendesk to 2.3.1
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/ZendeskHelper.kt
Labels: [Type] Crash

#1016 Added scrollview to review notification screen
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
Labels: [Type] Bug

#1019 Merge Release/1.7 into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Tooling

#1018 issue/933-crash-fix-for-no-activity-found-exception
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
Labels: [Type] Crash

#1022 Allow null value for intent param in notification service
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationsProcessingService.kt
Labels: [Type] Crash

#1020 Feature/wc db downgrade
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooWellSqlConfig.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/res/layout/skeleton_site_picker.xml
  WooCommerce/src/main/res/layout/skeleton_site_picker_item.xml
  build.gradle
  gradle.properties-example
Labels: Hack Week

#1023 Added logic to retain the state of the "My Store" tab when the activity is destroyed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
Labels: [Type] Bug

#1024 Modify rating bar star colors to support Lollipop devices
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
Labels: Notifications, [Type] Bug

#1031 Fix dashboard title not changing when stats tab is reselected the first time
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: [Type] Bug

#1033 Added ui tests for navigating to settings & help page
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedActivityBindingModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/WCMatchers.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/MainNavigationTest.kt
Labels: [Type] Enhancement

#1027 Issue/993 move up fabric initialization
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
Labels: App Settings
