Repository woocommerce/woocommerce-android, pull requests merged in 2019-03, with the labels that each got.

#864 Issue/update switcher promo svg
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCPromoDialog.kt
  WooCommerce/src/main/res/drawable/promo_store_switcher.xml
  WooCommerce/src/main/res/layout/dialog_promo.xml
Labels: [Type] Enhancement

#868 issue/846-review-notifs-2lines
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/res/layout/notifs_list_item.xml
Labels: [Type] Enhancement

#866 Issue/854 api upgrade notice
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/res/layout/fragment_dashboard.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: Dashboard

#875 Issue/872 show product images
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ProductImageMapModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NotificationModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotificationHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
  WooCommerce/src/main/res/layout/skeleton_dashboard_top_earner_list_item.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
  WooCommerce/src/main/res/values/dimens.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
  build.gradle
Labels: Epic: Product Details, [Status] Not Ready for Merge

#883 Remove Travis CI configuration
  .travis.yml
  README.md
Labels: Tooling

#879 Add Violations plugin to comment on GH PR
  .circleci/config.yml
  WooCommerce/build.gradle
  build.gradle
Labels: Tooling

#886 Add msg notifying user site switched successfully
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: App Settings

#890 Issue/site picker clipping
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/res/layout/activity_site_picker.xml
Labels: Size: S

#862 Issue/859 rapid review moderation woes
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListPresenter.kt
Labels: Notifications

#895 Update to latest FluxC hash to include the stats refresh fix
  RELEASE-NOTES.txt
  build.gradle
Labels: Store Stats

#893 issue/892-update-fluxc-hash-for-top-earners-fix
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
  build.gradle
Labels: Dashboard

#898 Update Login library subtree from remote
  libs/login/.circleci/config.yml
  libs/login/.idea/checkstyle-idea.xml
  libs/login/.idea/codeStyles/Project.xml
  libs/login/.travis.yml
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/widgets/WPLoginInputRow.java
  libs/login/WordPressLoginFlow/src/main/res/layout/login_input_row.xml
  libs/login/WordPressLoginFlow/src/main/res/values/attrs.xml
  libs/login/WordPressLoginFlow/src/main/res/values/colors.xml
  libs/login/WordPressLoginFlow/src/main/res/values/styles.xml
  libs/login/config/checkstyle.xml
  libs/login/gradle/wrapper/gradle-wrapper.properties
Labels: Login

#896 Update to new FluxC interceptor usage for Stetho
  WooCommerce/src/debug/kotlin/com.woocommerce.android/di/InterceptorModule.kt
  build.gradle
Labels: Tooling

#899 Update FluxC hash
  build.gradle
Labels: Hotfix

#889 Issue/877 product images part2
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
Labels: [Type] Enhancement

#905 Merge 1.4 into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  fastlane/Pluginfile
Labels: Tooling

#884 Issues/882 assorted design tweaks
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
Labels: Notifications, Order Details

#885 issues/874-email-from-order-notif
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderCustomerActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderCustomerHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
Labels: Order Details

#907 issue/897-fluxc-hash-for-fields
  build.gradle
Labels: [Type] Enhancement

#911 Fix Gradle plugin 3.3.+ deprecation warnings
  WooCommerce/build.gradle
  build.gradle
Labels: Tooling

#921 Issue/promo dialog clipped
  WooCommerce/src/main/res/layout/dialog_promo.xml
Labels: Priority: Low

#928 Merge 1.4 into develop
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  build.gradle
Labels: Tooling

#929 Merge 1.4 into master
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  build.gradle
Labels: Tooling

#931 Merge 1.5 back to develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
Labels: Tooling

#932 Merge 1.5 into master
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderCustomerActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderCustomerHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
  WooCommerce/src/main/res/layout/dialog_promo.xml
  WooCommerce/src/main/res/layout/fragment_review_detail.xml
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
  build.gradle
Labels: Tooling

#930 issue/922-onbackpressed-exception
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: [Type] Crash

#937 issue/910-app-rating-init
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Low hanging fruit

#935 Issue/891 stats bar size
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Dashboard, [Type] Bug

#943 issue/942-cant-fulfill-order
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
Labels: Hotfix

#936 Issue/873 clear backstack when site changed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
Labels: App Settings, [Type] Bug

#940 issue/939-orderproductlist-access-exception
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
Labels: Order Details, [Type] Crash

#946 Merge 1.5-rc-2 intro develop
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
Labels: Tooling

#945 issue/920-dead-system-exception
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMMessageService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: [Type] Crash

#947 Merge 1.5-rc-2 into master
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
Labels: Tooling

#941 issue/888-order-detail-already-active
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
Labels: Order Details, [Type] Crash

#950 Update Jetpack login track event to match iOS
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
Labels: Login
