Repository woocommerce/woocommerce-android, pull requests merged in 2019-05, with the labels that each got.

#1039 Fix order list fragment is blank after closing and opening the app
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: Priority: High, [Type] Bug

#924 Feature/add release tooling
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  tools/release-checks.sh
  tools/update-name-core.sh
  tools/update-release-names.sh
  tools/update-translations.sh
Labels: Tooling

#1045 Merge Release/1.7 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Tooling

#1044 Issue/1040-fix-page-title-mismatch
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
Labels: [Type] Bug

#1060 Issue/1057 add dates to order list
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListAdapter.kt
  WooCommerce/src/main/res/layout/order_list_item.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: Order List, [Status] Needs Design Review

#1063 Issue/1062 sdk v28
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: Architecture

#1028 Add scripts to use Android App Bundles
  .gitignore
  tools/build-app-bundle.sh
  tools/gradle-functions.sh
  tools/install-app-bundle.sh
Labels: Tooling

#1070 Fix padding on Customer Info Card
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
Labels: Order Details

#1067 Updated to Glide 4.9.0
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: AndroidX

#1074 Merge Release/1.8 into master
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#1073 Merge Release/1.8 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#1079 Fix update_appstore_strings lane
  Gemfile.lock
  fastlane/Pluginfile
Labels: [Type] Bug

#1075 Merge Release/1.9 into develop
  .configure
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  fastlane/Pluginfile
Labels: Releases

#1077 Merge release/1.9 into master
  .configure
  .gitignore
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListAdapter.kt
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
  WooCommerce/src/main/res/layout/order_list_item.xml
  WooCommerce/src/main/res/values/styles.xml
  build.gradle
  fastlane/Pluginfile
  libs/login/WordPressLoginFlow/build.gradle
  tools/build-app-bundle.sh
  tools/gradle-functions.sh
  tools/install-app-bundle.sh
Labels: Releases

#1054 Order Fulfillment: Add Optional Shipment Tracking Card
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddShipmentTrackingUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderShipmentTrackingActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrdersViewRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/drawable/ic_arrow_right_grey.xml
  WooCommerce/src/main/res/drawable/ic_done_purple_24dp.xml
  WooCommerce/src/main/res/layout/activity_add_shipment_tracking.xml
  WooCommerce/src/main/res/layout/dialog_order_tracking_provider_list.xml
  WooCommerce/src/main/res/layout/dialog_order_tracking_provider_list_header.xml
  WooCommerce/src/main/res/layout/dialog_order_tracking_provider_list_item.xml
  WooCommerce/src/main/res/layout/fragment_order_fulfillment.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_item.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list.xml
  WooCommerce/src/main/res/menu/menu_add.xml
  WooCommerce/src/main/res/menu/menu_search.xml
  WooCommerce/src/main/res/values/integers.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/DateUtilsTest.kt
Labels: Order Details, [Status] Needs Design Review

#1080 Issue/1066 woo update dagger
  .idea/inspectionProfiles/profiles_settings.xml
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AppComponentTest.kt
  WooCommerce/src/debug/kotlin/com.woocommerce.android/di/AppComponentDebug.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/AppComponent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/FragmentScope.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/ReviewDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsModule.kt
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: AndroidX, Tech Debt, [Status] Not Ready for Merge

#1084 issue/1081-site-picker-out-of-bounds
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
Labels: [Type] Crash

#1041 Add UI tests for Order detail screen
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AppComponentTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedActivityBindingModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockedCurrencyModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/DrawableMatcher.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/RecyclerViewMatcher.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/WCMatchers.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/WcDateTimeTestUtils.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/MainActivityTestRule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/MainNavigationTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/MockedOrderDetailModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/MockedOrderListModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailNavigationTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailNotesCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailPaymentCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderListItemTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderListNavigationTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/stats/MockedDashboardModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/SectionedRecyclerViewAdapter.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
Labels: Order Details, [Type] Enhancement

#1052 Issue/1051-illegal-state-crash-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationView.kt
Labels: [Type] Crash

#1085 Only update the title of the fragment if the order list is visible
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
Labels: Order List

#1087 Issue/766 top earner inflation exception take2
  WooCommerce/src/main/res/layout/dashboard_top_earners.xml
  WooCommerce/src/main/res/layout/top_earner_list_item.xml
  WooCommerce/src/main/res/values/styles.xml
Labels: [Type] Crash

#1089 Page title doesn't update after switching device language
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
Labels: [Type] Bug

#1088 Subclass BarChart class to handle nullPointerException in MpAndroidChart
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsBarChart.kt
  WooCommerce/src/main/res/layout/dashboard_stats.xml
Labels: [Type] Crash

#1064 Order Fulfillment: Add store country at the beginning of the list of shipment providers
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenterTest.kt
  build.gradle
Labels: Order Details

#1072 Order Fulfillment: Add shipment tracking with custom providers
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/res/layout/activity_add_shipment_tracking.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
Labels: Order Details, [Type] Enhancement

#1093 issue/1092-custom-tabs-handle-invalid-urls
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ChromeCustomTabUtils.kt
Labels: [Type] Crash

#1095 Add missing translations from GlotPress
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
Labels: Dashboard, Localization

#1098 Switch order of custom provider and store country sections in list of tracking providers
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListAdapter.kt
Labels: Order Details, [Type] Enhancement

#1103 i8 Designs: Fix padding on logout button
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/dimens.xml
Labels: App Settings, [Type] Enhancement

#1078 Shipment Tracking: Provides option to delete a tracking record
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderShipmentTrackingActionListener.kt
  WooCommerce/src/main/res/drawable-v23/delete_button_bg.xml
  WooCommerce/src/main/res/drawable/button_purple_bg_oval.xml
  WooCommerce/src/main/res/drawable/delete_button_bg.xml
  WooCommerce/src/main/res/drawable/ic_close.xml
  WooCommerce/src/main/res/layout/activity_add_shipment_tracking.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_item.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list.xml
  WooCommerce/src/main/res/menu/menu_order_detail_shipment_tracking_actions.xml
  WooCommerce/src/main/res/values/dimens.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
Labels: Order Details, [Status] Needs Design Review, [Type] Enhancement

#1100 Order Detail: provide option to add shipment tracking
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderShipmentTrackingActionListener.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
Labels: Order Details, Woo Extensions, [Type] Enhancement
