Repository woocommerce/woocommerce-android, pull requests merged in 2019-01, with the labels that each got.

#690 Update README
  README.md
Labels: MVLP

#669 Analytics: Track Jetpack tunnel timeouts
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/Regex.kt
  build.gradle
  config/checkstyle.xml
Labels: Epic: Usage Analytics

#686 Update logout button text
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: App Settings

#685 Show exact count of orders in 'Orders to fulfill' card
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardUnfilledOrdersCard.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenterTest.kt
  build.gradle
Labels: Epic: Dashboard

#693 Update Kotlin, Gradle, and build tools
  .travis.yml
  WooCommerce/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tools

#696 issue/fix-unfulfilled-orders-layout
  WooCommerce/src/main/res/layout/skeleton_dashboard_unfilled_orders.xml
Labels: Epic: Dashboard

#695 Site Selector: Switch to on-demand api version verification design like iOS
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpiloguePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WooUpgradeRequiredDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/layout/activity_login_epilogue.xml
  WooCommerce/src/main/res/layout/dialog_version_upgrade_required.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: [Type] Bug

#702 Add RELEASE-NOTES.txt file to encourage adding release notes iteratively
  .github/PULL_REQUEST_TEMPLATE.md
  RELEASE-NOTES.txt
Labels: Tools

#705 Feature/add metadata sources
  Gemfile.lock
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/full_description.txt
  WooCommerce/metadata/release_notes.txt
  WooCommerce/metadata/short_description.txt
  WooCommerce/metadata/title.txt
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/android_update_metadata_source.rb
Labels: Tools

#703 Issue/640 notifs markread snack
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListPresenter.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Epic: Notifications II

#706 Add strings from promo screenshots
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/promo_screenshot_1.txt
  WooCommerce/metadata/promo_screenshot_1_b.txt
  WooCommerce/metadata/promo_screenshot_2.txt
  WooCommerce/metadata/promo_screenshot_3.txt
  WooCommerce/metadata/promo_screenshot_4.txt
  WooCommerce/metadata/promo_screenshot_5.txt
  WooCommerce/metadata/promo_screenshot_6.txt
  WooCommerce/metadata/promo_screenshot_7.txt
  WooCommerce/metadata/promo_screenshot_8.txt
  fastlane/Fastfile
Labels: Tools

#704 Issue/639 notifs disable markread
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListPresenter.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: Epic: Notifications II

#708 Update Woo site settings during login and periodically
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/RateLimitedTask.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpilogueContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpiloguePresenter.kt
Labels: [Type] Enhancement

#712 issue/711-dont-disable-support-menu
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Epic: App Settings

#701 Issue/668 prompt for review
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AppRatingDialog.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: [Type] Enhancement

#709 Issue/620 item decoration notifs
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListFragment.kt
  WooCommerce/src/main/res/layout/notifs_list_item.xml
Labels: Epic: Notifications II

#724 Issue/722 index out of bounds notifs
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt
Labels: Epic: Notifications II, [Type] Crash

#714 Issue/425 hide future orders
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt
Labels: Epic: Order List

#716 issue/715-illegal-state-noordersview
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt
Labels: Epic: Order List, [Type] Crash

#729 Reduce number of conflicts in RELEASE-NOTES.txt
  .gitattributes
Labels: Tools

#730 Format currencies based on site settings and locale
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AppComponentTest.kt
  WooCommerce/src/debug/kotlin/com.woocommerce.android/di/AppComponentDebug.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/AppComponent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/CurrencyModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPaymentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyUtils.kt
  build.gradle
Labels: Epic: Dashboard, Epic: Order Details, Epic: Order List

#732 Refresh site and account periodically
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ApplicationLifecycleMonitor.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
Labels: [Type] Enhancement
