Repository woocommerce/woocommerce-android, pull requests merged in 2020-06, with the labels that each got.

#2506 Merge 4.3 final to develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/ar/changelogs/131.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/131.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/131.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/131.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/id/changelogs/131.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/131.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/131.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ja-JP/changelogs/131.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/131.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/131.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/131.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/ru-RU/changelogs/131.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/131.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/131.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-CN/changelogs/131.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/131.txt
Labels: Releases

#2505 Merge 4.3 final to master
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/ar/changelogs/131.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/131.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/131.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/131.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/id/changelogs/131.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/131.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/131.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ja-JP/changelogs/131.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/131.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/131.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/131.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/ru-RU/changelogs/131.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/131.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/131.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-CN/changelogs/131.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/131.txt
Labels: Releases

#2507 Merge Release/4.4 back into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
Labels: Releases

#2513 Issue/2504 discard dialog filter products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/CustomDiscardDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product List

#2517 Merge Release/4.4 back into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#2512 Added logic to add images to a product only if it does not already exist
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: Product Details, [Type] Crash

#2526 Added null check to lastUpdatedRunnable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Store Stats, [Type] Crash

#2527 Merge Release/4.4 back into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Releases

#2514 Read-only variant details
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/BigDecimalExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariant.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertiesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductProperty.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/SiteParameters.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/PropertyGroupViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/SwitchViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PriceUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_not_visible.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_types.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_visible.xml
  WooCommerce/src/main/res/layout/fragment_product_variant.xml
  WooCommerce/src/main/res/layout/product_property_switch_layout.xml
  WooCommerce/src/main/res/layout/product_property_view_vert_layout.xml
  WooCommerce/src/main/res/layout/product_variant_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: Part of a WIP Feature, Variant Details

#2532 Add privacy notice for california users link
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/res/layout/fragment_settings_privacy.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: App Settings

#2535 Release/4.4
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/131.txt
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/131.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/131.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/fr-FR/changelogs/131.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/id/changelogs/131.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/131.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/131.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/131.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/131.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/nl-NL/changelogs/131.txt
  fastlane/metadata/android/nl-NL/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/131.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/131.txt
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/131.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/131.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/zh-CN/changelogs/131.txt
  fastlane/metadata/android/zh-CN/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/131.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
Labels: Releases

#2534 Merge Release/4.4 back into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/131.txt
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/131.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/131.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/fr-FR/changelogs/131.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/id/changelogs/131.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/131.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/131.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/131.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/131.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/nl-NL/changelogs/131.txt
  fastlane/metadata/android/nl-NL/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/131.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/131.txt
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/131.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/131.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/zh-CN/changelogs/131.txt
  fastlane/metadata/android/zh-CN/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/131.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
Labels: Releases

#2536 Remove the M2 feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
Labels: Product List, Product Settings

#2542 Merge Release/4.5 back into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
Labels: Releases

#2540 Update Gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tooling

#2547 Add CCPA link
  WooCommerce/metadata/full_description.txt
Labels: [Type] Enhancement

#2546 Issue/1926 new order notification bug fix
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Notifications, [Type] Bug

#2541 Feature/update product categories
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AppComponentTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductCategoriesModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductCategoriesRepository.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductCategory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/OnProductCategoryClickListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoryItemUiModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductProperty.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ComplexPropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_folder.xml
  WooCommerce/src/main/res/layout/fragment_product_categories_list.xml
  WooCommerce/src/main/res/layout/product_category_list_item.xml
  WooCommerce/src/main/res/layout/skeleton_product_categories_list.xml
  WooCommerce/src/main/res/layout/skeleton_product_category_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: Product Details

#2551 Merge Release/4.5 back into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/full_description.txt
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#2552 Merge Release/4.5 into Master
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/full_description.txt
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/CustomDiscardDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  WooCommerce/src/main/res/layout/fragment_settings_privacy.xml
  WooCommerce/src/main/res/values/strings.xml
  fastlane/Fastfile
Labels: Releases

#2548 Use shared debug keystore
  .circleci/config.yml
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/debug.keystore.enc
  .configure-files/google-services.json.enc
  .configure-files/gradle.properties.enc
  Gemfile.lock
  WooCommerce/build.gradle
  build.gradle
  fastlane/Pluginfile
Labels: Tooling

#2554 Update configuration
  .configure
Labels: Tooling

#2565 Hide the refund notice in refund details
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
Labels: Refunds, [Type] Bug

#2568 Remove trailing whitespaces from Fastfile
  fastlane/Fastfile
Labels: Tooling

#2557 Move CCPA link to About Screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AboutFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/res/layout/fragment_about.xml
  WooCommerce/src/main/res/layout/fragment_settings_privacy.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: App Settings

#2558 Make background color of login views white for light mode
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values/styles_login.xml
Labels: Login, Style

#2570 Issue/2566 order open event - Take 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListListener.kt
Labels: Order List, Tracks Events, [Type] Bug

#2571 Update finalize lane
  fastlane/Fastfile
Labels: Tooling

#2543 Feature/add product categories
  WooCommerce/src/main/kotlin/com/woocommerce/android/RequestCodes.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductCategory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariant.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/RequestResult.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ParentCategoryListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ParentCategoryListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ParentCategoryListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesRepository.kt
  WooCommerce/src/main/res/layout/add_product_category_view.xml
  WooCommerce/src/main/res/layout/fragment_add_product_category.xml
  WooCommerce/src/main/res/layout/fragment_product_categories_list.xml
  WooCommerce/src/main/res/layout/parent_category_list_item.xml
  WooCommerce/src/main/res/layout/skeleton_product_categories_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_add_product_category.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  build.gradle
Labels: Product Details, [Type] Enhancement

#2562 Issue/2523 add guest as customer name
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/MockedOrderListModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/list/MockedOrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCOrderModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailOrderStatusView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListItemDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: Order Details, Order List

#2555 Add shipping property (read-only)
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/IProduct.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariant.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantViewModel.kt
  WooCommerce/src/main/res/layout/fragment_product_variant.xml
  WooCommerce/src/main/res/layout/skeleton_variant_detail.xml
Labels: Variation Details

#2575 Merge Release/4.5 back into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/ar/changelogs/136.txt
  fastlane/metadata/android/ar/full_description.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/136.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/136.txt
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/es-ES/short_description.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/fr-FR/full_description.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/id/full_description.txt
  fastlane/metadata/android/id/short_description.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/136.txt
  fastlane/metadata/android/it-IT/full_description.txt
  fastlane/metadata/android/it-IT/short_description.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/136.txt
  fastlane/metadata/android/iw-IL/full_description.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/136.txt
  fastlane/metadata/android/ja-JP/full_description.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/136.txt
  fastlane/metadata/android/ko-KR/full_description.txt
  fastlane/metadata/android/nl-NL/changelogs/134.txt
  fastlane/metadata/android/nl-NL/changelogs/136.txt
  fastlane/metadata/android/nl-NL/full_description.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/136.txt
  fastlane/metadata/android/pt-BR/full_description.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/ru-RU/full_description.txt
  fastlane/metadata/android/ru-RU/short_description.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/136.txt
  fastlane/metadata/android/sv-SE/full_description.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/136.txt
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/zh-CN/changelogs/134.txt
  fastlane/metadata/android/zh-CN/changelogs/136.txt
  fastlane/metadata/android/zh-CN/full_description.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/136.txt
  fastlane/metadata/android/zh-TW/full_description.txt
Labels: Releases

#2576 Release/4.5
  WooCommerce/build.gradle
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/ar/changelogs/136.txt
  fastlane/metadata/android/ar/full_description.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/136.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/de-DE/short_description.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/136.txt
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/es-ES/short_description.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/fr-FR/full_description.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/id/full_description.txt
  fastlane/metadata/android/id/short_description.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/136.txt
  fastlane/metadata/android/it-IT/full_description.txt
  fastlane/metadata/android/it-IT/short_description.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/136.txt
  fastlane/metadata/android/iw-IL/full_description.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/136.txt
  fastlane/metadata/android/ja-JP/full_description.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/136.txt
  fastlane/metadata/android/ko-KR/full_description.txt
  fastlane/metadata/android/nl-NL/changelogs/134.txt
  fastlane/metadata/android/nl-NL/changelogs/136.txt
  fastlane/metadata/android/nl-NL/full_description.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/136.txt
  fastlane/metadata/android/pt-BR/full_description.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/ru-RU/full_description.txt
  fastlane/metadata/android/ru-RU/short_description.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/136.txt
  fastlane/metadata/android/sv-SE/full_description.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/136.txt
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/zh-CN/changelogs/134.txt
  fastlane/metadata/android/zh-CN/changelogs/136.txt
  fastlane/metadata/android/zh-CN/full_description.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/136.txt
  fastlane/metadata/android/zh-TW/full_description.txt
Labels: Releases

#2574 Remove v4 stats from beta option
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/res/layout/fragment_settings_beta.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Store Stats, [Type] Enhancement

#2578 issue/2458-in-app-update-crash-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/AppUpgradeActivity.kt
Labels: [Type] Crash

#2583 Issue/2188 display product tags
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductTag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_tag.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: Product Details

#2573 Update/build lane
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#2590 Merge release 4.6 into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
Labels: Releases

#2577 Fix broken unit tests
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/NetworkStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderNoteRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingClassViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductVariantViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/NavArgsWithDefaultLazy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/SavedStateWithArgs.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/CoroutineTestRule.kt
Labels: Broken Tests
