Repository woocommerce/woocommerce-android, pull requests merged in 2020-11, with the labels that each got.

#3114 Merge Release/5.3 into develop
  .circleci/config.yml
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/Fastfile
  fastlane/metadata/android/es-ES/changelogs/158.txt
  fastlane/metadata/android/fr-FR/changelogs/158.txt
  fastlane/metadata/android/fr-FR/changelogs/161.txt
  fastlane/metadata/android/it-IT/changelogs/161.txt
  fastlane/metadata/android/iw-IL/changelogs/158.txt
  fastlane/metadata/android/iw-IL/changelogs/161.txt
  fastlane/metadata/android/ko-KR/changelogs/158.txt
  fastlane/metadata/android/ko-KR/changelogs/161.txt
  fastlane/metadata/android/pt-BR/changelogs/158.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/158.txt
  fastlane/metadata/android/sv-SE/changelogs/158.txt
  fastlane/metadata/android/sv-SE/changelogs/161.txt
  fastlane/metadata/android/zh-CN/changelogs/161.txt
  fastlane/metadata/android/zh-TW/changelogs/158.txt
Labels: Releases

#3117 merge release/5.4 into develop after code freeze
  .idea/compiler.xml
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#3129 issue/release-notes-remove-linked-products-5.4
  RELEASE-NOTES.txt
Labels: Product Details

#3130 Merge release/5.4 back to develop: update in release notes
  RELEASE-NOTES.txt
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#3131 Show different banner based on M4 flag switch state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  fastlane/resources/values/strings.xml
Labels: Product List

#3135 issue/3134-photo-view-update
  WooCommerce/build.gradle
Labels: Low hanging fruit

#3137 Issue/3133 add linked product picker
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModel.kt
Labels: Product Details

#3132 Update dagger to 2.29.1
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tech Debt, [Type] Task

#3138 Issue/3127 hide already selected products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModelTest.kt
Labels: Product Details

#3147 Fix variation names
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListAdapter.kt
Labels: Variation Details, Variation list

#3150 Fix typo in shipping label refund request screen
  WooCommerce/src/main/res/values/strings.xml
Labels: Order Details

#3156 Beta fix: Use HTML entities in String resource to fix translation issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelInfoFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Priority: High, Shipping Labels

#3149 Remove References to "master"
  .idea/vcs.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/LiveDataUtils.kt
  tools/team-props/git-hooks/pre-commit
Labels: Tooling

#3162 release/5.4 -> develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelInfoFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/metadata/android/ar/changelogs/163.txt
  fastlane/metadata/android/de-DE/changelogs/163.txt
  fastlane/metadata/android/es-ES/changelogs/163.txt
  fastlane/metadata/android/fr-FR/changelogs/161.txt
  fastlane/metadata/android/fr-FR/changelogs/163.txt
  fastlane/metadata/android/id/changelogs/163.txt
  fastlane/metadata/android/it-IT/changelogs/161.txt
  fastlane/metadata/android/it-IT/changelogs/163.txt
  fastlane/metadata/android/iw-IL/changelogs/161.txt
  fastlane/metadata/android/iw-IL/changelogs/163.txt
  fastlane/metadata/android/ja-JP/changelogs/163.txt
  fastlane/metadata/android/ko-KR/changelogs/161.txt
  fastlane/metadata/android/ko-KR/changelogs/163.txt
  fastlane/metadata/android/nl-NL/changelogs/163.txt
  fastlane/metadata/android/pt-BR/changelogs/163.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/163.txt
  fastlane/metadata/android/sv-SE/changelogs/161.txt
  fastlane/metadata/android/sv-SE/changelogs/163.txt
  fastlane/metadata/android/tr-TR/changelogs/163.txt
  fastlane/metadata/android/zh-CN/changelogs/161.txt
  fastlane/metadata/android/zh-CN/changelogs/163.txt
  fastlane/metadata/android/zh-TW/changelogs/163.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#3161 Enable Products M4 for all
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product List

#3158 Added tracking event when product image upload fails
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
Labels: Product Details, Tracks Events

#3169 Release/5.5 -> develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#3170 Fix order detail products
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: Order Details

#3172 Issue/2615 fetch media crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUtils.kt
Labels: [Type] Crash

#3182 Add ADD_ORDER_TRACKING analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: Tracks Events

#3188 Update FluxC commit hash to pull in the hotfix for empty order product variation keys
  RELEASE-NOTES.txt
  build.gradle
Labels: Hotfix, Order Details

#3136 Issue/nav redesign
  .idea/codeStyles/Project.xml
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/TopLevelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackCompletedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackSurveyFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderTrackingProviderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/LicensesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ChromeCustomTabUtils.kt
  WooCommerce/src/main/res/drawable/ic_back_24dp.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_cog_24dp.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_cross_24dp.xml
  WooCommerce/src/main/res/drawable/ic_search_24dp.xml
  WooCommerce/src/main/res/layout/activity_app_settings.xml
  WooCommerce/src/main/res/layout/activity_help.xml
  WooCommerce/src/main/res/layout/activity_logviewer.xml
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/main/res/layout/activity_site_picker.xml
  WooCommerce/src/main/res/layout/dialog_order_tracking_provider_list.xml
  WooCommerce/src/main/res/layout/fragment_image_viewer.xml
  WooCommerce/src/main/res/layout/fragment_product_image_viewer.xml
  WooCommerce/src/main/res/layout/fragment_product_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_wpmedia_viewer.xml
  WooCommerce/src/main/res/layout/view_toolbar.xml
  WooCommerce/src/main/res/layout/zs_activity_request.xml
  WooCommerce/src/main/res/layout/zs_activity_request_list.xml
  WooCommerce/src/main/res/menu/menu_action_bar.xml
  WooCommerce/src/main/res/menu/menu_order_list_fragment.xml
  WooCommerce/src/main/res/menu/menu_product_list_fragment.xml
  WooCommerce/src/main/res/menu/menu_search.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values-v23/themes.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/themes.xml
Labels: Architecture

#3193 Merge/5.4.1 into 5.5
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
Labels: Releases

#3190 Release/5.4.1 - Merge to Trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
  fastlane/metadata/android/ar/changelogs/88.txt
  fastlane/metadata/android/de-DE/changelogs/.txt
  fastlane/metadata/android/de-DE/changelogs/88.txt
  fastlane/metadata/android/es-ES/changelogs/.txt
  fastlane/metadata/android/es-ES/changelogs/88.txt
  fastlane/metadata/android/fr-FR/changelogs/.txt
  fastlane/metadata/android/fr-FR/changelogs/88.txt
  fastlane/metadata/android/id/changelogs/.txt
  fastlane/metadata/android/id/changelogs/88.txt
  fastlane/metadata/android/it-IT/changelogs/88.txt
  fastlane/metadata/android/iw-IL/changelogs/.txt
  fastlane/metadata/android/iw-IL/changelogs/88.txt
  fastlane/metadata/android/ja-JP/changelogs/.txt
  fastlane/metadata/android/ja-JP/changelogs/88.txt
  fastlane/metadata/android/ko-KR/changelogs/.txt
  fastlane/metadata/android/ko-KR/changelogs/88.txt
  fastlane/metadata/android/nl-NL/changelogs/.txt
  fastlane/metadata/android/nl-NL/changelogs/88.txt
  fastlane/metadata/android/pt-BR/changelogs/.txt
  fastlane/metadata/android/pt-BR/changelogs/88.txt
  fastlane/metadata/android/ru-RU/changelogs/.txt
  fastlane/metadata/android/ru-RU/changelogs/88.txt
  fastlane/metadata/android/sv-SE/changelogs/.txt
  fastlane/metadata/android/sv-SE/changelogs/88.txt
  fastlane/metadata/android/tr-TR/changelogs/.txt
  fastlane/metadata/android/tr-TR/changelogs/88.txt
  fastlane/metadata/android/zh-CN/changelogs/.txt
  fastlane/metadata/android/zh-CN/changelogs/88.txt
  fastlane/metadata/android/zh-TW/changelogs/.txt
  fastlane/metadata/android/zh-TW/changelogs/88.txt
Labels: Hotfix

#3187 Issue/2036 single product display
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailProductListView.kt
Labels: Order Details, [Type] Bug

#3180 Issue/3144 display shipping info
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/IProduct.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/IProductTest.kt
Labels: Shipping Labels, [Type] Bug

#3189 Issue/572 sqlite blob too big exception
  build.gradle
Labels: [Type] Crash

#3200 Issue/3195 collapsing toolbar child fragments
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/DisabledAppBarLayoutBehavior.kt
  WooCommerce/src/main/res/layout/activity_main.xml
Labels: UI fix

#3178 Product Images: Add drag&drop for images
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ConfirmRemoveProductImageDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/DraggableItemTouchHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FragmentUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ListUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  WooCommerce/src/main/res/drawable/ic_cancel.xml
  WooCommerce/src/main/res/layout/fragment_product_images.xml
  WooCommerce/src/main/res/layout/image_gallery_item.xml
  WooCommerce/src/main/res/menu/menu_dragging.xml
  WooCommerce/src/main/res/values/attrs.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: [Status] Needs Design Review

#3216 Fixed renamed icons
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
Labels: [Type] Bug

#3213 Issue/3196 remove fulfilment code
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderProductListPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderShipmentTrackingActionListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrdersModule.kt
  WooCommerce/src/main/res/layout/fragment_order_fulfillment.xml
  WooCommerce/src/main/res/layout/fragment_order_product_list.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentPresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderProductListPresenterTest.kt
Labels: Order Details, Order List, Tech Debt

#3203 issue/3154-login-site-address-crash-fix
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
Labels: Login, [Type] Crash

#3177 Add the shipping label creation info screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InfoScreenFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/res/drawable/img_woo_desk_character.xml
  WooCommerce/src/main/res/layout/fragment_info_screen.xml
  WooCommerce/src/main/res/layout/order_detail_product_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Order Details, Part of a WIP Feature, Shipping Labels

#3202 Merge release/5.5 into develop (conflict resolution)
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
Labels: Releases

#3110 Shipping labels: Update the order detail UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/WooPlugin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InfoScreenFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/drawable/img_woo_desk_character.xml
  WooCommerce/src/main/res/layout/feature_wip_notice.xml
  WooCommerce/src/main/res/layout/fragment_info_screen.xml
  WooCommerce/src/main/res/layout/order_detail_product_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
Labels: Order Details, Part of a WIP Feature, Shipping Labels

#3219 [Shipping Labels]: remove the bottom divider of the last product
  WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
Labels: Shipping Labels

#3201 issue/3057-product-list-crash-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsSettingsFragment.kt
  build.gradle
Labels: Product Details, [Type] Bug

#3217 Issue/2848 product variations scroll
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
Labels: Variation list, [Type] Bug

#2933 Add WireMock network mocking for screenshot test
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/assets/mocks/mappings/auth/auth-options.json
  WooCommerce/src/androidTest/assets/mocks/mappings/auth/is-available_email_not_available.json
  WooCommerce/src/androidTest/assets/mocks/mappings/auth/oauth2_token.json
  WooCommerce/src/androidTest/assets/mocks/mappings/devices/devices_id_delete.json
  WooCommerce/src/androidTest/assets/mocks/mappings/devices/devices_new_get.json
  WooCommerce/src/androidTest/assets/mocks/mappings/devices/devices_new_post.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/rest_api.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_leaderboards-year.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-hour.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-year.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_totals.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/products/products.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/reviews/products_reviews-all.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/settings/wc_settings_general.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/settings/wc_settings_products.json
  WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me.json
  WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_settings_get.json
  WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_sites.json
  WooCommerce/src/androidTest/assets/mocks/mappings/notifications/rest_v11_notifications.json
  WooCommerce/src/androidTest/assets/mocks/mappings/sites/rest_v11_sites_161477129.json
  WooCommerce/src/androidTest/assets/mocks/mappings/sites/site-info-wordpress-com.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-week.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-year.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_top_earners-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_top_earners-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_top_earners-week.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_top_earners-year.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-week.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-year.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AndroidNotifier.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AppComponentTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/AssetFileSource.java
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/InterceptorModuleTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/MockingInterceptor.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/TestBase.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/EmailAddressScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/MyStoreScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/res/xml/network_security_config.xml
Labels: Tests

#3221 Update Play Store copy
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/full_description.txt
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#3223 Testing: Update MockingInterceptor requests for okhttp3 v4.X
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/MockingInterceptor.kt
Labels: Tests

#3220 Show the confirm discard dialog when exiting product tags after adding new tags
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsFragment.kt
Labels: Product Details, [Type] Bug

#3222 Merge release/5.5 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/163.txt
  fastlane/metadata/android/ar/changelogs/173.txt
  fastlane/metadata/android/de-DE/changelogs/163.txt
  fastlane/metadata/android/de-DE/changelogs/173.txt
  fastlane/metadata/android/es-ES/changelogs/163.txt
  fastlane/metadata/android/es-ES/changelogs/173.txt
  fastlane/metadata/android/fr-FR/changelogs/163.txt
  fastlane/metadata/android/fr-FR/changelogs/173.txt
  fastlane/metadata/android/id/changelogs/163.txt
  fastlane/metadata/android/id/changelogs/173.txt
  fastlane/metadata/android/it-IT/changelogs/163.txt
  fastlane/metadata/android/it-IT/changelogs/173.txt
  fastlane/metadata/android/iw-IL/changelogs/163.txt
  fastlane/metadata/android/iw-IL/changelogs/173.txt
  fastlane/metadata/android/ja-JP/changelogs/163.txt
  fastlane/metadata/android/ja-JP/changelogs/173.txt
  fastlane/metadata/android/ko-KR/changelogs/163.txt
  fastlane/metadata/android/ko-KR/changelogs/173.txt
  fastlane/metadata/android/nl-NL/changelogs/163.txt
  fastlane/metadata/android/nl-NL/changelogs/173.txt
  fastlane/metadata/android/pt-BR/changelogs/163.txt
  fastlane/metadata/android/pt-BR/changelogs/173.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/163.txt
  fastlane/metadata/android/ru-RU/changelogs/173.txt
  fastlane/metadata/android/sv-SE/changelogs/163.txt
  fastlane/metadata/android/sv-SE/changelogs/173.txt
  fastlane/metadata/android/tr-TR/changelogs/163.txt
  fastlane/metadata/android/tr-TR/changelogs/173.txt
  fastlane/metadata/android/zh-CN/changelogs/163.txt
  fastlane/metadata/android/zh-CN/changelogs/173.txt
  fastlane/metadata/android/zh-TW/changelogs/163.txt
  fastlane/metadata/android/zh-TW/changelogs/173.txt
Labels: Releases

#3225 Shipping labels M2 feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: Shipping Labels

#3218 Redirect to the previous screen after survey completion
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
Labels: [Feat] In-app Feedback

#3227 Merge release/5.6 to develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#3229 Shipping label creation feature branch -> develop
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/WooPlugin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InfoScreenFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/img_woo_desk_character.xml
  WooCommerce/src/main/res/layout/feature_wip_notice.xml
  WooCommerce/src/main/res/layout/fragment_info_screen.xml
  WooCommerce/src/main/res/layout/order_detail_product_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
Labels: Part of a WIP Feature, Shipping Labels
