Repository woocommerce/woocommerce-android, pull requests merged in 2020-05, with the labels that each got.

#2356 Dark Mode: Update notification icon
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: Notifications, Style

#2347 Update Fastlane and other tools in preparation for screenshots automation
  .configure
  .configure-files/gradle.properties.enc
  Gemfile.lock
  fastlane/Pluginfile
Labels: Tooling

#2357 Product settings style tweaks
  WooCommerce/src/main/res/layout/fragment_aztec_editor.xml
  WooCommerce/src/main/res/layout/fragment_product_catalog_visibility.xml
  WooCommerce/src/main/res/layout/fragment_product_menu_order.xml
  WooCommerce/src/main/res/layout/fragment_product_settings.xml
  WooCommerce/src/main/res/layout/fragment_product_slug.xml
  WooCommerce/src/main/res/layout/fragment_product_status.xml
  WooCommerce/src/main/res/layout/fragment_product_visibility.xml
Labels: Product Settings, Style

#2361 issue/2354-saved-state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedCurrencyEditTextView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedEditTextView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedSpinnerView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCSavedState.kt
Labels: Low hanging fruit, Tech Debt

#2360 Merge 4.1 final to develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/122.txt
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/122.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/122.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/122.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/122.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/122.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/122.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/122.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/122.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/122.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/122.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/122.txt
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/122.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/122.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/122.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/122.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
Labels: Releases

#2359 Merge 4.1 final to master
  WooCommerce/build.gradle
  WooCommerce/src/main/res/layout/fragment_login_discovery_error.xml
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/122.txt
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/122.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/122.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/122.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/122.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/122.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/122.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/122.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/122.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/122.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/122.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/122.txt
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/122.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/122.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/122.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/122.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
Labels: Releases

#2368 Merge 4.2-rc-1 to develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
Labels: Releases

#2364 Issue/2363 product settings done button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/aztec/AztecEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/BaseProductSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductCatalogVisibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductMenuOrderFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSlugFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductStatusFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductVisibilityFragment.kt
Labels: Product Settings

#2376 issue/2375-product-description-duplication
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
Labels: Product Details, [Type] Bug

#2377 Issue/2366 product filters design changes
  WooCommerce/src/main/res/color/button_outlined_stroke_selector.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: Product List

#2379 Issue/2351 product settings tracks events
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSortingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSettingsFragment.kt
Labels: Tracks Events

#2382 Merge 4.2 release notes to develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#2381 Merge 4.2 release notes to master
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#2380 Issue/2362 product detail done button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductInventoryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingFragment.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
Labels: Product Details

#2398 issue/1729-viewpager-pointer-index-oob
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCViewPager.kt
  WooCommerce/src/main/res/layout/fragment_product_image_viewer.xml
Labels: Product Details, [Type] Crash

#2403 Fixed crash when entering dot values when updating product dimensions
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingFragment.kt
Labels: Product Details, [Type] Crash

#2404 Changed default sorting to name asc
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt
Labels: Product List, [Type] Bug

#2383 Product property building refactoring
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ProductPropertyExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductBackorderStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductStockStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyEditableView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyLinkView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertiesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertiesCardsDiffCallback.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertiesDiffCallback.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertyCardsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductProperty.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ComplexPropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/DividerViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/EditableViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/LinkViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ProductPropertyCardViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ProductPropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/PropertyGroupViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/PropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/RatingBarViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ReadMoreViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/LiveDataDelegate.kt
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/layout/product_property_cardview_layout.xml
  WooCommerce/src/main/res/layout/view_product_detail_divider.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  build.gradle
Labels: Architecture, Product Details

#2365 Add screen object pattern implementation + screengrab to write UI tests
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooCommerceTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/TabNavComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/EmailAddressScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/MagicLinkScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/PasswordScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/SiteAddressScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/WelcomeScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/MyStoreScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/StatsComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/BetaFeaturesScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/SettingsScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderSearchScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/ReviewsListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/SingleReviewScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/FirstMatcher.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/NestedScrollViewExtension.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/SupplierIdler.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/TestIdler.kt
  WooCommerce/src/debug/AndroidManifest.xml
Labels: Tooling

#2401 Issue/navigate safely
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerFragment.kt
Labels: Architecture

#2391 issue/2390-order-detail-status-design-tweaks
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailOrderStatusView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/order_detail_order_status.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Order Details, [Status] Needs Design Review

#2405 Add a product editing beta feature to the release notes
  RELEASE-NOTES.txt
Labels: Releases

#2413 Show future-dated orders in the ALL orders tab
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
Labels: Order List

#2396 issue/2395-order-detail-add-tracking
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailShipmentTrackingListView.kt
  WooCommerce/src/main/res/layout/fragment_order_fulfillment.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenterTest.kt
Labels: Order Details, [Status] Needs Design Review

#2399 issue/2372-order-detail-animation-crash
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
Labels: Order Details, [Type] Crash

#2411 Product editing banner fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsWIPNoticeCard.kt
  WooCommerce/src/main/res/layout/products_wip_notice.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Product List, [Type] Enhancement

#2423 Add pseudolocales support for debug builds
  WooCommerce/build.gradle
Labels: Accessibility, Localization, Tooling

#2422 issue/2371-image-viewer-crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
Labels: [Type] Crash

#2394 Issue/2392 order detail product card design tweaks
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentProductListCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/ProductListCardTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
  WooCommerce/src/main/res/layout/order_detail_product_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Order Details, [Status] Needs Design Review

#2421 Issue/2420 strict mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
Labels: Architecture

#2402 Prevent Null Appearing in Order Detail Title
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailFragment.kt
Labels: Order Details

#2434 Removed feature flag check for filter and sort in product list
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product List

#2435 Added logic to display stock status when there is no sku
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
Labels: Product Details

#2442 Fix a crash in Product details
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
Labels: Product Details, [Type] Crash

#2440 Set colorForeground to always use black for zendesk theme
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values/themes.xml
Labels: Style, Support, UI fix

#2414 Fix build failures in the integrated tests
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderDetailNavigationTest.kt
Labels: Broken Tests

#2438 Merge 4.2 final to master
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
Labels: Releases

#2437 Merge release/4.2 final to develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
Labels: Releases

#2444 Updates the WordPress Util lib hash to include a crash fix for product description
  WooCommerce/build.gradle
Labels: Product Details, [Type] Crash

#2441 Replace GlobalScope with scopes specific to the owner class
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BasePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt
Labels: Order Details, [Type] Crash

#2446 issue/2393-tracking-date-cut-off
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
Labels: Order Details

#2450 issue/2233-fix-cursor-position-product-title
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyEditableView.kt
Labels: Product Details, [Type] Bug

#2448 Merge 4.3 code freeze to develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
Labels: Releases

#2445 issue/2443-image-upload-progress
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
Labels: Product Details

#2439 Issue/2385 login tweaks
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/styles_login.xml
Labels: Login, Style, UI fix

#2454 Issue/2452 main activity leaked
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardStatsView.kt
Labels: Tech Debt

#2462 Hotfix: OutOfMemory crashes - Take 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Hotfix

#2472 Merge 4.2.1 to release/4.3
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Releases

#2475 Merge 4.3 release notes and 4.2.1 hotfix to master
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Releases

#2474 Merge 4.3 release notes and 4.2.1 hotfix to develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: Releases

#2470 issue/2467-wpmedia-null-url
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt
Labels: Product Details, [Type] Crash

#2477 Added logic to display view product on store menu button only for published products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
Labels: Product Details, [Type] Bug

#2478 Added logic to display keypad when aztec editor is first opened
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/aztec/AztecEditorFragment.kt
Labels: Product Details, [Type] Bug

#2465 Fix new build failures in androidTest
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/OrderFulfillmentProductListCardTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/ProductListCardTest.kt
Labels: Broken Tests

#2473 Issue/2469 no done for uploading images
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: Product Details

#2481 issue/2466-review-badge-on-rotation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
Labels: Product Review List

#2483 Revert notification icon to the W
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: Style

#2492 Issue/2476 product sale date fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product Details, [Type] Bug

#2493 Added logic to calculate tax only if quantity is not zero
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductListView.kt
Labels: Order Details, [Type] Crash

#2494 Added logic to refresh product list only if filters change
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
Labels: Product List

#2496 Fix Product details properties
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ProductPropertyExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductProperty.kt
Labels: Product Details

#2497 Issue/wellsql 1.6
  build.gradle
Labels: Architecture

#2491 Check for null before accessing views inside onTabSelected handler
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: Store Stats, [Type] Crash

#2499 Issue/2488 image delete confirmation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: Product Details

#2501 Display exact stock quantity in product detail
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
Labels: Product Details, [Type] Bug

#2500 Fix the empty billing address issue
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
Labels: Order Details

#2464 Build instrumentation tests in CI
  .circleci/config.yml
  .editorconfig
  gradle.properties-example
Labels: Tooling
