Repository woocommerce/woocommerce-android, pull requests merged in 2021-10, with the labels that each got.

#4923 Update in person payments dialog designs
  WooCommerce/src/main/res/layout/card_reader_connect_dialog.xml
  WooCommerce/src/main/res/layout/card_reader_payment_dialog.xml
  WooCommerce/src/main/res/layout/card_reader_tutorial_dialog.xml
  WooCommerce/src/main/res/layout/card_reader_update_dialog.xml
  WooCommerce/src/main/res/layout/card_reader_welcome_dialog.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_tutorial_viewpager_item.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
Labels: category: design, feature: mobile payments

#4921 Fix addon applied percentage
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt
  WooCommerce/src/test/resources/mocks/product_addon_metadata.json
Labels: feature: order details

#4920 Create Order Editing Feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: order details

#4924 Fix RTL issues for orders and product screens
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
  WooCommerce/src/main/res/layout/order_detail_note_list.xml
  WooCommerce/src/main/res/layout/order_detail_note_list_header.xml
  WooCommerce/src/main/res/layout/order_detail_order_status.xml
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list_item.xml
  WooCommerce/src/main/res/layout/order_list_item.xml
  WooCommerce/src/main/res/layout/product_property_view_vert_layout.xml
  WooCommerce/src/main/res/layout/refunds_detail_product_list_item.xml
  WooCommerce/src/main/res/layout/refunds_product_list_item.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: bug, category: i18n

#4925 Issue/4842 order list selected site crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
Labels: feature: order list, type: crash

#4919 Issue/4110 media adapter illegal state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt
Labels: type: crash, feature: product details

#4928 Merges the 7.6 final release into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesNotificationHandler.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/246.txt
  fastlane/metadata/android/ar/changelogs/249.txt
  fastlane/metadata/android/de-DE/changelogs/246.txt
  fastlane/metadata/android/de-DE/changelogs/249.txt
  fastlane/metadata/android/es-ES/changelogs/246.txt
  fastlane/metadata/android/es-ES/changelogs/249.txt
  fastlane/metadata/android/fr-FR/changelogs/246.txt
  fastlane/metadata/android/fr-FR/changelogs/249.txt
  fastlane/metadata/android/id/changelogs/246.txt
  fastlane/metadata/android/id/changelogs/249.txt
  fastlane/metadata/android/it-IT/changelogs/246.txt
  fastlane/metadata/android/it-IT/changelogs/249.txt
  fastlane/metadata/android/iw-IL/changelogs/246.txt
  fastlane/metadata/android/iw-IL/changelogs/249.txt
  fastlane/metadata/android/ja-JP/changelogs/246.txt
  fastlane/metadata/android/ja-JP/changelogs/249.txt
  fastlane/metadata/android/ko-KR/changelogs/246.txt
  fastlane/metadata/android/ko-KR/changelogs/249.txt
  fastlane/metadata/android/nl-NL/changelogs/246.txt
  fastlane/metadata/android/nl-NL/changelogs/249.txt
  fastlane/metadata/android/pt-BR/changelogs/246.txt
  fastlane/metadata/android/pt-BR/changelogs/249.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/246.txt
  fastlane/metadata/android/ru-RU/changelogs/249.txt
  fastlane/metadata/android/sv-SE/changelogs/246.txt
  fastlane/metadata/android/sv-SE/changelogs/249.txt
  fastlane/metadata/android/tr-TR/changelogs/246.txt
  fastlane/metadata/android/tr-TR/changelogs/249.txt
  fastlane/metadata/android/zh-CN/changelogs/246.txt
  fastlane/metadata/android/zh-CN/changelogs/249.txt
  fastlane/metadata/android/zh-TW/changelogs/246.txt
  fastlane/metadata/android/zh-TW/changelogs/249.txt
Labels: Releases

#4914 Add a feature flag for Jetpack CP project
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, status: feature-flagged, feature: jetpack cp

#4927 Issue/4926 collapsing toolbar rtl
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/res/layout/activity_main.xml
Labels: category: design

#4930 Revert "Remove redundant textAlignment property and reuse it through …
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
  WooCommerce/src/main/res/layout/order_detail_note_item.xml
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list_item.xml
  WooCommerce/src/main/res/layout/product_list_item.xml
  WooCommerce/src/main/res/layout/product_property_view_vert_layout.xml
  WooCommerce/src/main/res/layout/rating_property_view_layout.xml
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
  WooCommerce/src/main/res/layout/refund_by_items_shipping.xml
  WooCommerce/src/main/res/layout/refunds_detail_product_list_item.xml
  WooCommerce/src/main/res/layout/refunds_product_list_item.xml
  WooCommerce/src/main/res/layout/view_toggle_single_option.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: bug, priority: high, category: design

#4935 Merge 7.7 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#4945 Only show SSR menu if user is logged in and a site is selected.
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/res/layout/activity_help.xml
Labels: type: crash, feature: support

#4933 Jetpack CP: support signing in to Jetpack CP sites using WPCom credentials
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
  build.gradle
Labels: type: enhancement, status: feature-flagged, feature: jetpack cp

#4922 Add AddonRepository proper mocking at OrderDetailViewModelTest
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: feature: order details, category: unit tests

#5118 Fix state selection incorrect data mapping
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt
Labels: feature: order details

#5117 Issue/5110 quick order flag and toggle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_settings_beta.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: order details

#5071 Jetpack CP: image uploads
  build.gradle
Labels: type: enhancement, status: feature-flagged, feature: jetpack cp
