Repository woocommerce/woocommerce-android, pull requests merged in 2021-06, with the labels that each got.

#4115 issue/4114-auth-error-crash-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
Labels: feature: login, priority: critical, type: crash

#4096 Receipts 3 - printing
  WooCommerce/src/debug/kotlin/com.woocommerce.android/di/CardReaderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PrintHtmlHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/receipts/ReceiptDataMapper.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/receipts/ReceiptDataMapperTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/receipts/ReceiptCreator.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/receipts/ReceiptData.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/receipts/ReceiptCreatorTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4097 Issue/4039 receipts 3 tests
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/receipts/ReceiptDataMapperTest.kt
Labels: feature: mobile payments, status: do not merge, status: feature-flagged

#4116 Issue/3725 Polish connected/disconnected state UIs
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/res/drawable-night/img_card_reader_not_connected.xml
  WooCommerce/src/main/res/drawable/ic_info_outline_20dp.xml
  WooCommerce/src/main/res/drawable/reader_disconnected_state_number_background_oval.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_connected_state.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_disconnected_state.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_learn_more.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4128 Fix typo in Product Type Selector
  WooCommerce/src/main/res/values/strings.xml
Labels: category: i18n, feature: product list, type: bug

#4127 Merge release/6.8 into develop (rc-2)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
Labels: Releases

#4130 Improve how s3 repository is defined and define which dependencies it serves
  WooCommerce/build.gradle
Labels: category: tooling

#4124 Re-fetch order after payment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4091 Merge "illustration and design updates" feature branch.
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt
  WooCommerce/src/main/res/drawable-night/img_empty_my_store.xml
  WooCommerce/src/main/res/drawable-night/img_empty_orders_all_fulfilled.xml
  WooCommerce/src/main/res/drawable-night/img_empty_orders_loading.xml
  WooCommerce/src/main/res/drawable-night/img_empty_orders_no_orders.xml
  WooCommerce/src/main/res/drawable-night/img_empty_products.xml
  WooCommerce/src/main/res/drawable-night/img_empty_reviews.xml
  WooCommerce/src/main/res/drawable-night/img_empty_search.xml
  WooCommerce/src/main/res/drawable-night/img_login_jetpack_required.xml
  WooCommerce/src/main/res/drawable-night/img_print_with_phone.xml
  WooCommerce/src/main/res/drawable-night/img_what_is_jetpack.xml
  WooCommerce/src/main/res/drawable-night/img_woo_no_stores.xml
  WooCommerce/src/main/res/drawable-night/img_wpcom_error.xml
  WooCommerce/src/main/res/drawable/img_empty_my_store.xml
  WooCommerce/src/main/res/drawable/img_empty_orders_all_fulfilled.xml
  WooCommerce/src/main/res/drawable/img_empty_orders_loading.xml
  WooCommerce/src/main/res/drawable/img_empty_orders_no_orders.xml
  WooCommerce/src/main/res/drawable/img_empty_products.xml
  WooCommerce/src/main/res/drawable/img_empty_reviews.xml
  WooCommerce/src/main/res/drawable/img_empty_search.xml
  WooCommerce/src/main/res/drawable/img_login_jetpack_required.xml
  WooCommerce/src/main/res/drawable/img_print_with_phone.xml
  WooCommerce/src/main/res/drawable/img_what_is_jetpack.xml
  WooCommerce/src/main/res/drawable/img_woo_no_stores.xml
  WooCommerce/src/main/res/drawable/img_wpcom_error.xml
  WooCommerce/src/main/res/layout/fragment_login_jetpack_required.xml
  WooCommerce/src/main/res/layout/fragment_login_site_check_error.xml
  WooCommerce/src/main/res/layout/fragment_login_what_is_jetpack.xml
  WooCommerce/src/main/res/layout/fragment_my_store.xml
  WooCommerce/src/main/res/layout/fragment_print_shipping_label_info.xml
  WooCommerce/src/main/res/layout/wc_empty_view.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
Labels: category: design

#4120 Issue/3725 Clean up Stripe sdk on logout and on site change
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BasePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenterTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/TokenProvider.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
Labels: feature: mobile payments, status: feature-flagged

#4106 Set customer email on PaymentIntent
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: mobile payments, status: do not merge, status: feature-flagged

#4107 Set payment description
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: mobile payments, status: do not merge, status: feature-flagged

#4129 Receipt 6 - Replace custom html receipts with Stripe's receipts
  WooCommerce/src/debug/kotlin/com.woocommerce.android/di/CardReaderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PrintHtmlHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/receipts/ReceiptDataMapper.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/receipts/ReceiptDataMapperTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/ReceiptPaymentInfoMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardPaymentStatus.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/receipts/PaymentCardBrand.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/receipts/ReceiptCreator.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/receipts/ReceiptData.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/ReceiptPaymentInfoMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/receipts/ReceiptCreatorTest.kt
  libs/cardreader/src/test/resources/example_receipt_html.html
Labels: feature: mobile payments, status: do not merge, status: feature-flagged

#4132 Merge release/6.8 into develop – Release Notes
  .bundle/config
  Gemfile.lock
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Releases

#4133 Import strings from binary deps
  fastlane/Fastfile
Labels: category: i18n

#4136 Adds composite build support for WordPress-Login-Flow-Android
  WooCommerce/build.gradle
  local-builds.gradle-example
  settings.gradle
Labels: category: tooling, feature: login

#3978 Integrate encrypted logging
  .configure
  .configure-files/gradle.properties.enc
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/NetworkStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/CrashLoggingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/EnqueueSendingEncryptedLogs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/UploadEncryptedLogs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/UuidGenerator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WooLogFileProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/encryptedlogging/ObserveEncryptedLogsUploadResult.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/EnqueueSendingEncryptedLogsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/UploadEncryptedLogsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WooLogFileProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/encryptedlogging/ObserveEncryptedLogsUploadResultTest.kt
  gradle.properties-example
Labels: category: analytics, feature: support, type: enhancement

#4125 Fix `AddAttributeFragment` UI issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/res/layout/fragment_add_attribute.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details, needs: design, status: do not merge

#4141 Remove Extra Padding in Attribute Options Entry
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/res/layout/fragment_add_attribute_terms.xml
Labels: feature: variation details

#4137 Hilt Migration: migrate product details screens
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailBottomSheetModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductExternalLinkFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductExternalLinkModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsSettingsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductCatalogVisibilityModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductMenuOrderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSettingsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSlugModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductStatusModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductVisibilityModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeListModule.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  build.gradle
Labels: category: architecture, type: enhancement

#4151 Update google-services plugin to 4.3.8
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMMessageService.kt
Labels: category: tooling

#4148 Remove trash option from Product Status
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductStatusFragment.kt
  WooCommerce/src/main/res/layout/fragment_product_status.xml
Labels: feature: product details

#4163 Hilt Migration: Migrate Help screen.
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpModule.kt
Labels: category: architecture, type: enhancement

#4167 Hilt migration: migrate services
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/OrderFetcherModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesServiceModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMMessageService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMServiceModule.kt
Labels: category: architecture, type: enhancement

#4123 Shipping Labels: multiple bug fixes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
  WooCommerce/src/main/res/layout/fragment_label_format_options.xml
  WooCommerce/src/main/res/layout/fragment_print_shipping_label.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: shipping labels, type: bug

#4166 Fix NPE when loading refunds
  RELEASE-NOTES.txt
  build.gradle
Labels: feature: refunds, type: crash

#4173 Fix release version crash
  build.gradle
Labels: priority: high, type: crash

#4103 Shipping Labels: Finish Customs form
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Address.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabelPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressValidator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/main/res/layout/fragment_shipping_customs.xml
  WooCommerce/src/main/res/layout/shipping_customs_line_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachineTest.kt
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4174 Hilt migration for site picker activity
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerModule.kt
Labels: category: architecture, type: enhancement

#4024 Enable variable product creation
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypeBottomSheetBuilder.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details

#4192 Fix typo in product selector
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product list

#4117 Shipping Labels: update the logic of steps in the state machine
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachineTest.kt
Labels: feature: shipping labels, status: do not merge, status: feature-flagged, type: enhancement

#4168 [Mobile Payments] Add Printing tutorial dialog to order detail screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/PrintingInstructionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/res/layout/fragment_printing_instructions.xml
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments, needs: design

#4122 Shipping Labels: customs forms tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/viewmodel/BaseUnitTest.kt
Labels: category: unit tests, feature: shipping labels, status: feature-flagged

#4193 Use line_item id as unique identifier when displaying products
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundProductListAdapter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  build.gradle
Labels: feature: order details, type: bug

#4194 Issue/3726 Fixed buttons styles on order details screen
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/values/strings.xml
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#4190 issue/4181-overlapping-no-price-message
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
Labels: feature: variation list

#4198 Update login library to 0.0.2
  build.gradle
Labels: category: releases

#4199 Add the commit_strings private lane
  fastlane/Fastfile
Labels: Releases

#4139 Issue/4044 Basic detekt integration
  build.gradle
  config/detekt/baseline.xml
  config/detekt/detekt.yml
Labels: category: tooling

#4160 Update NotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
Labels: feature: notifications, type: bug

#4134 Shipping Labels: print commercial invoice
  .idea/codeStyles/Project.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailShippingLabelsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/Base64Decoder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FileDownloader.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/CustomProgressDialog.kt
  WooCommerce/src/main/res/layout/fragment_print_label_customs_form.xml
  WooCommerce/src/main/res/menu/menu_shipping_label.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/xml/provider_paths.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModelTest.kt
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4135 Enable leaving FetchingOrder dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4143 Issue/4142 Fix of formatting issues
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/TabNavComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/MagicLinkScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/MyStoreScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/StatsComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/BetaFeaturesScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/SettingsScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderSearchScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MiscExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ViewExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/DashboardStatsBarChart.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreDateRangeView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/network/OfflineStatusBarView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressSuggestionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ApplicationLifecycleMonitor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/BorderedImageView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCSavedState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCTextViewCompat.kt
Labels: category: tooling, status: do not merge

#4146 Issue/4047 Remove checkstyle IDEA plugin. Updated checkstyle rules
  .idea/checkstyle-idea.xml
  .idea/externalDependencies.xml
  README.md
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginAnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  config/checkstyle.xml
Labels: category: tooling

#4149 Issue/4048. Removed ktlint. Adjusted readme
  .circleci/config.yml
  .editorconfig
  README.md
  build.gradle
Labels: category: tooling, status: do not merge

#4152 Issue/4046 remove project xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: category: tooling

#4208 issue/4200-save-as-draft-6.9
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: feature: product details

#4203 Merge 6.9 code freeze into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#4213 Merge 6.9 beta 2 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  build.gradle
Labels: Releases

#4214 Project/27 detekt
  .circleci/config.yml
  .editorconfig
  .idea/checkstyle-idea.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/externalDependencies.xml
  README.md
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/TabNavComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/MagicLinkScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/MyStoreScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/StatsComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/BetaFeaturesScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/SettingsScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderSearchScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MiscExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ViewExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginAnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/DashboardStatsBarChart.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreDateRangeView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/network/OfflineStatusBarView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressSuggestionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ApplicationLifecycleMonitor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/BorderedImageView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCSavedState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCTextViewCompat.kt
  build.gradle
  config/checkstyle.xml
  config/detekt/baseline.xml
  config/detekt/detekt.yml
Labels: category: tooling

#4205 Change Dependabot config to use up-to-date config
  .github/dependabot.yml
Labels: category: tooling

#4211 Issue/3725 more readers found
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/res/drawable/ic_loop_24px.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersActionTest.kt
Labels: feature: mobile payments

#4175 Issue/3725 use backend feature flag for payments
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
Labels: feature: mobile payments

#4212 Issue/3725 more readers found UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/adapter/MultipleCardReadersFoundAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/adapter/MultipleCardReadersFoundDiffCallback.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooAnimUtils.kt
  WooCommerce/src/main/res/layout/card_reader_connect_reader_item.xml
  WooCommerce/src/main/res/layout/card_reader_connect_scanning_item.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments, needs: design, status: feature-flagged

#4219 Issue/3725 extract is collectable method
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
Labels: feature: mobile payments

#4216 Shipping Labels: international requirements for DHL
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Address.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressValidator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModelTest.kt
  build.gradle
Labels: feature: shipping labels, type: enhancement

#4229 Custom settings for kotlin in editorconfig file
  .editorconfig
Labels: category: tooling

#4224 Use hw card reader by default
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
Labels: feature: mobile payments, status: feature-flagged

#4223 Issue/3726 dialogs same size
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/drawable-night/img_card_reader_available.xml
  WooCommerce/src/main/res/drawable-night/img_celebration.xml
  WooCommerce/src/main/res/drawable-night/img_products_error.xml
  WooCommerce/src/main/res/drawable/ic_card_reader.xml
  WooCommerce/src/main/res/drawable/img_card_reader_available.xml
  WooCommerce/src/main/res/drawable/img_celebration.xml
  WooCommerce/src/main/res/drawable/img_products_error.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
  WooCommerce/src/main/res/values-land/dimens_payments.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/dimens_payments.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/themes.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4232 Merge 6.9 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#4226 issue/4225-manage-readers-overlap
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_disconnected_state.xml
Labels: feature: mobile payments

#4228 GitIgnore some IDEA files
  .gitignore
  .idea/codeStyleSettings.xml
  .idea/vcs.xml
Labels: category: tooling

#4238 Issue/4237 fix encrypted logging crash
  WooCommerce/proguard-rules.pro
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: priority: high, type: crash

#4241 issue/3836-big-titles-trial-pr
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BaseFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BaseFragmentView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreDateRangeView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreStatsView.kt
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/main/res/layout/fragment_my_store.xml
  WooCommerce/src/main/res/layout/my_store_date_bar.xml
  WooCommerce/src/main/res/layout/my_store_stats.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  config/detekt/baseline.xml
Labels: category: design, feature: stats

#4218 Issue/3726 fetch order when payment flow starts
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments, status: do not merge, status: feature-flagged

#4231 Add is_debug and build_type properties to Tracks events
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
Labels: category: analytics

#4204 Improve fetching orders on incoming notification
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderFetcher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListItemDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  build.gradle
  config/detekt/baseline.xml
Labels: category: performance, feature: notifications, feature: order details, feature: order list

#4251 Attempt to fix some image upload issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUtils.kt
Labels: feature: product details, type: bug

#4250 Shipping Labels: enable customs feature and update tracking
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreationFeatures.kt
  WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
  WooCommerce/src/main/res/menu/menu_shipping_label.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels, type: task

#4240 Connecting to reader - tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTrackerWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
Labels: category: analytics, feature: mobile payments

#4230 Convention doc with unit test naming convention
  CONVENTION.md
Labels: category: tooling

#4244 Payment Flow - tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#4207 Make installGitHooks task optional and use Task Configuration Avoidance
  build.gradle
Labels: category: tooling

#4252 nick/payment-pulse-anim
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/res/animator/pulse.xml
  WooCommerce/src/main/res/drawable/img_card_reader_connecting.xml
  WooCommerce/src/main/res/drawable/img_card_reader_scanning.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
Labels: feature: mobile payments, needs: design

#4233 Fix Flaky Variations Number Problem
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
Labels: feature: variation details

#4261 Tracking - Card Reader Software Update
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#4265 Issue/3725 remove settings fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/CardReaderSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/res/layout/fragment_settings_card_reader.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  config/detekt/baseline.xml
Labels: feature: mobile payments, type: technical debt

#4254 Tracking receipts
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PrintHtmlHelper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#4234 Shipping Labels: add payment method
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/UrlInterceptor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreationFeatures.kt
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_payment.xml
  WooCommerce/src/main/res/layout/fragment_wpcom_webview.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_payment_list.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_payment_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModelTest.kt
  config/detekt/baseline.xml
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4268 Update `Dependabot` to limit 5 opened PRs
  .github/dependabot.yml
Labels: category: tooling

#4271 Set up a `CODEOWNERS` file
  .github/CODEOWNERS
Labels: category: tooling

#4255 LongParameterList rule relaxation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginDiscoveryErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PriceUtils.kt
  config/detekt/baseline.xml
  config/detekt/detekt.yml
Labels: category: tooling

#4285 Detekt TooManyFunctions rule relaxation
  config/detekt/baseline.xml
  config/detekt/detekt.yml
Labels: category: tooling

#4281 issue/4274-payment-wording-tweaks
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_learn_more.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#4247 Issue/3725 dialog same size
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
  WooCommerce/src/main/res/layout/card_reader_connect_reader_item.xml
  WooCommerce/src/main/res/layout/card_reader_connect_scanning_item.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/CardReaderImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReader.kt
Labels: feature: mobile payments

#4283 Merge 6.9 final into develop
  WooCommerce/build.gradle
  WooCommerce/proguard-rules.pro
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/223.txt
  fastlane/metadata/android/ar/changelogs/227.txt
  fastlane/metadata/android/de-DE/changelogs/223.txt
  fastlane/metadata/android/de-DE/changelogs/227.txt
  fastlane/metadata/android/es-ES/changelogs/223.txt
  fastlane/metadata/android/es-ES/changelogs/227.txt
  fastlane/metadata/android/fr-FR/changelogs/223.txt
  fastlane/metadata/android/fr-FR/changelogs/227.txt
  fastlane/metadata/android/id/changelogs/223.txt
  fastlane/metadata/android/id/changelogs/227.txt
  fastlane/metadata/android/it-IT/changelogs/223.txt
  fastlane/metadata/android/it-IT/changelogs/227.txt
  fastlane/metadata/android/iw-IL/changelogs/223.txt
  fastlane/metadata/android/iw-IL/changelogs/227.txt
  fastlane/metadata/android/ja-JP/changelogs/223.txt
  fastlane/metadata/android/ja-JP/changelogs/227.txt
  fastlane/metadata/android/ko-KR/changelogs/223.txt
  fastlane/metadata/android/ko-KR/changelogs/227.txt
  fastlane/metadata/android/nl-NL/changelogs/223.txt
  fastlane/metadata/android/nl-NL/changelogs/227.txt
  fastlane/metadata/android/pt-BR/changelogs/223.txt
  fastlane/metadata/android/pt-BR/changelogs/227.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/223.txt
  fastlane/metadata/android/ru-RU/changelogs/227.txt
  fastlane/metadata/android/sv-SE/changelogs/223.txt
  fastlane/metadata/android/sv-SE/changelogs/227.txt
  fastlane/metadata/android/tr-TR/changelogs/223.txt
  fastlane/metadata/android/tr-TR/changelogs/227.txt
  fastlane/metadata/android/zh-CN/changelogs/223.txt
  fastlane/metadata/android/zh-CN/changelogs/227.txt
  fastlane/metadata/android/zh-TW/changelogs/223.txt
  fastlane/metadata/android/zh-TW/changelogs/227.txt
Labels: Releases

#4303 Issue/4291 crash on insert card
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
  libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentActionTest.kt
Labels: feature: mobile payments

#4269 Fix selectable Attributes hint visibility
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
Labels: feature: product details, type: bug

#4301 Update Products List Banner for Variations
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product list

#4287 Issue 3957. Check software update status after successful update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments

#4299 Enable Present Card Payments in release build
  .circleci/config.yml
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/release/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  libs/cardreader/build.gradle
  libs/cardreader/src/main/AndroidManifest.xml
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/TokenProvider.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/actions/CheckSoftwareUpdatesAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/actions/InstallSoftwareUpdateAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/ProcessPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/LogWrapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/PaymentIntentParametersFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
Labels: feature: mobile payments

#4306 Improve order status update snackbars
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: category: design, feature: order details, type: enhancement

#4300 Bump stripe terminal sdk version
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#4293 Remove newly created Attribute when no Terms is defined
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
Labels: feature: product details, type: bug

#4267 Support decimal quantities in Orders, and fix shipping labels handling of them
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabelPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachineTest.kt
  build.gradle
Labels: feature: order details, feature: shipping labels, status: do not merge, type: enhancement

#4304 Smaller bottom padding to compensate bottom inset
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
  WooCommerce/src/main/res/values/dimens_payments.xml
Labels: feature: mobile payments

#4294 Provide `debug` release variant for `debug` builds in Sentry
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/BuildConfigWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProviderTest.kt
Labels: category: tooling
