Repository woocommerce/woocommerce-android, pull requests merged in 2021-09, with the labels that each got.

#4683 Product filter by category performance and UI improvements.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterResult.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/res/layout/fragment_product_filter_list.xml
  WooCommerce/src/main/res/layout/fragment_product_filter_option_list.xml
  WooCommerce/src/main/res/layout/skeleton_product_filter_options_categories_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_product_filters.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
Labels: feature: product list

#4693 Refactoring: two different flows for UpdateAvailability and UpdateStatus
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/event/CardReaderEvent.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/event/SoftwareUpdateAvailability.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/event/SoftwareUpdateStatus.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManager.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManagerTest.kt
Labels: feature: mobile payments

#4687 Create Add-ons beta toggle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/settings/BetaFeaturesScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_settings_beta.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: app settings

#4169 Upgrade gradle to 7.1.1 & Android Gradle Plugin to 4.2.2
  WooCommerce/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: category: tooling

#4688 Create Add-ons track events
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt
Labels: category: analytics

#4712 Moved the dispatcher registration logic to the init block
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: feature: order details, type: crash

#4713 Fix is order paid condition
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
Labels: feature: mobile payments

#4689 Remove addons feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: order details, feature: product details

#4715 Add new feature: Product Filtering By Category
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterResult.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/res/layout/fragment_product_filter_list.xml
  WooCommerce/src/main/res/layout/fragment_product_filter_option_list.xml
  WooCommerce/src/main/res/layout/skeleton_product_filter_options_categories_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_product_filters.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
Labels: type: enhancement, feature: product list

#4708 "What's New" Screen": Feature Flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: status: feature-flagged

#4697 Fix runtime crash when using sample `google-services.json` file
  WooCommerce/google-services.json-example
Labels: type: task, type: crash, category: tooling

#4700 Issue/4660 add support for optional firmware updates
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
Labels: feature: mobile payments

#4723 Update detekt version to 1.18.1
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/network/ConnectionChangeReceiver.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandlerTest.kt
  build.gradle
  config/detekt/baseline.xml
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/actions/InstallSoftwareUpdateActionTest.kt
Labels: category: tooling

#4716 Issue/4661 disconnect button does not work
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
Labels: feature: mobile payments

#4721 Merge 7.4 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/238.txt
  fastlane/metadata/android/ar/changelogs/242.txt
  fastlane/metadata/android/de-DE/changelogs/238.txt
  fastlane/metadata/android/de-DE/changelogs/242.txt
  fastlane/metadata/android/es-ES/changelogs/238.txt
  fastlane/metadata/android/es-ES/changelogs/242.txt
  fastlane/metadata/android/fr-FR/changelogs/238.txt
  fastlane/metadata/android/fr-FR/changelogs/242.txt
  fastlane/metadata/android/id/changelogs/238.txt
  fastlane/metadata/android/id/changelogs/242.txt
  fastlane/metadata/android/it-IT/changelogs/238.txt
  fastlane/metadata/android/it-IT/changelogs/242.txt
  fastlane/metadata/android/iw-IL/changelogs/238.txt
  fastlane/metadata/android/iw-IL/changelogs/242.txt
  fastlane/metadata/android/ja-JP/changelogs/238.txt
  fastlane/metadata/android/ja-JP/changelogs/242.txt
  fastlane/metadata/android/ko-KR/changelogs/238.txt
  fastlane/metadata/android/ko-KR/changelogs/242.txt
  fastlane/metadata/android/nl-NL/changelogs/238.txt
  fastlane/metadata/android/nl-NL/changelogs/242.txt
  fastlane/metadata/android/pt-BR/changelogs/238.txt
  fastlane/metadata/android/pt-BR/changelogs/242.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/238.txt
  fastlane/metadata/android/ru-RU/changelogs/242.txt
  fastlane/metadata/android/sv-SE/changelogs/238.txt
  fastlane/metadata/android/sv-SE/changelogs/242.txt
  fastlane/metadata/android/tr-TR/changelogs/238.txt
  fastlane/metadata/android/tr-TR/changelogs/242.txt
  fastlane/metadata/android/zh-CN/changelogs/238.txt
  fastlane/metadata/android/zh-CN/changelogs/242.txt
  fastlane/metadata/android/zh-TW/changelogs/238.txt
  fastlane/metadata/android/zh-TW/changelogs/242.txt
Labels: Releases

#4724 Issue/4553 check total
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
Labels: feature: mobile payments

#4717 Issue/4699 New update dialog design
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/WCSettingsToggleOptionView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiHelpers.kt
  WooCommerce/src/main/res/drawable/img_card_reader_update_progress.xml
  WooCommerce/src/main/res/layout/card_reader_update_dialog.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/actions/CheckSoftwareUpdatesAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/actions/InstallAvailableSoftwareUpdateAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManagerTest.kt
Labels: feature: mobile payments

#4727 Remove team from Dependabot default reviewers
  .github/dependabot.yml
Labels: category: tooling

#4731 "What's New" Screen: Create and show basic Feature Announcement dialog when the menu item is selected
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt
  WooCommerce/src/main/res/layout/feature_announcement_dialog_fragment.xml
  WooCommerce/src/main/res/layout/feature_announcement_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
Labels: status: feature-flagged

#4736 Merge 7.5 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#4739 Issue/4732 Filter supported readers
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/CardReaderType.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersActionTest.kt
Labels: feature: mobile payments

#4720 Background Image Upload: new logic for handling background work
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesNotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesServiceWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/AddProductDownloadBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/media/ProductImagesUploadWorkerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/WooLog.kt
Labels: needs: design, feature: product details

#4750 Issue/4749 Use of terminal application delegate
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalApplicationDelegateWrapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
Labels: feature: mobile payments

#4733 Update save for later text
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#4737 Handle order Add-ons loading failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt
  WooCommerce/src/main/res/layout/fragment_ordered_addon.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt
Labels: feature: order details

#4751 Use Add-on domain models
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductAddon.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonsExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/ProductAddonCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/options/AddonOptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/product/ProductAddonsFragment.kt
  WooCommerce/src/main/res/layout/product_addon_card.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/ProductAddonTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt
  WooCommerce/src/test/resources/mocks/product_addon_metadata.json
  build.gradle
Labels: type: enhancement, feature: order details, feature: product details

#4756 Issue/4754 Connection status not in sync between 2 sources
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/TerminalListenerImpl.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/TerminalListenerImplTest.kt
Labels: status: do not merge, feature: mobile payments

#4747 issue/4676 Implemented support for update cancelation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  libs/cardreader/build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/TerminalListenerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/TerminalListenerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManagerTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4763 Fix button not displayed for Orders containing Global Add-ons only
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonRepositoryTest.kt
Labels: feature: order details

#4755 Disable google pay on merchants phone
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialogFragment.kt
Labels: feature: mobile payments

#4761 Make tabLayout visible in the appbar after coming back from a searched order screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: enhancement

#4753 Background image uploads: product creation case
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: type: enhancement, feature: product details

#4762 Shipping Labels: fix international DHL purchase
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  build.gradle
Labels: type: bug, status: do not merge, feature: shipping labels

#4726 Issue/4725 Reset state on disconnect
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
Labels: feature: mobile payments

#4771 Merge 7.5 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#4766 Issue/4765 handle required update failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4752 Update utils and fluxc versions
  WooCommerce/build.gradle
  build.gradle
Labels: type: technical debt

#4768 Issue/4767 automattic optinal update start
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments

#4770 Product Image Uploads: auto dismiss the error snackbar when needed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: type: enhancement, feature: product details

#4787 Fixes issue/4785-fix-concurrentmodificationexception
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationMessageHandler.kt
Labels: type: crash, feature: notifications

#4788 Fixes #4786-order-detail-notification-bug-fix
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: type: bug, feature: order details, feature: notifications

#4790 Fix a navigation crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/navigation/KeepStateNavigator.kt
Labels: type: crash, feature: notifications

#4776 Fix activity restoration on ProductDetail screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: feature: product details

#4673 issue/4525-support-push-notifications-for-all-stores
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationChannelType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListFragment.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/NotificationTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationMessageHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: type: enhancement, feature: notifications

#4793 Fixes issue/4792-order-detail-duplicate-notes
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: type: bug, feature: order details

#4777 set tax status field to Taxable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
Labels: type: enhancement

#4760 "What's New" Screen: Add sample announcement and style it
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureAnnouncement.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementViewModel.kt
  WooCommerce/src/main/res/layout/feature_announcement_dialog_fragment.xml
  WooCommerce/src/main/res/layout/feature_announcement_list_item.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: app settings

#4801 Nick/hack week switch store button
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCPromoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCPromoTooltip.kt
  WooCommerce/src/main/res/layout/dialog_promo.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: app settings

#4773 Make add-ons view available for refunds
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/res/layout/refunds_detail_product_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
Labels: feature: refunds

#4780 Fix tracking order details events multiple times
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
Labels: type: bug, feature: order details

#4798 Fixed incorrect continuation called when fetching product for a review
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt
Labels: type: bug, feature: review details

#4813 Bring back Android team to Dependabot default reviewers
  .github/dependabot.yml
Labels: category: tooling

#4811 Product Images Upload: remove temp files after the upload
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUtils.kt
Labels: type: enhancement, feature: product details

#4819 Show the create shipping label's button if the store is not part of in-person payment's beta program
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: bug, priority: high, feature: shipping labels, feature: mobile payments

#4803 SSR: Display screen, show example data, add share and copy functionality
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/ResourceProvider.kt
  WooCommerce/src/main/res/layout/activity_help.xml
  WooCommerce/src/main/res/layout/activity_ssr.xml
  WooCommerce/src/main/res/raw/system_status.json
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: support

#4800 Update login lib - show network error
  build.gradle
Labels: type: enhancement, feature: login

#4815 Merge 7.5 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/navigation/KeepStateNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonRepository.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/242.txt
  fastlane/metadata/android/ar/changelogs/246.txt
  fastlane/metadata/android/de-DE/changelogs/242.txt
  fastlane/metadata/android/de-DE/changelogs/246.txt
  fastlane/metadata/android/es-ES/changelogs/242.txt
  fastlane/metadata/android/es-ES/changelogs/246.txt
  fastlane/metadata/android/fr-FR/changelogs/242.txt
  fastlane/metadata/android/fr-FR/changelogs/246.txt
  fastlane/metadata/android/id/changelogs/242.txt
  fastlane/metadata/android/id/changelogs/246.txt
  fastlane/metadata/android/it-IT/changelogs/242.txt
  fastlane/metadata/android/it-IT/changelogs/246.txt
  fastlane/metadata/android/iw-IL/changelogs/242.txt
  fastlane/metadata/android/iw-IL/changelogs/246.txt
  fastlane/metadata/android/ja-JP/changelogs/242.txt
  fastlane/metadata/android/ja-JP/changelogs/246.txt
  fastlane/metadata/android/ko-KR/changelogs/242.txt
  fastlane/metadata/android/ko-KR/changelogs/246.txt
  fastlane/metadata/android/nl-NL/changelogs/242.txt
  fastlane/metadata/android/nl-NL/changelogs/246.txt
  fastlane/metadata/android/pt-BR/changelogs/242.txt
  fastlane/metadata/android/pt-BR/changelogs/246.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/242.txt
  fastlane/metadata/android/ru-RU/changelogs/246.txt
  fastlane/metadata/android/sv-SE/changelogs/242.txt
  fastlane/metadata/android/sv-SE/changelogs/246.txt
  fastlane/metadata/android/tr-TR/changelogs/242.txt
  fastlane/metadata/android/tr-TR/changelogs/246.txt
  fastlane/metadata/android/zh-CN/changelogs/242.txt
  fastlane/metadata/android/zh-CN/changelogs/246.txt
  fastlane/metadata/android/zh-TW/changelogs/242.txt
  fastlane/metadata/android/zh-TW/changelogs/246.txt
Labels: Releases

#4805 Remove `multidex`
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  build.gradle
Labels: category: tooling, type: technical debt

#4821 SSR: Add formatter to match core behavior
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCSSRModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivityViewModel.kt
  build.gradle
Labels: status: do not merge, feature: support

#4826 Readme.md update. Fix invalid link to OAuth2 docs
  README.md
Labels: priority: low, type: documentation

#4828 Media Upload: check url before marking upload as successful
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
Labels: type: crash, feature: product details

#4817 Issue/4764 handle cancelation and restart connection
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4830 SSR: Fetch real data instead of example
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCSSRModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivityViewModel.kt
  WooCommerce/src/main/res/layout/activity_ssr.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: support

#4808 Issue/4806 convert fetch order notes into suspendable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenterTest.kt
  build.gradle
Labels: status: do not merge, type: technical debt

#4832 Initial commit for displaying specific error message when the total of the product is less than $0.50.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: feature: mobile payments

#4840 Issue/4774 Sort and display filter categories in parent-child hierarchy
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListFragment.kt
Labels: type: enhancement, good first issue

#4839 Issue/4825 Fetching and usage of the location id
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderLocationRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderLocationRepositoryTest.kt
  build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
Labels: feature: mobile payments

#4841 Issue/4778 update error low battery
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/main/res/drawable-night/img_card_reader_update_failed_battery_low.xml
  WooCommerce/src/main/res/drawable/img_card_reader_update_failed_battery_low.xml
  WooCommerce/src/main/res/layout/card_reader_update_dialog.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/event/SoftwareUpdateStatus.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/UpdateErrorMapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/UpdateErrorMapperTest.kt
Labels: feature: mobile payments

#4838 Handle add-on percentage price values
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/AddonsExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/ProductAddonCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/options/AddonOptionListAdapter.kt
Labels: feature: order details, feature: product details

#4837 Issue/4131 product tags adapter illegal state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt
Labels: type: crash

#4836 Issue/4835 feedback request crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: type: crash

#4852 Stop clearing notifications when switching stores
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
Labels: type: bug, feature: notifications

#4831 Merge 7.6 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#4854 Merge 7.6 beta 2 and release notes into develop
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: Releases

#4855 Issue/4823 show specific error message when total is less than 0.50 dollar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
Labels: feature: mobile payments

#4850 Issue/4848 Remove lint xml suppressing
  WooCommerce/lint.xml
Labels: feature: mobile payments

#4812 Issue/4806 convert fetch shipment tracking into suspendable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  build.gradle
Labels: feature: order details, type: technical debt

#4824 Hack week/add device info in app logs
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/WooLogViewerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DeviceInfo.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
Labels: feature: support

#4858 Issue/4847 Handling of check mobile device message
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothCardReaderMessages.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/AdditionalInfoMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImplTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/AdditionalInfoMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
Labels: feature: mobile payments

#4861 Initial commit for removing unused classes in cardreader module
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
Labels: feature: mobile payments

#4853 Enable setting negative values for product regular price
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModel.kt
  WooCommerce/src/main/res/layout/fragment_product_pricing.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModelTest.kt
Labels: type: enhancement, feature: product details

#4871 Issue/3173 Disable shipping for external products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailBottomSheetBuilder.kt
Labels: type: bug, feature: product details

#4869 Enable card present payments on all stores
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
Labels: feature: mobile payments

#4870 Issue/4859 Update progress indicator
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/CircleProgressOverlayView.kt
  WooCommerce/src/main/res/drawable/img_card_reader_update_progress.xml
  WooCommerce/src/main/res/layout/card_reader_update_dialog.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/attrs.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
Labels: feature: mobile payments

#4882 Fix race condition when refreshing product detail cards
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: type: bug, feature: product details

#4799 Update login lib - Run XML-RPC discovery during SiteAddress login flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  build.gradle
Labels: type: enhancement, status: do not merge, feature: login

#4890 Release SSR feature
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCSSRModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/ResourceProvider.kt
  WooCommerce/src/main/res/layout/activity_help.xml
  WooCommerce/src/main/res/layout/activity_ssr.xml
  WooCommerce/src/main/res/raw/system_status.json
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: support

#4884 Issue/4579 onboarding dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderWelcomeDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderWelcomeViewModel.kt
  WooCommerce/src/main/res/drawable-night/img_woman_payment_card.xml
  WooCommerce/src/main/res/drawable/img_woman_payment_card.xml
  WooCommerce/src/main/res/layout/card_reader_welcome_dialog.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/dimens_payments.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderWelcomeViewModelTest.kt
Labels: feature: mobile payments

#4883 Design Changes - Dark mode top bar background color
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: enhancement

#4918 Hotfix: fix crash related to product images upload
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesNotificationHandler.kt
Labels: type: crash, feature: product details
