Repository woocommerce/woocommerce-android, pull requests merged in 2021-03, with the labels that each got.

#3646 Merge release/6.1 -> develop after first beta
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/aztec/AztecEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsRepository.kt
Labels: Releases

#3620 "Add Variation" Button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/ActionableEmptyView.kt
  WooCommerce/src/main/res/drawable/ic_add_variations.xml
  WooCommerce/src/main/res/layout/fragment_variation_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Product Details, [Status] Needs Design Review

#3647 Shipping labels: Shipping carriers - part 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/BigDecimalExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingRate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/main/res/color/checkbox_shipping_rate_bg_selector.xml
  WooCommerce/src/main/res/layout/fragment_shipping_carrier_rates.xml
  WooCommerce/src/main/res/layout/shipping_rate_list.xml
  WooCommerce/src/main/res/layout/shipping_rate_list_item.xml
  WooCommerce/src/main/res/layout/skeleton_create_shipping_label.xml
  WooCommerce/src/main/res/layout/skeleton_create_shipping_label_item.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_carrier_list.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_carrier_rate.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachineTest.kt
  build.gradle
Labels: Shipping Labels

#3650 Issue/3207 add attribute part3
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListAdapter.kt
  WooCommerce/src/main/res/layout/attribute_term_list_item.xml
  WooCommerce/src/main/res/layout/fragment_add_attribute.xml
  WooCommerce/src/main/res/layout/fragment_add_attribute_terms.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Variation list

#3659 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: Tooling

#3656 Added fix for a login string to override string validation
  WooCommerce/src/main/res/values/strings.xml
Labels: Login

#3649 Add app version to surveys metadata
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/feedback/SurveyTypeTest.kt
Labels: [Feat] In-app Feedback, type: enhancement

#3654 Shipping labels: Creation summary
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingRate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
Labels: Shipping Labels

#3663 Merge release/6.1 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/199.txt
  fastlane/metadata/android/ar/changelogs/202.txt
  fastlane/metadata/android/de-DE/changelogs/199.txt
  fastlane/metadata/android/de-DE/changelogs/202.txt
  fastlane/metadata/android/es-ES/changelogs/199.txt
  fastlane/metadata/android/es-ES/changelogs/202.txt
  fastlane/metadata/android/fr-FR/changelogs/199.txt
  fastlane/metadata/android/fr-FR/changelogs/202.txt
  fastlane/metadata/android/id/changelogs/199.txt
  fastlane/metadata/android/id/changelogs/202.txt
  fastlane/metadata/android/it-IT/changelogs/199.txt
  fastlane/metadata/android/it-IT/changelogs/202.txt
  fastlane/metadata/android/iw-IL/changelogs/199.txt
  fastlane/metadata/android/iw-IL/changelogs/202.txt
  fastlane/metadata/android/ja-JP/changelogs/199.txt
  fastlane/metadata/android/ja-JP/changelogs/202.txt
  fastlane/metadata/android/ko-KR/changelogs/199.txt
  fastlane/metadata/android/ko-KR/changelogs/202.txt
  fastlane/metadata/android/nl-NL/changelogs/199.txt
  fastlane/metadata/android/nl-NL/changelogs/202.txt
  fastlane/metadata/android/pt-BR/changelogs/199.txt
  fastlane/metadata/android/pt-BR/changelogs/202.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/199.txt
  fastlane/metadata/android/ru-RU/changelogs/202.txt
  fastlane/metadata/android/sv-SE/changelogs/199.txt
  fastlane/metadata/android/sv-SE/changelogs/202.txt
  fastlane/metadata/android/tr-TR/changelogs/199.txt
  fastlane/metadata/android/tr-TR/changelogs/202.txt
  fastlane/metadata/android/zh-CN/changelogs/199.txt
  fastlane/metadata/android/zh-CN/changelogs/202.txt
  fastlane/metadata/android/zh-TW/changelogs/199.txt
  fastlane/metadata/android/zh-TW/changelogs/202.txt
Labels: Releases

#3648 Update Order class with ShippingLine item.
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  build.gradle
Labels: Refunds

#3658 Shipping labels: Checkbox styles
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_payment.xml
  WooCommerce/src/main/res/layout/product_category_list_item.xml
  WooCommerce/src/main/res/layout/shipping_rate_list_item.xml
  WooCommerce/src/main/res/layout/view_shipping_label_order_summary.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: Shipping Labels

#3669 Merge release/6.2 into develop after code freeze
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#3660 Issue/3207 add attribute part4
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListAdapter.kt
Labels: Variation list

#3670 Login crash fix
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/res/layout-land/fragment_login_jetpack_required.xml
Labels: type: crash

#3672 Update editorconfig
  .editorconfig
Labels: Tooling

#3676 Merge release/6.2 into develop after beta-fix + Editorial copy
  RELEASE-NOTES.txt
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/res/layout-land/fragment_login_jetpack_required.xml
Labels: Releases

#3635 Track ORDERS_LIST_LOADED
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  build.gradle
Labels: Order List, Tracks Events

#3680 In add new product setting, set review flag to be enabled by default.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: Product Settings

#3679 Show "Downloadable" label on Product type row.
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Product Details, type: enhancement

#3653 Add Dependabot configuration file
  .github/dependabot.yml
Labels: Tech Debt, type: enhancement

#3682 Order details: Show menu when tracking info area is tapped.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailShipmentTrackingListAdapter.kt
  WooCommerce/src/main/res/layout/order_detail_shipment_tracking_list_item.xml
Labels: Order Details

#3705 Use array of longs for passing product ids
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GroupedProductListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModelTest.kt
Labels: Product List

#3694 Issue/3207 add attribute part5
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductAttribute.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/CombinedAttributeListAdapter.kt
  WooCommerce/src/main/res/layout/fragment_add_attribute_terms.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: Variation list

#3706 Issue/3472 fix first day of week
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StatsGranularityExt.kt
  build.gradle
Labels: Dashboard, Store Stats, [Status] Not Ready for Merge

#3716 Add translatable="false" to strings that reference other strings
  WooCommerce/src/main/res/values/strings.xml
Labels: Product List

#3693 Custom order status
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: Order Details

#3719 fix/rollback-to-commons-text-1.8
  WooCommerce/build.gradle
Labels: duplicate, type: crash

#3708 Issue/3700 remove combined attr
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/CombinedAttributeModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductGlobalAttribute.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/CombinedAttributeListAdapter.kt
Labels: Variation list

#3717 Merge release/6.2 into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  fastlane/metadata/android/ar/changelogs/202.txt
  fastlane/metadata/android/ar/changelogs/204.txt
  fastlane/metadata/android/de-DE/changelogs/202.txt
  fastlane/metadata/android/de-DE/changelogs/204.txt
  fastlane/metadata/android/es-ES/changelogs/202.txt
  fastlane/metadata/android/es-ES/changelogs/204.txt
  fastlane/metadata/android/fr-FR/changelogs/202.txt
  fastlane/metadata/android/fr-FR/changelogs/204.txt
  fastlane/metadata/android/id/changelogs/202.txt
  fastlane/metadata/android/id/changelogs/204.txt
  fastlane/metadata/android/it-IT/changelogs/202.txt
  fastlane/metadata/android/it-IT/changelogs/204.txt
  fastlane/metadata/android/iw-IL/changelogs/202.txt
  fastlane/metadata/android/iw-IL/changelogs/204.txt
  fastlane/metadata/android/ja-JP/changelogs/202.txt
  fastlane/metadata/android/ja-JP/changelogs/204.txt
  fastlane/metadata/android/ko-KR/changelogs/202.txt
  fastlane/metadata/android/ko-KR/changelogs/204.txt
  fastlane/metadata/android/nl-NL/changelogs/202.txt
  fastlane/metadata/android/nl-NL/changelogs/204.txt
  fastlane/metadata/android/pt-BR/changelogs/202.txt
  fastlane/metadata/android/pt-BR/changelogs/204.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/202.txt
  fastlane/metadata/android/ru-RU/changelogs/204.txt
  fastlane/metadata/android/sv-SE/changelogs/202.txt
  fastlane/metadata/android/sv-SE/changelogs/204.txt
  fastlane/metadata/android/tr-TR/changelogs/202.txt
  fastlane/metadata/android/tr-TR/changelogs/204.txt
  fastlane/metadata/android/zh-CN/changelogs/202.txt
  fastlane/metadata/android/zh-CN/changelogs/204.txt
  fastlane/metadata/android/zh-TW/changelogs/202.txt
  fastlane/metadata/android/zh-TW/changelogs/204.txt
Labels: Releases

#3723 Merge release/6.3 into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#3729 [Tooling] Mute fastlane's CHANGELOG and update check
  .circleci/config.yml
Labels: Tooling

#3732 Issue/3730 remove empty attributes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: Variation list

#3728 Drop FindBugs Java static analysis
  WooCommerce/build.gradle
Labels: Tech Debt, dependencies

#3741 Merge release/6.3 -> develop (Release Notes)
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#3720 Variable refund notice
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ListExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
Labels: type: task

#3740 issue/3739-status-bar-color
  WooCommerce/src/main/res/values-v23/themes.xml
  WooCommerce/src/main/res/values-v27/themes.xml
  WooCommerce/src/main/res/values/themes.xml
Labels: Style, Tech Debt

#3747 Update `Dependabot` configuration file
  .github/dependabot.yml
Labels: dependencies

#3749 Issue/fix statusbar color lollipop
  WooCommerce/src/main/res/values-v23/themes.xml
  WooCommerce/src/main/res/values/themes.xml
Labels: Style

#3748 issue/3745-material-1.3.0
  WooCommerce/build.gradle
Labels: dependencies

#3738 Init CardReader module
  WooCommerce/build.gradle
  build.gradle
  libs/cardreader/.gitignore
  libs/cardreader/build.gradle
  libs/cardreader/proguard-rules.pro
  libs/cardreader/src/main/AndroidManifest.xml
  settings.gradle
Labels: Card Present Payments

#3750 Drop `Optional` and `OptionalViewState` classes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/Optional.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: Variation Details, dependencies

#3756 Updating the Made By section
  README.md
Labels: Documentation

#3757 Introduce "Manage card reader" section in settings (in debug builds)
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/CardReaderSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_settings_card_reader.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Card Present Payments, Tracks Events

#3754 Stripe Terminal initialization
  libs/cardreader/build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderStore.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/TokenProvider.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/temporary/ApiEndpoints.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/temporary/CardReaderStoreImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/temporary/ConnectionToken.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/LogWrapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
Labels: Card Present Payments

#3758 Issue/3209 remove attribute
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/res/menu/menu_attribute_terms.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Variation Details

#3655 Edit variation attributes
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ListExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/AttributeOptionSelectorDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/VariationAttributeSelectionGroup.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/VariationAttributesAdapter.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_customize.xml
  WooCommerce/src/main/res/layout/attribute_term_selection_list_item.xml
  WooCommerce/src/main/res/layout/fragment_edit_variation_attributes.xml
  WooCommerce/src/main/res/layout/skeleton_variation_attributes_list.xml
  WooCommerce/src/main/res/layout/skeleton_variation_attributes_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationTestUtils.kt
  build.gradle
Labels: Product Details, Variation Details
