Repository woocommerce/woocommerce-android, pull requests merged in 2021-07, with the labels that each got.

#4327 issue/4324-payments-misleading-no-reader-found
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#4298 Merge 7.0 code freeze into develop
  Gemfile.lock
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#4242 issue/4239-payments-clipped-send-receipt
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
Labels: feature: mobile payments

#4319 Issue 3724. LogWrapper uses WooLog
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/LogWrapper.kt
Labels: feature: mobile payments

#4326 Store payment receipts into persistent storage
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PrintHtmlHelper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#4335 Issue/3726 Fixed horizontal margins for payment collection flow
  WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
Labels: feature: mobile payments, type: bug

#4340 Update fluxc - fix crash in payments/account endpoint
  build.gradle
Labels: feature: mobile payments

#4325 nick/reader-found-animation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooAnimUtils.kt
Labels: feature: mobile payments, type: enhancement

#4345 Issue/4311 Card Reader auto re-connection feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: mobile payments

#4346 Issue/4310 CRD operations on shared preferences for the reader id
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PreferenceUtils.kt
Labels: feature: mobile payments

#4348 issue/4347-update-reader-android5
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
Labels: feature: mobile payments

#4350 Merge 7.0 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#4329 Introduce preview receipt UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/res/layout/fragment_receipt_preview.xml
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/menu/menu_receipt_preview.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModelTest.kt
Labels: feature: mobile payments

#4266 Show Progress when loading printing UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#4353 Some Detekt configuration changes
  README.md
  config/detekt/detekt.yml
Labels: category: tooling

#4323 Shipping Labels: add ability to move items to new packages
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabelPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/res/layout/dialog_move_shipping_item.xml
  WooCommerce/src/main/res/layout/shipping_label_package_details_list_item.xml
  WooCommerce/src/main/res/layout/shipping_label_package_product_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachineTest.kt
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4286 Set `platform-9` team as the code owner for config
  .github/CODEOWNERS
Labels: category: tooling

#4352 Use padding instead of margin for the clickable "learn more" section
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_disconnected_state.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_learn_more.xml
Labels: feature: mobile payments

#4365 Issue/4357 Save web view state on configuration change
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
Labels: feature: mobile payments

#4354 Shipping Labels: Add create custom package form when there are existing active packages
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageViewPagerAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorViewModel.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_custom_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_service_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_packages_selector.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4366 Shipping Labels: multiple packages support part 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabelPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModelTest.kt
Labels: feature: shipping labels, type: enhancement

#4370 Migrate LoginActivity and Woo specific login fragments to Hilt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ViewModelAssistedFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginDiscoveryErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEmailHelpDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoWPcomAccountFoundFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginSiteCheckErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WooLoginFragmentModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ParameterRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/DaggerScopedViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/SavedStateWithArgs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/ViewModelFactory.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: category: architecture, type: task

#4349 Introduce Attributes Created view when creating first Variation
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributesAddedFragment.kt
  WooCommerce/src/main/res/drawable/img_welcome_light.xml
  WooCommerce/src/main/res/layout/fragment_attributes_added.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
Labels: feature: product details, type: task

#4379 Fix incorrect notice when saving product as draft
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details, type: bug, type: task

#4369 Product Attributes and Variation design feedback improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeBaseAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeListAdapter.kt
  WooCommerce/src/main/res/layout/add_attribute_list_item.xml
  WooCommerce/src/main/res/layout/attribute_item.xml
  WooCommerce/src/main/res/layout/fragment_add_attribute.xml
  WooCommerce/src/main/res/layout/fragment_add_attribute_terms.xml
  WooCommerce/src/main/res/layout/fragment_attribute_list.xml
  WooCommerce/src/main/res/layout/fragment_variation_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: category: design, feature: product details, type: enhancement

#4377 Issue/4328 Always hide update available button if update was succesful
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments

#4368 issue/viewpager_indicator
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueViewPager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueViewPagerIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCViewPagerIndicator.kt
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-sw600dp/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
Labels: feature: login, feature: mobile payments

#4381 Shipping Labels: add support for shipping items in original packaging
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/res/layout/shipping_label_package_details_list_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModelTest.kt
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4378 issue/4375 Error texts for the payment flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardPaymentStatus.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: feature: mobile payments

#4264 Handle back when sw update in progress
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
Labels: category: design, feature: mobile payments

#4385 Issue/4309 Turning of bluetooth breaks the connection flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4386 Shipping labels: show a discard changes dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
Labels: feature: shipping labels, type: enhancement

#4388 Issue/4356 printing on configuration change 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#4393 Hide collect button on orders with refund
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
Labels: feature: mobile payments

#4392 issue/4390-payment-gray-heading-lollipop
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
Labels: feature: mobile payments

#4399 Store readers id when a reader connected
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4400 Clear last know reader on disconnect clicked
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments

#4395 Merge 7.0 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/227.txt
  fastlane/metadata/android/ar/changelogs/229.txt
  fastlane/metadata/android/de-DE/changelogs/227.txt
  fastlane/metadata/android/de-DE/changelogs/229.txt
  fastlane/metadata/android/es-ES/changelogs/227.txt
  fastlane/metadata/android/es-ES/changelogs/229.txt
  fastlane/metadata/android/fr-FR/changelogs/227.txt
  fastlane/metadata/android/fr-FR/changelogs/229.txt
  fastlane/metadata/android/id/changelogs/227.txt
  fastlane/metadata/android/id/changelogs/229.txt
  fastlane/metadata/android/it-IT/changelogs/227.txt
  fastlane/metadata/android/it-IT/changelogs/229.txt
  fastlane/metadata/android/iw-IL/changelogs/227.txt
  fastlane/metadata/android/iw-IL/changelogs/229.txt
  fastlane/metadata/android/ja-JP/changelogs/227.txt
  fastlane/metadata/android/ja-JP/changelogs/229.txt
  fastlane/metadata/android/ko-KR/changelogs/227.txt
  fastlane/metadata/android/ko-KR/changelogs/229.txt
  fastlane/metadata/android/nl-NL/changelogs/227.txt
  fastlane/metadata/android/nl-NL/changelogs/229.txt
  fastlane/metadata/android/pt-BR/changelogs/227.txt
  fastlane/metadata/android/pt-BR/changelogs/229.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/227.txt
  fastlane/metadata/android/ru-RU/changelogs/229.txt
  fastlane/metadata/android/sv-SE/changelogs/227.txt
  fastlane/metadata/android/sv-SE/changelogs/229.txt
  fastlane/metadata/android/tr-TR/changelogs/227.txt
  fastlane/metadata/android/tr-TR/changelogs/229.txt
  fastlane/metadata/android/zh-CN/changelogs/227.txt
  fastlane/metadata/android/zh-CN/changelogs/229.txt
  fastlane/metadata/android/zh-TW/changelogs/227.txt
  fastlane/metadata/android/zh-TW/changelogs/229.txt
Labels: Releases

#4402 Issue/4030 cancel payment intent
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentUtils.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CancelPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
Labels: feature: mobile payments

#4403 Suppress `LargeClass` Detekt rule for tests
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  config/detekt/detekt.yml
Labels: category: unit tests, type: enhancement

#4401 Improve input validation for shipping labels address form
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Address.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressValidator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_address.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModelTest.kt
Labels: feature: shipping labels, type: enhancement

#4412 Connect to a reader automatically if it's known
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4414 Auto reconnection event tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#4417 Issue/4413 feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#4415 Issue/4413 initial structure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
Labels: feature: mobile payments

#4176 Check translation progress during final release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: category: tooling

#4397 Shipping Labels: Add create custom package form when there are no existing active packages
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreationFeatures.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
Labels: feature: shipping labels

#4411 [Product Image Uploads] Step 2 - display the count of upload errors in the SnackBar
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
Labels: feature: product details, type: enhancement, type: task

#4419 Use `Long` for `Product`'s `total_sales`
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  build.gradle
Labels: feature: product list, type: bug

#4418 Shipping labels: add support of multiple packages in the customs step
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/res/layout/shipping_customs_line_list_item.xml
  WooCommerce/src/main/res/layout/shipping_customs_list_item.xml
  WooCommerce/src/main/res/layout/shipping_label_package_details_list_item.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4372 Issue/4341 payment tutorial
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueViewPager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt
  WooCommerce/src/main/res/drawable-night/img_card_reader_available.xml
  WooCommerce/src/main/res/drawable-night/img_wc_ship_card_charge.xml
  WooCommerce/src/main/res/drawable-night/img_wc_ship_card_insert.xml
  WooCommerce/src/main/res/drawable-night/img_wc_ship_card_sleep.xml
  WooCommerce/src/main/res/drawable-night/img_wc_ship_payment.xml
  WooCommerce/src/main/res/drawable/img_card_reader_available.xml
  WooCommerce/src/main/res/drawable/img_wc_ship_card_charge.xml
  WooCommerce/src/main/res/drawable/img_wc_ship_card_insert.xml
  WooCommerce/src/main/res/drawable/img_wc_ship_card_sleep.xml
  WooCommerce/src/main/res/drawable/img_wc_ship_payment.xml
  WooCommerce/src/main/res/layout/dialog_card_reader_tutorial.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_tutorial_viewpager_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#4445 Removed `CARD_READER_RECONNECTION` feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: feature: mobile payments

#4404 Merge 7.1 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#4432 [Product Image Uploads] Step 3 - Display image upload details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/res/layout/fragment_media_upload_error_list.xml
  WooCommerce/src/main/res/layout/media_upload_error_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details, type: task

#4450 nick/viewPager2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueViewPager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCViewPagerIndicator.kt
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-sw600dp/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/dialog_card_reader_tutorial.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_product_image_viewer.xml
Labels: feature: login, feature: mobile payments, feature: product details, type: technical debt

#4447 Shipping Labels: update order summary to support multiple packages
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/res/layout/view_shipping_label_order_package_price.xml
  WooCommerce/src/main/res/layout/view_shipping_label_order_summary.xml
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4452 Issue/4413 Check if card present payments supported in store's country
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4451 Merge 7.1 rc 2 into develop
  Gemfile.lock
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Releases

#4455 Merge 7.1 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#4446 Show correct item's total price when using order addons
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt
Labels: feature: order details, type: bug

#4453 Issue/4413 Stripe Account verifications
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4459 Update fluxc
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  build.gradle
Labels: feature: shipping labels

#4460 Add wcpay plugin checks
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4394 Order status optimistic update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderStatusSelectorDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/fulfill/OrderFulfillViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFullfillViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  build.gradle
  config/checkstyle.xml
Labels: category: performance, feature: order details, feature: order list, type: enhancement

#4462 Make the the “Update”/”Done”/Publish buttons Pink 50
  WooCommerce/src/main/res/layout/view_toolbar.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: enhancement

#4463 Fixed detekt command in README.md
  README.md
Labels: type: documentation

#4467 Issue/4030 init payment meta data
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/PaymentInfo.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/MetaDataKeys.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentUtils.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/PaymentIntentParametersFactory.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: mobile payments, type: enhancement

#4433 Shipping Labels: Add "activate service packages" form.
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingPackage.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelServicePackageAdapter.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_custom_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_service_package.xml
  WooCommerce/src/main/res/layout/shipping_package_selectable_list_item.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_service_package.xml
  WooCommerce/src/main/res/layout/skeleton_shipping_label_service_package_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels

#4472 Add view states to onboarding view model
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4470 Issue/4437 Add serial number to the metadata of the payment intent
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/PaymentInfo.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/MetaDataKeys.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: mobile payments

#4476 issue/4465-crash-tutorial-payments-take2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
Labels: feature: mobile payments

#4436 Define Product Add-ons feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: order details, type: task

#4479 Fix dark mode background of card reader tutorial
  WooCommerce/src/main/res/layout/dialog_card_reader_tutorial.xml
Labels: feature: mobile payments

#4434 issue/4413-payment-onboarding-basic-loading-ui
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/drawable/img_payment_onboarding_loading.xml
  WooCommerce/src/main/res/drawable/img_woo_payments.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_loading.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments

#4471 Add Activate Service Package Empty View
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_service_package.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels

#4482 issue/4478-payment-tutorial-tablets
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_tutorial_viewpager_item.xml
Labels: feature: mobile payments

#4483 Merge 7.1 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/229.txt
  fastlane/metadata/android/de-DE/changelogs/229.txt
  fastlane/metadata/android/de-DE/changelogs/232.txt
  fastlane/metadata/android/es-ES/changelogs/229.txt
  fastlane/metadata/android/es-ES/changelogs/232.txt
  fastlane/metadata/android/fr-FR/changelogs/229.txt
  fastlane/metadata/android/fr-FR/changelogs/232.txt
  fastlane/metadata/android/id/changelogs/229.txt
  fastlane/metadata/android/id/changelogs/232.txt
  fastlane/metadata/android/it-IT/changelogs/229.txt
  fastlane/metadata/android/it-IT/changelogs/232.txt
  fastlane/metadata/android/iw-IL/changelogs/229.txt
  fastlane/metadata/android/iw-IL/changelogs/232.txt
  fastlane/metadata/android/ja-JP/changelogs/229.txt
  fastlane/metadata/android/ja-JP/changelogs/232.txt
  fastlane/metadata/android/ko-KR/changelogs/229.txt
  fastlane/metadata/android/ko-KR/changelogs/232.txt
  fastlane/metadata/android/nl-NL/changelogs/229.txt
  fastlane/metadata/android/nl-NL/changelogs/232.txt
  fastlane/metadata/android/pt-BR/changelogs/229.txt
  fastlane/metadata/android/pt-BR/changelogs/232.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/229.txt
  fastlane/metadata/android/ru-RU/changelogs/232.txt
  fastlane/metadata/android/sv-SE/changelogs/229.txt
  fastlane/metadata/android/sv-SE/changelogs/232.txt
  fastlane/metadata/android/tr-TR/changelogs/229.txt
  fastlane/metadata/android/tr-TR/changelogs/232.txt
  fastlane/metadata/android/zh-CN/changelogs/229.txt
  fastlane/metadata/android/zh-CN/changelogs/232.txt
  fastlane/metadata/android/zh-TW/changelogs/229.txt
  fastlane/metadata/android/zh-TW/changelogs/232.txt
Labels: Releases

#4475 change product title bottom divider to full width
  WooCommerce/src/main/res/layout/product_property_editable_view_layout.xml
Labels: type: enhancement

#4481 Add CardReaderEligibilityFragment and view model
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/onboarding/CardReaderEligibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/onboarding/CardReaderEligibilityViewModel.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_eligibility.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments, status: feature-flagged, type: task

#4485 Add missing tests
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentUtilsTest.kt
Labels: feature: mobile payments

#4486 Card Reader Payments Onboarding: Unsupported country
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/layout/card_reader_learn_more_section.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_connected_state.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_disconnected_state.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_loading.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_unsupported_country.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: category: design, feature: mobile payments

#4490 Merge 7.2 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#4492 Change chevron color to "on surface/disabled".
  WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
Labels: category: design, feature: shipping labels, type: enhancement

#4488 Issue/4413 unsupported country
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments

#4494 Allow zero value for custom package creation's weight.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModel.kt
Labels: feature: shipping labels

#4497 issue/4496-missing-settings-on-tablet
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
Labels: category: tablet, feature: app settings

#4477 Define Product Details add-ons button
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductAddon.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/main/res/drawable/ic_gridicon_circle_plus.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: product details, type: task

#4435 Redirect to the previous screen when back button is clicked, even when images are uploading
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: feature: product details, type: task

#4504 Clear card present payments eligibility on site switch
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
Labels: feature: mobile payments

#4495 Prevent shipping carrier checkboxes cut-off on larger fonts.
  WooCommerce/src/main/res/layout/shipping_rate_list_item.xml
Labels: feature: shipping labels

#4503 change background colour on image selection screen
  WooCommerce/src/main/res/layout/fragment_product_images.xml
Labels: type: enhancement

#4499 issue/4413-wcpay-screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/drawable-night/img_woo_payments.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_wcpay.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments, status: feature-flagged

#4498 Issue/4421 Contacting support team regarding payments
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/ZendeskHelper.kt
  WooCommerce/src/main/res/layout/activity_help.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#4507 Issue/4351 save for latter button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/res/layout/dialog_card_reader_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#4493 Shipping Labels: Only show Add Payment Button if current user is store owner
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModelTest.kt
Labels: feature: shipping labels

#4487 Shipping Labels: print multiple packages
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/res/layout/fragment_print_shipping_label.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModelTest.kt
  build.gradle
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4515 Added logic to create WCOrderModel from Order object
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
Labels: feature: order details, type: crash

#4500 Shipping Labels: print multiple commercial invoices
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModel.kt
  WooCommerce/src/main/res/layout/fragment_print_label_customs_form.xml
  WooCommerce/src/main/res/layout/print_customs_form_list_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormViewModelTest.kt
Labels: feature: shipping labels, status: feature-flagged, type: enhancement

#4524 Merge 7.2 rc 2 into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
Labels: Releases

#4505 Feature/image upload errors
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
  WooCommerce/src/main/res/layout/fragment_media_upload_error_list.xml
  WooCommerce/src/main/res/layout/media_upload_error_item.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: feature: product details, type: enhancement

#4509 Shipping Labels M4: tracking events
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorViewModel.kt
Labels: category: analytics, feature: shipping labels

#4527 Issue/4398 Fixed configuration change cause not receiving an event from the payments dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
Labels: feature: mobile payments, status: feature-flagged

#4523 Shipping Labels: fix tracking option text
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels, type: bug

#4520 issue/4518-stripe-onboarding-landscape
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_stripe.xml
Labels: feature: mobile payments, status: feature-flagged

#4529 Shipping Labels: enable remaining M4 features
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreationFeatures.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: shipping labels

#4533 Merge 7.2 release notes into develop
  Gemfile.lock
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases
