Repository woocommerce/woocommerce-android, pull requests merged in 2021-11, with the labels that each got.

#5120 Merge 7.8 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/254.txt
  fastlane/metadata/android/ar/changelogs/257.txt
  fastlane/metadata/android/de-DE/changelogs/254.txt
  fastlane/metadata/android/de-DE/changelogs/257.txt
  fastlane/metadata/android/es-ES/changelogs/254.txt
  fastlane/metadata/android/es-ES/changelogs/257.txt
  fastlane/metadata/android/fr-FR/changelogs/254.txt
  fastlane/metadata/android/fr-FR/changelogs/257.txt
  fastlane/metadata/android/id/changelogs/254.txt
  fastlane/metadata/android/id/changelogs/257.txt
  fastlane/metadata/android/it-IT/changelogs/254.txt
  fastlane/metadata/android/it-IT/changelogs/257.txt
  fastlane/metadata/android/iw-IL/changelogs/254.txt
  fastlane/metadata/android/iw-IL/changelogs/257.txt
  fastlane/metadata/android/ja-JP/changelogs/254.txt
  fastlane/metadata/android/ja-JP/changelogs/257.txt
  fastlane/metadata/android/ko-KR/changelogs/254.txt
  fastlane/metadata/android/ko-KR/changelogs/257.txt
  fastlane/metadata/android/nl-NL/changelogs/254.txt
  fastlane/metadata/android/nl-NL/changelogs/257.txt
  fastlane/metadata/android/pt-BR/changelogs/254.txt
  fastlane/metadata/android/pt-BR/changelogs/257.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/254.txt
  fastlane/metadata/android/ru-RU/changelogs/257.txt
  fastlane/metadata/android/sv-SE/changelogs/254.txt
  fastlane/metadata/android/sv-SE/changelogs/257.txt
  fastlane/metadata/android/tr-TR/changelogs/254.txt
  fastlane/metadata/android/tr-TR/changelogs/257.txt
  fastlane/metadata/android/zh-CN/changelogs/254.txt
  fastlane/metadata/android/zh-CN/changelogs/257.txt
  fastlane/metadata/android/zh-TW/changelogs/254.txt
  fastlane/metadata/android/zh-TW/changelogs/257.txt
Labels: Releases

#5099 Update login library to check only `isJetpackConnected` when checking jetpack's status
  build.gradle
Labels: feature: login, feature: jetpack cp

#5087 Refresh order list with order status selected filters
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterOptionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFiltersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/adapter/OrderFilterOptionAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/model/OrderFilterUiMappers.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/model/OrderFilterUiModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterListViewModelTest.kt
Labels: type: task, status: do not merge, feature: order list, status: feature-flagged

#5129 Merge 7.9 code freeze into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/Pluginfile
  fastlane/resources/values/strings.xml
Labels: Releases

#5132 Issue/4873 3.2.0 min wcpay version
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
Labels: feature: mobile payments

#5135 Set min wcpay suported version to 3.2.1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
Labels: feature: mobile payments

#5127 Cover empty billing email on WooCommerce <= 5.8.1 case
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingViewModelTest.kt
  build.gradle
Labels: type: task, feature: order details

#5128 Issue/5111 quick order banners
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/FeatureWIPNoticeCard.kt
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: order list

#5146 Merge 7.9 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#5152 Add unit tests for stripe m2 card reader manual icon display logic
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#5142 issue/5139-quick-order-wip-arrow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: bug, feature: order list, status: feature-flagged

#5159 Issue/5153 Accessibility connected state improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_detail_connected_state.xml
Labels: category: accessibility, feature: mobile payments

#5162 Set toggle viewModel state to false when leaving the Address editing …
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
Labels: type: bug, feature: order details

#5158 Add docs for usage of card reader flows in wcandroid
  docs/card-reader-module.md
Labels: feature: mobile payments

#5165 Define new style to TextButtons that aligns text to the start
  .github/dependabot.yml
  WooCommerce/src/main/res/layout/order_detail_customer_info.xml
  WooCommerce/src/main/res/layout/order_detail_note_list.xml
  WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
  WooCommerce/src/main/res/layout/wc_actionable_empty_label.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: bug, category: design

#5168 Issue/5163 Use of the non deprecated compiler arg
  libs/cardreader/build.gradle
Labels: type: technical debt

#5157 Issue/4553 Resolve todos
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/TerminalListenerImpl.kt
Labels: type: technical debt, feature: mobile payments

#5160 Added mocks necessary to open individual product screens with no warnings from WireMock.
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/products/products_2123.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/products/products_2129.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/taxes/taxes_classes.json
  WooCommerce/src/androidTest/assets/mocks/mappings/sites/rest_sites_161477129.json
  WooCommerce/src/androidTest/assets/mocks/mappings/sites/sites_posts_password.json
Labels: category: ui tests, category: WireMock

#5138 Jetpack CP: fetch site's metadata from the remote site directly
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
  build.gradle
Labels: type: enhancement, feature: jetpack cp

#5167 This PR adds talkback announcement for different payment states
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialogFragment.kt
Labels: feature: mobile payments

#5144 Issue/5143 quick order menu item
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/res/menu/menu_order_list_fragment.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: order list, status: feature-flagged

#5176 Moves mocks-reading functions to a separate class
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/JSONArray+iterator.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/MocksReader.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ReviewsUITest.kt
Labels: category: ui tests

#5105 Jetpack CP: force fetching sites on site picker to run additional checks
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerPresenter.kt
  WooCommerce/src/main/res/layout/activity_site_picker.xml
Labels: type: enhancement, status: feature-flagged, feature: jetpack cp

#5182 AddTalkBack support for connection flow during IPP
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModelTest.kt
Labels: category: accessibility, feature: mobile payments

#5187 Issue/5148 Missing unit tests for start async update method
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManagerTest.kt
Labels: type: technical debt, feature: mobile payments

#5145 Add test coverage to OrderEditingViewModel
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingViewModelTest.kt
Labels: feature: order details, category: unit tests

#5184 Image upload: improve Flow usage in MediaFilesRepository
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: feature: product details, category: architecture

#5190 Add talk back support for software update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
Labels: category: accessibility, feature: mobile payments

#5191 Track product image upload failures
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
Labels: type: bug, feature: product details

#5194 Bump compileSdkVersion to 31
  WooCommerce/build.gradle
  libs/cardreader/build.gradle
Labels: type: task

#5177 Update order reader url
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#5104 Filters orders by date
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoryListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFiltersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/adapter/OrderFilterCategoryAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/adapter/OrderFilterOptionAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersUseCases.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/model/OrderFilterUiMappers.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/model/OrderFilterUiModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/model/OrderFilterUiMappers.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_filters.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterListViewModelTest.kt
Labels: type: enhancement, feature: order list

#5180 Issue/5112 quick order view
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderViewModel.kt
  WooCommerce/src/main/res/layout/dialog_quick_order.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: order list, status: feature-flagged

#5202 Fix broken card reader manager initialisation flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
Labels: feature: mobile payments

#5216 Issue/5204 Inject card reader manager
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/CardReaderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManagerFactory.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
Labels: type: technical debt, feature: mobile payments

#5181 Refactor OrderShipmentProvidersRepository to use fetch order shipment providers suspended functions
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/OrderShipmentProvidersRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/OrderShipmentProvidersRepositoryTest.kt
  build.gradle
Labels: feature: order details

#5211 Issue/5113 create quick order
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderViewModel.kt
  WooCommerce/src/main/res/layout/dialog_quick_order.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: order details, status: feature-flagged

#5222 Preserve the variation model in SavedStateHandle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
Labels: type: bug, feature: variation details

#5170 Jetpack CP: UI for Install Jetpack from App
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackBenefitsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallProgressDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallStartDialog.kt
  WooCommerce/src/main/res/drawable-night/ic_connecting.xml
  WooCommerce/src/main/res/drawable-night/ic_progress_circle_complete.xml
  WooCommerce/src/main/res/drawable-night/ic_progress_circle_loading.xml
  WooCommerce/src/main/res/drawable-night/ic_progress_circle_start.xml
  WooCommerce/src/main/res/drawable/ic_connecting.xml
  WooCommerce/src/main/res/drawable/ic_progress_circle_complete.xml
  WooCommerce/src/main/res/drawable/ic_progress_circle_loading.xml
  WooCommerce/src/main/res/drawable/ic_progress_circle_start.xml
  WooCommerce/src/main/res/drawable/ic_woo_bubble.xml
  WooCommerce/src/main/res/layout/dialog_jetpack_install_progress.xml
  WooCommerce/src/main/res/layout/dialog_jetpack_install_start.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: category: design, status: feature-flagged, feature: jetpack cp

#5169 Save order filters into shared preferences
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersUseCases.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
Labels: type: enhancement, feature: order list

#5207 Convert fetchProductReviews into suspendable function
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListRepository.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: status: do not merge

#5215 Refactor StatsRepository into stateless repository. Mark I: fetchHasOrders
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/StatsRepository.kt
  build.gradle
Labels: status: do not merge

#5231 Products List: improve handling of the FAB
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/main/res/layout/fragment_product_list.xml
Labels: type: bug, type: enhancement, feature: product list

#5234 Remove PR list generation at code freeze
  fastlane/Fastfile
Labels: category: tooling

#5197 Split order filter use cases into independent file
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersUseCases.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetDateRangeFilterOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetOrderStatusFilterOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetSelectedOrderFiltersCount.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetWCOrderListDescriptorWithFilters.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
Labels: feature: order list, category: architecture

#5195 Update mediapicker dependency to be fetched from S3 and enable composite build for it
  WooCommerce/build.gradle
  build.gradle
  local-builds.gradle-example
  settings.gradle
Labels: category: tooling

#5246 Merge 7.9 final into develop
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/257.txt
  fastlane/metadata/android/ar/changelogs/260.txt
  fastlane/metadata/android/de-DE/changelogs/257.txt
  fastlane/metadata/android/de-DE/changelogs/260.txt
  fastlane/metadata/android/es-ES/changelogs/257.txt
  fastlane/metadata/android/es-ES/changelogs/260.txt
  fastlane/metadata/android/fr-FR/changelogs/257.txt
  fastlane/metadata/android/fr-FR/changelogs/260.txt
  fastlane/metadata/android/id/changelogs/257.txt
  fastlane/metadata/android/id/changelogs/260.txt
  fastlane/metadata/android/it-IT/changelogs/257.txt
  fastlane/metadata/android/it-IT/changelogs/260.txt
  fastlane/metadata/android/iw-IL/changelogs/257.txt
  fastlane/metadata/android/iw-IL/changelogs/260.txt
  fastlane/metadata/android/ja-JP/changelogs/257.txt
  fastlane/metadata/android/ja-JP/changelogs/260.txt
  fastlane/metadata/android/ko-KR/changelogs/257.txt
  fastlane/metadata/android/ko-KR/changelogs/260.txt
  fastlane/metadata/android/nl-NL/changelogs/257.txt
  fastlane/metadata/android/nl-NL/changelogs/260.txt
  fastlane/metadata/android/pt-BR/changelogs/257.txt
  fastlane/metadata/android/pt-BR/changelogs/260.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/257.txt
  fastlane/metadata/android/ru-RU/changelogs/260.txt
  fastlane/metadata/android/sv-SE/changelogs/257.txt
  fastlane/metadata/android/sv-SE/changelogs/260.txt
  fastlane/metadata/android/tr-TR/changelogs/257.txt
  fastlane/metadata/android/tr-TR/changelogs/260.txt
  fastlane/metadata/android/zh-CN/changelogs/257.txt
  fastlane/metadata/android/zh-CN/changelogs/260.txt
  fastlane/metadata/android/zh-TW/changelogs/257.txt
  fastlane/metadata/android/zh-TW/changelogs/260.txt
Labels: Releases

#5033 Media picker library integration
  WooCommerce/build.gradle
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerLogger.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/WooMediaLoaderFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/WooMimeTypeProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt
  WooCommerce/src/main/res/values/media_picker_drawables.xml
  build.gradle
  local-builds.gradle-example
  settings.gradle
Labels: feature: product details, feature: variation details

#5224 Issue/5141 order shipment providers
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/OrderShipmentProvidersRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/OrderShipmentProvidersRepositoryTest.kt
  build.gradle
Labels: type: enhancement, feature: order details

#5232 Tracks for What's New
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
Labels: category: analytics

#5244 issue/5218-move-collect-payment-button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
Labels: feature: mobile payments

#5199 Update to navigation 2.4
  WooCommerce/src/main/kotlin/com/woocommerce/android/navigation/KeepStateNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/SavedStateHandleExt.kt
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
  build.gradle
Labels: type: task, category: architecture

#5217 Navigation 2.4: drop Robolectric from tests
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/NotificationsParser.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/NotificationsUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ArgsExt.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationMessageHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationRegistrationHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcherTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderFullfillViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRefundViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/MoveShippingItemViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressSuggestionViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateServicePackageViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/OrderShipmentProvidersRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderWelcomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GroupedProductListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductInventoryViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductSelectionListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductShippingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadDetailsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/reviews/ReviewListViewModelTest.kt
  build.gradle
  config/detekt/baseline.xml
Labels: category: unit tests

#5253 Remove unused method from MainBottomNavigationView
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
Labels: type: task

#5254 Issue/5245 quick order onboarding check
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: feature: app settings, feature: order list, status: feature-flagged

#5262 Bump Stripe terminal Android SDK to v2.5.1
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#5242 issue/5115-quick-order-tracks
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/quickorder/QuickOrderViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
Labels: feature: order list, category: analytics

#5220 Track selected filters when show orders button is clicked
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetTrackingForFilterSelection.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
Labels: feature: order list, category: analytics

#5243 Improve Splash screen on Android 12
  WooCommerce/src/jalapeno/res/drawable-v23/img_woo_bubble_white.xml
  WooCommerce/src/main/res/drawable-v31/img_woo_bubble_white.xml
  WooCommerce/src/main/res/values/themes.xml
  WooCommerce/src/wasabi/res/drawable-v23/img_woo_bubble_white.xml
  WooCommerce/src/wasabi/res/drawable-v31/img_woo_bubble_white.xml
Labels: type: enhancement, category: design

#5259 Issue/5193 fetch single product review
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt
  build.gradle
Labels: feature: review details

#5269 Change the target SDK version to 30
  WooCommerce/build.gradle
  build.gradle
Labels: type: bug

#5284 Implement search filter for country and state when editing an order
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterItem.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterViewState.kt
  WooCommerce/src/main/res/layout/fragment_base_edit_address.xml
  WooCommerce/src/main/res/layout/fragment_search_filter.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/searchfilter/SearchFilterViewModelTest.kt
Labels: feature: order details

#5273 Supply the necessary mutability flags for PendingIntents
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationsProcessingService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationBuilder.kt
Labels: type: task

#5271 Set FCMMessageService as non-exported
  WooCommerce/src/main/AndroidManifest.xml
Labels: type: enhancement, type: task

#5248 Merge 8.0 code freeze into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#5295 Merge 8.0 release notes into develop
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#5294 Add headsup comment to targetSdkVersion
  WooCommerce/build.gradle
Labels: type: documentation

#5264 Add payment canceled event for the payment flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#5293 Update location permission wording
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#5296 Android 12 PendingIntent changes (rectification)
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/WooCommerceGlideModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/TextViewExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesNotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationsProcessingService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/SystemVersionUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCTextViewCompat.kt
Labels: type: task

#5239 Issue/4934 adapt search to new filters feature
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: type: enhancement, feature: order list

#5303 Media Upload: check filename before displaying upload error list
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
Labels: type: crash, feature: product details

#5287 Jetpack CP: Jetpack install vm and repository.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/PluginRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallViewModelTest.kt
Labels: feature: jetpack cp

#5307 Navigation: fix crash when restoring state that has custom Parcelable arrays
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PackageUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/SavedStateHandleExt.kt
Labels: type: crash

#5302 Android 12: backup configuration
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/res/xml/backup_scheme.xml
  WooCommerce/src/main/res/xml/legacy_backup_scheme.xml
Labels: type: task, category: tooling

#5268 Issue/4991 memory leaks
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/SkeletonView.kt
Labels: type: technical debt

#5260 Order filters: custom date range
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/adapter/OrderFilterOptionAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFilterDataModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetDateRangeFilterOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetWCOrderListDescriptorWithFilters.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/model/OrderFilterUiMappers.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/model/OrderFilterUiModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/order_filter_option_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
Labels: type: enhancement, feature: order list

#5319 Update release notes for order list filters
  RELEASE-NOTES.txt
Labels: feature: order list

#5299 Add a new tab for Analytics section
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/AnalyticsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/BottomNavigationPosition.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/as_menu_analytics.xml
  WooCommerce/src/main/res/drawable/ic_menu_analytics.xml
  WooCommerce/src/main/res/layout/fragment_analytics.xml
  WooCommerce/src/main/res/menu/menu_bottom_bar.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, status: do not merge, category: analytics, status: feature-flagged

#5309 Issue/5192 rename quick order
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/simplepayments/SimplePaymentsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/simplepayments/SimplePaymentsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/dialog_simple_payments.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_beta.xml
  WooCommerce/src/main/res/menu/menu_order_list_fragment.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: order list, status: feature-flagged

#5214 Integrate Tracks Gradle plugin
  build.gradle
  gradle.properties-example
Labels: type: enhancement, category: analytics

#5324 Update secret `gradle.properties` for `tracks-gradle` configuration options
  .configure
  .configure-files/gradle.properties.enc
Labels: type: enhancement, category: analytics

#5310 Define order creation experimental toggle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/BetaFeaturesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/res/layout/fragment_settings_beta.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: order details

#5308 Jetpack CP: handle fetching media for the Wordpress Media library
  build.gradle
Labels: type: enhancement, status: do not merge, feature: jetpack cp

#5326 Update stripe terminal SDK to 2.5.2
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#5300 Issue-5267. Android 12 support for IPP. New bluetooth runtime permission
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/main/AndroidManifest.xml
Labels: type: technical debt, feature: mobile payments

#5323 Refactor StatsRepository into stateless repository. Mark II: fetchVisitorStats
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/StatsRepository.kt
  build.gradle
Labels: status: do not merge

#5235 Add products UI test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/ReviewsListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/MocksReader.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/ReviewData.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ReviewsUITest.kt
Labels: category: ui tests

#5347 Navigation: fix navigation to my store after receiving push notifications
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
Labels: type: bug

#5209 Send `WCTracker` telemetry
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreQualifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tracker/DataStoreTrackerRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tracker/SendTelemetry.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tracker/TrackerRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/tracker/FakeTrackerRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/tracker/SendTelemetryTest.kt
Labels: type: enhancement, category: analytics

#5249 Add prominent/overflow publish option for draft and pending review products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/res/menu/menu_product_detail_fragment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: type: enhancement, feature: product details

#5325 Jetpack CP: Connect UI states with install states
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallProgressDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallViewModel.kt
  WooCommerce/src/main/res/layout/dialog_jetpack_install_progress.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallViewModelTest.kt
Labels: category: design, feature: jetpack cp

#5349 Convert markReviewAsRead into suspendable function
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListViewModel.kt
  build.gradle
Labels: status: do not merge, feature: notifications

#5346 Android 12: migrate to WindowMetrics API
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackBenefitsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallProgressDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallStartDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueViewPagerItemFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/simplepayments/SimplePaymentsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  build.gradle
Labels: type: enhancement

#5357 Hide m2 reader manual row
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#5351 Refactor StatsRepository into stateless repository. Mark III: fetchRevenueStats
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/StatsRepository.kt
  build.gradle
Labels: type: enhancement, feature: stats

#5352 Update OnboardingChecker and add unit test
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: category: unit tests, feature: mobile payments

#5354 Order creation button
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderCreationBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/res/drawable/ic_bolt.xml
  WooCommerce/src/main/res/layout/dialog_order_creation_bottom_sheet.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/menu/menu_order_list_fragment.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: order list

#5353 Issue/5350 stripe extension flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/StripeExtensionFeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments

#5366 issue/5343-simple-payment-device-rotation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: bug, feature: order list, status: feature-flagged

#5374 Merge 8.1 code freeze into develop
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#5361 Issue/5317 extract logic out of presenter
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/data/StatsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetTopPerformers.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/domain/GetStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/domain/GetTopPerformersTest.kt
Labels: type: enhancement, feature: home screen

#5368 More menu tab
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/BottomNavigationPosition.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/res/drawable/as_menu_more.xml
  WooCommerce/src/main/res/drawable/ic_more_menu.xml
  WooCommerce/src/main/res/layout/fragment_more_menu.xml
  WooCommerce/src/main/res/menu/menu_bottom_bar.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: home screen

#5383 Enable build time reporting on CI
  .circleci/config.yml
Labels: type: enhancement, category: analytics
