Repository woocommerce/woocommerce-android, pull requests merged in 2022-07, with the labels that each got.

#6796 Refactor CardReaderOnboardingChecker to allow user to choose between multiple plugins
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments

#6834 [Screenshots Automation] Fix locales switching
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/debug/kotlin/com.woocommerce.android/LeakCanaryInstaller.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/ZendeskHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PackageUtils.kt
  fastlane/Fastfile
Labels: category: ui tests

#6840 [Kotlin Warnings As Errors] Woo Commerce Module - Resolve Coroutines Warnings
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ViewExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaFileUploadHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategoryListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/push/RegisterDeviceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/domain/GetStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilderTest.kt
  config/detekt/baseline.xml
Labels: type: technical debt, Tooling

#6851 Use woo_blue_5 for completed order status
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusTag.kt
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
Labels: feature: order list

#6852 [Screenshot automation] promo screenshots
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/playstoreres/assets/pixel-3-mask.png
  fastlane/playstoreres/assets/pixel-3.png
  fastlane/playstoreres/assets/style.css
  fastlane/screenshots.json
Labels: category: ui tests

#6846 Update Dagger to 2.42
  settings.gradle
Labels: dependency update

#6055 ExPlat integration
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ExperimentationModule.kt
Labels: type: enhancement

#6835 Order editing loading indicator
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
  WooCommerce/src/main/res/layout/fragment_order_creation_form.xml
  WooCommerce/src/main/res/layout/order_creation_payment_section.xml
Labels: feature: order editing

#6859 Compose: Add default text color in WCSearchField to make it readable in light and dark mode.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
Labels: feature: coupons, compose

#6832 Auto-sync order editing
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncOrder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncPriceModifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CreateOrUpdateOrderDraft.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CreateUpdateOrder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/SyncStrategy.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncOrderStrategyTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncPriceModifierStrategyTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreateUpdateOrderTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/SyncStrategyTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: feature: order editing

#6866 [Coupons] Fix race conditions about loading state during search
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
Labels: type: bug, feature: coupons

#6857 [UOE] Inform user about multiple fee and/or shipping lines
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/OrderMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/DetermineMultipleLinesContext.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/res/layout/fragment_order_creation_form.xml
  WooCommerce/src/main/res/layout/multiple_lines_warning.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: type: enhancement, feature: order editing

#6858 Issue/6623 connect select payment plugin screen to vm
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments

#6862 Track selected payment gateway event when merchant selects preferred plugin
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTrackerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#6892 Exclude tracks experiments dependency from dependabot
  .github/dependabot.yml
Labels: type: enhancement, Tooling

#6888 Fix navgraph action
  WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
Labels: type: enhancement, feature: mobile payments

#6883 For the Canadian store, when both WCPay and Stripe extension plugin are installed, proceed with onboarding using WCPay as the preferred plugin
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments

#6876 Update our dependencies to AGP 7.2.1 PRs
  WooCommerce/build.gradle
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/coupons/details/CouponDetailsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/DefaultCurrencyFormatterTest.kt
  build.gradle
Labels: dependency update

#6887 Issue/6886 enable multiple plugins for all
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: mobile payments

#6824 Update Gradle to 7.4.2 & AGP to 7.2.1
  WooCommerce/build.gradle
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/coupons/details/CouponDetailsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/DefaultCurrencyFormatterTest.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: Tooling

#6885 Remove wcpayandstripeinstalled state from the codebase
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/IppSelectPaymentGateway.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments

#6823 [Kotlin Warnings As Errors] Card Reader Module - Resolve Warnings & Enable All Warnings as Errors
  libs/cardreader/build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CancelPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/ProcessPaymentAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderBaseUnitTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/config/CardReaderConfigFactoryTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersActionTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/firmware/SoftwareUpdateManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/AdditionalInfoMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/InteracRefundManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentUtilsTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectInteracRefundActionTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/ProcessInteracRefundActionTest.kt
Labels: type: technical debt, Tooling

#6845 Track event when "Choose payment gateway" screen is shown while onboarding
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTracker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTrackerTest.kt
Labels: feature: mobile payments

#6865 [Kotlin Warnings As Errors] Woo Commerce Module - Resolve Type/Cast/When & Other Warnings
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/WooCommerceGlideModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SequenceExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringDateFormatExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/DatePickerDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/CouponRestrictionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/MagicLinkInterceptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncOrder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/AutoSyncPriceModifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CreateUpdateOrder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/SyncStrategy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderDetailOrderNoteItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderNoteViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderNotesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributesAddedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/PropertyGroupViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ReadMoreViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundFeeListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundShippingListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/Section.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/sectionedrecyclerview/SectionedRecyclerViewAdapter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  config/detekt/baseline.xml
Labels: type: technical debt, Tooling

#6874 [Screenshot Automation] Update screenshots (part 1) + Store listing metada
  WooCommerce/metadata/full_description.txt
  WooCommerce/metadata/promo_screenshot_1.txt
  WooCommerce/metadata/promo_screenshot_1_b.txt
  WooCommerce/metadata/promo_screenshot_2.txt
  WooCommerce/metadata/promo_screenshot_3.txt
  WooCommerce/metadata/promo_screenshot_4.txt
  WooCommerce/metadata/promo_screenshot_5.txt
  WooCommerce/metadata/promo_screenshot_6.txt
  WooCommerce/metadata/promo_screenshot_7.txt
  WooCommerce/metadata/promo_screenshot_8.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/mystore/StatsComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderCreationScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  fastlane/Fastfile
Labels: category: ui tests

#6875 [Screenshot Automation] IPP screenshot
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/2787/2787_details.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/2787/2787_notes.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_all_detailed.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockCardReaderManagerModule.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/TestBase.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/CardReaderPaymentScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/InPersonPaymentsModule.kt
Labels: category: ui tests

#6878 [Screenshot automation] Screenshot for push notifications
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/notifications/NotificationsScreen.kt
  WooCommerce/src/main/res/values/strings.xml
  fastlane/Fastfile
Labels: category: ui tests

#6889 [Screenshot Automation] Update promo screenshot entries
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  fastlane/screenshots.json
Labels: category: ui tests

#6860 Coupons: Make Empty Product Selector Screen be Scrollable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
Labels: feature: coupons, compose

#6897 WCSettingsModel Crash Fix
  build.gradle
Labels: type: crash

#6898 Update release notes
  RELEASE-NOTES.txt
Labels: feature: mobile payments

#6901 Fix promo screenshots translation
  WooCommerce/metadata/PlayStoreStrings.pot
  fastlane/Fastfile
Labels: Releases, Tooling

#6891 Feature/6881 what is wordpress
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/LoginFragmentsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/UnifiedLoginTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginEmailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginSiteAddressFragment.kt
  WooCommerce/src/main/res/layout/fragment_login_email_screen.xml
  WooCommerce/src/main/res/layout/fragment_login_site_address.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: login

#6870 [UOE] Handle multiple shipping lines edit
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreationViewModelTest.kt
Labels: type: enhancement, feature: order editing

#6909 Extract 'com.woocommerce.android' to `APP_PACKAGE_NAME` in `Fastfile`
  fastlane/Fastfile
Labels: category: tooling

#6910 Login Enhancement: Update flow to allow site credentials login first before showing Jetpack missing screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
Labels: type: enhancement, feature: login

#6913 Adds rmagick to Gemfile.lock
  Gemfile.lock
Labels: category: tooling

#6917 Merge 9.6 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#6929 Merge 9.6 release notes to trunk
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#6907 Append APP_ to METADATA_DIR_PATH to make it clear it's for the app
  fastlane/Fastfile
Labels: category: tooling

#6919 Fix `metadata_path` in `create_promo_screenshots` lane
  fastlane/Fastfile
Labels: category: tooling

#6942 [UOE] No price recalculation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreateEditViewModelTest.kt
Labels: type: enhancement, feature: order editing

#6937 Issue/6928 order metadata UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: order details, status: feature-flagged

#6930 [UOE] Update events with a correct flow parameter
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: category: analytics, feature: order editing

#6896 [Screenshot Automation] Fix issue with non-latin languages
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-hour.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_all_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_any.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_completed_pending_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_processing.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_processing_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-month.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
Labels: category: ui tests

#6945 Change color on payment provider icon to support dark mode
  WooCommerce/src/main/res/drawable/ic_payment_provider.xml
Labels: type: bug, feature: mobile payments

#6952 Fix wording on order paid with cash dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
Labels: type: bug, feature: mobile payments

#6954 Issue/6951 order detail always fetch order
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: feature: order details

#6950 Add sync error message in edit flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: order editing

#6941 Hide mark order complete button unpaid orders
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: enhancement, feature: order details

#6944 Fix payment selection landscape mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml
Labels: feature: mobile payments

#6971 Move UI tests to Buildkite
  .buildkite/pipeline.yml
  .circleci/.firebase.secrets.json.enc
  .circleci/config.yml
  .configure
  .configure-files/firebase.secrets.json.enc
  Gemfile.lock
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/OrdersUITest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ReviewsUITest.kt
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: category: tooling, Testing

#6961 Fix stroke select payment gateway buttons
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
Labels: type: bug, feature: mobile payments

#6915 [Kotlin Warnings As Errors] All Modules - Enable All Warnings as Errors
  WooCommerce/build.gradle
  build.gradle
  libs/cardreader/build.gradle
  quicklogin/build.gradle
Labels: category: tooling, type: technical debt

#6973 [UOE] Display day time in order editing
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
Labels: type: enhancement, feature: order editing

#6969 [UOE] Track edit button tap
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: category: analytics, feature: order editing

#6970 [UOE] Update order sync failed event
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CreateUpdateOrder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: category: analytics, feature: order editing

#6967 Issue/6965 metadata actionable urls and email
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsScreen.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  build.gradle
Labels: feature: order details, status: feature-flagged

#6987 [UOE] Release feature
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: order editing

#6976 Update order analytics for metadata
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: type: task, feature: order details

#6994 Merge 9.6-rc2 into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-sw600dp/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: category: releases

#6999 Enable customer search for all
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: order creation, feature: order editing

#7000 Improves BUILDKITE_TOKEN permission explanation in release management prechecks
  scripts/release-management-prechecks.sh
Labels: category: tooling

#6997 6995-order-list-tracking-crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
Labels: feature: order details

#7001 Fix the prologue layouts
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-sw600dp/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
Labels: category: releases

#6990 Feature/login local notifications
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationChannelType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/localnotifications/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/localnotifications/LoginFlowUsageTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: login

#6998 Show edit button in the toolbar
  WooCommerce/src/main/res/menu/menu_order_detail.xml
Labels: feature: order details, feature: order editing

#6984 Track event when CTA is tapped in the banner
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6983 Issue/6924 tracking banner dismiss event
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6982 Issue/6923 tracking for displaying banner
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6981 Issue/6959 upsell card reader banner in settings screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_upsell_banner.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6980 Issue/6957 upsell card reader banner in order list screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_upsell_banner.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6979 Issue/6936 dismiss card reader upsell banner
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_upsell_banner.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6978 Issue/6934 payments alert dialog compose UI
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_upsell_banner.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#6765 Compile SDK version to 33
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/products/OrderCreateEditProductSelectionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCSelectableTextView.kt
  build.gradle
  libs/cardreader/build.gradle
  quicklogin/build.gradle
  settings.gradle
Labels: type: technical debt

#7004 Login Enhancement: Install and Connect Jetpack via Chrome Custom Tab
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackListener.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: login

#7007 Login Enhancement: Handle Successful Jetpack Connection
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
Labels: type: enhancement, feature: login

#7010 Login Enhancement: Analytics for Jetpack Installation via Login Flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
Labels: type: enhancement, category: analytics, feature: login

#7009 Feature/login local notification ii
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/push/WooNotificationBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/localnotifications/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/localnotifications/LoginHelpNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/localnotifications/LoginNotificationScheduler.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: login

#7015 Merge feature branch `feature/install-jetpack-from-login` to trunk.
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackListener.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: login

#6993 Issue/remove metadata feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  build.gradle
Labels: feature: order details

#7014 Activate: Emphasize credentials login for self-hosted sites
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
Labels: feature: login

#6977 Issue/6920 payments banner compose UI
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDismissDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/drawable/ic_banner_upsell_card_reader_illustration.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_upsell_banner.xml
  WooCommerce/src/main/res/layout/fragment_order_list.xml
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: feature: mobile payments

#7028 Site credentials A/B test
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/ExperimentTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/DataStoreRemoteConfigRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/RemoteConfigManager.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/RemoteConfigRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/SiteLoginExperiment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/res/xml/remote_config_values.xml
Labels: feature: login

#7033 Merge 9.7 code freeze into trunk
  Gemfile.lock
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#7029 Fix WorkManager initialization in UI tests
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooCommerceTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/CarouselScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/login/WelcomeScreen.kt
Labels: category: ui tests

#7043 Add 9.7 Release notes into trunk
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#7041 Show red budge on the more button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuNewFeatureAvailableProvider.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: feature: mobile payments

#7042 Show red budge on the more button till More screen is visible at least once
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuNewFeatureAvailableProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuNewFeatureHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuNewFeatureHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: feature: mobile payments

#7040 Change the copy in the upsell card reader banner.
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#7059 Issue/7051 promote linked products
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/promobanner/PromoBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/promobanner/PromoBannerType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details

#7044 Payments icon to more screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MenuUiButton.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: mobile payments

#7045 Show red badge on the new payments icon
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MenuUiButton.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
Labels: feature: mobile payments

#7046 Hide the red dot from payments button
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuNewFeatureHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: feature: mobile payments

#7058 Upsell card reader banner gets preference over feedback banner in the order list screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: feature: mobile payments

#7055 Issue/7012 hide upsell banner on empty orders
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: feature: mobile payments

#6726 Update Hilt to use the Plugin Marker Artifact
  WooCommerce/build.gradle
  build.gradle
  settings.gradle
Labels: type: task, bot: dependencies update

#7070 [Login] Fix button "need more help" in the email help dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
Labels: type: bug, feature: login
