Repository woocommerce/woocommerce-android, pull requests merged in 2022-12, with the labels that each got.

#7948 Add update reader selected option logic
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockCardReaderManagerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImplTest.kt
Labels: type: enhancement, status: do not merge

#7964 Remove update reader row when simulated reader disabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsTest.kt
Labels: type: enhancement

#7941 feat: add product bulk editing icon
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/ic_multiselect.xml
  WooCommerce/src/main/res/menu/menu_product_list_fragment.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product list

#7972 Activate: Native store creation flow improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/ProgressIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/NewStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationErrorType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationResult.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/mystoresummary/MyStoreSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_store_creation.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: store creation

#7976 [Tooling] Report Firebase Test Failures as Buildkite Annotations
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: category: tooling

#7980 Fix event name for tracking the Jetpack installation variant
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/JetpackInstallationExperiment.kt
Labels: type: bug, feature: login

#7975 Activate: Use the plan data to make make a purchase
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/NewStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/BillingPeriod.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt
  build.gradle
Labels: feature: store creation

#7982 Added release notes for 11.5
  CHANGELOG.md
Labels: Releases

#7984 Merge 11.4 final to trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/JetpackInstallationExperiment.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/361.txt
  fastlane/metadata/android/ar/changelogs/363.txt
  fastlane/metadata/android/de-DE/changelogs/361.txt
  fastlane/metadata/android/de-DE/changelogs/363.txt
  fastlane/metadata/android/es-ES/changelogs/361.txt
  fastlane/metadata/android/es-ES/changelogs/363.txt
  fastlane/metadata/android/fr-FR/changelogs/361.txt
  fastlane/metadata/android/fr-FR/changelogs/363.txt
  fastlane/metadata/android/id/changelogs/361.txt
  fastlane/metadata/android/id/changelogs/363.txt
  fastlane/metadata/android/it-IT/changelogs/361.txt
  fastlane/metadata/android/it-IT/changelogs/363.txt
  fastlane/metadata/android/iw-IL/changelogs/363.txt
  fastlane/metadata/android/ja-JP/changelogs/361.txt
  fastlane/metadata/android/ja-JP/changelogs/363.txt
  fastlane/metadata/android/ko-KR/changelogs/361.txt
  fastlane/metadata/android/ko-KR/changelogs/363.txt
  fastlane/metadata/android/nl-NL/changelogs/361.txt
  fastlane/metadata/android/nl-NL/changelogs/363.txt
  fastlane/metadata/android/pt-BR/changelogs/361.txt
  fastlane/metadata/android/pt-BR/changelogs/363.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/361.txt
  fastlane/metadata/android/ru-RU/changelogs/363.txt
  fastlane/metadata/android/sv-SE/changelogs/361.txt
  fastlane/metadata/android/sv-SE/changelogs/363.txt
  fastlane/metadata/android/tr-TR/changelogs/361.txt
  fastlane/metadata/android/tr-TR/changelogs/363.txt
  fastlane/metadata/android/zh-CN/changelogs/361.txt
  fastlane/metadata/android/zh-CN/changelogs/363.txt
  fastlane/metadata/android/zh-TW/changelogs/361.txt
  fastlane/metadata/android/zh-TW/changelogs/363.txt
Labels: Releases

#7985 Merge 11.5 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#7965 Support bulk product price status update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt
  build.gradle
Labels: type: task, status: do not merge, feature: product list

#7990 Fix/list multi-select top fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/MutableMultipleSelectionPredicate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
Labels: type: enhancement, feature: product list

#7992 Two menus are visible when switching between orders and products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
Labels: type: bug

#7994 Track and update unfulfilled orders count only when it's changed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
Labels: type: bug, feature: analytics

#7989 Integrate application passwords changes from FluxC
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/SiteObserver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/applicationpasswords/ApplicationPasswordsNotifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationPasswordsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ApplicationPasswordsTester.kt
  build.gradle
Labels: type: task, feature: login

#7998 Fix clear menu item visibility in the product filters
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListFragment.kt
Labels: type: bug

#7996 Fix event name for Jetpack URL connection failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt
Labels: type: bug, feature: login, feature: analytics

#7977 Reinitialize simulated reader upon update frequency change
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/MockCardReaderManagerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
Labels: type: enhancement

#8002 Hosted on side card reader manuals
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
Labels: feature: mobile payments

#8003 Add the missing store creation entry in the release notes
  RELEASE-NOTES.txt
Labels: category: releases

#8006 Added release notes for 11.6
  CHANGELOG.md
Labels: Releases

#8010 Merge release/11.6-rc-1 into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/layout/analytics_information_card_view.xml
  WooCommerce/src/main/res/layout/analytics_list_card_view.xml
  build.gradle
Labels: Releases

#7995 Call disconnect from a reader when the user clicks cancel during the connection flow
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
Labels: feature: mobile payments

#8018 [Application Passwords] Specify the correct device name when creating application passwords
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationPasswordsModule.kt
Labels: type: task, feature:REST API

#7987 Hide FAB when bottom navigation bar is animating
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt
Labels: type: bug

#8026 Remove glance animation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SwipeToComplete.kt
Labels: type: enhancement, feature: order list

#8028 Draw only over the swiped list item background
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SwipeToComplete.kt
Labels: type: enhancement, feature: order list

#8023 Selection with opacity
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/res/drawable/picture_frame.xml
  WooCommerce/src/main/res/drawable/product_selected_overlay.xml
  WooCommerce/src/main/res/layout/product_item_view.xml
  WooCommerce/src/main/res/menu/menu_product_list_fragment.xml
  WooCommerce/src/main/res/values/dimens_base.xml
Labels: feature: product list

#8031 [Analytics Hub] Improve percentage rounding rule
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/AnalyticsRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsRepositoryTest.kt
Labels: type: bug, feature: stats

#8020 Removing bulk editing feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: product list

#8042 Added release notes for 11.7
  CHANGELOG.md
Labels: Releases

#8044 Merge release/11.6 into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationPasswordsModule.kt
  fastlane/metadata/android/ar/changelogs/365.txt
  fastlane/metadata/android/ar/changelogs/367.txt
  fastlane/metadata/android/de-DE/changelogs/365.txt
  fastlane/metadata/android/de-DE/changelogs/367.txt
  fastlane/metadata/android/es-ES/changelogs/365.txt
  fastlane/metadata/android/es-ES/changelogs/367.txt
  fastlane/metadata/android/fr-FR/changelogs/365.txt
  fastlane/metadata/android/fr-FR/changelogs/367.txt
  fastlane/metadata/android/id/changelogs/365.txt
  fastlane/metadata/android/id/changelogs/367.txt
  fastlane/metadata/android/it-IT/changelogs/365.txt
  fastlane/metadata/android/it-IT/changelogs/367.txt
  fastlane/metadata/android/iw-IL/changelogs/365.txt
  fastlane/metadata/android/iw-IL/changelogs/367.txt
  fastlane/metadata/android/ja-JP/changelogs/365.txt
  fastlane/metadata/android/ja-JP/changelogs/367.txt
  fastlane/metadata/android/ko-KR/changelogs/365.txt
  fastlane/metadata/android/ko-KR/changelogs/367.txt
  fastlane/metadata/android/nl-NL/changelogs/365.txt
  fastlane/metadata/android/nl-NL/changelogs/367.txt
  fastlane/metadata/android/pt-BR/changelogs/365.txt
  fastlane/metadata/android/pt-BR/changelogs/367.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/365.txt
  fastlane/metadata/android/ru-RU/changelogs/367.txt
  fastlane/metadata/android/sv-SE/changelogs/365.txt
  fastlane/metadata/android/sv-SE/changelogs/367.txt
  fastlane/metadata/android/tr-TR/changelogs/365.txt
  fastlane/metadata/android/tr-TR/changelogs/367.txt
  fastlane/metadata/android/zh-CN/changelogs/365.txt
  fastlane/metadata/android/zh-CN/changelogs/367.txt
  fastlane/metadata/android/zh-TW/changelogs/365.txt
  fastlane/metadata/android/zh-TW/changelogs/367.txt
Labels: Releases

#8036 REST API: Integrate latest FluxC changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ApplicationPasswordsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ApplicationPasswordsTester.kt
  build.gradle
Labels: type: enhancement, feature:REST API

#8029 Activate: Store creation unit tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/InstallationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/PlansViewModelTest.kt
Labels: Testing, feature: store creation

#8048 Merge release/11.7-rc-1 into trunk (take.2)
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#8050 Hotfix: fix crash on native Jetpack installation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt
Labels: type: crash, feature: login

#8057 Merge release/11.6.1 into release/11.7-rc-1
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt
Labels: Releases

#8060 Merge release/11.7-rc-2 into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt
Labels: Releases

#8052 [REST API] Feature Flag for testing
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/LoginFragmentsModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginUsernamePasswordFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
Labels: type: task, feature: login

#8059 Replace internal module with Google code scanner
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/qrcode/ValidateScannedValue.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles_base.xml
  libs/barcode/.gitignore
  libs/barcode/build.gradle
  libs/barcode/src/main/AndroidManifest.xml
  libs/barcode/src/main/java/com/woocommerce/android/barcode/QrCodeScanningFragment.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/ScopedExecutor.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/Utils.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/CameraReticleAnimator.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/CameraSizePair.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/CameraSource.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/CameraSourcePreview.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/FrameMetadata.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/FrameProcessor.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/FrameProcessorBase.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/GraphicOverlay.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/camera/WorkflowModel.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeConfirmingGraphic.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeField.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeGraphicBase.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeLoadingGraphic.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeProcessor.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/detection/BarcodeReticleGraphic.kt
  libs/barcode/src/main/java/com/woocommerce/android/barcode/settings/PreferenceUtils.kt
  libs/barcode/src/main/res/drawable/barcode_field_box.xml
  libs/barcode/src/main/res/drawable/ic_close_vd_white_24.xml
  libs/barcode/src/main/res/drawable/ic_help.xml
  libs/barcode/src/main/res/layout/barcode_bottom_sheet.xml
  libs/barcode/src/main/res/layout/barcode_field.xml
  libs/barcode/src/main/res/layout/camera_preview_overlay.xml
  libs/barcode/src/main/res/layout/fragment_live_barcode.xml
  libs/barcode/src/main/res/layout/top_action_bar_in_live_camera.xml
  libs/barcode/src/main/res/navigation/nav_graph_barcode_scanner.xml
  libs/barcode/src/main/res/values/colors.xml
  libs/barcode/src/main/res/values/dimens.xml
  libs/barcode/src/main/res/values/strings.xml
  settings.gradle
Labels: type: enhancement, feature: login

#8067 Remove outdated Simple Payments feedback survey
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
Labels: type: technical debt

#8066 Extract JITM query params encoder logic into a reusable class
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/QueryParamsEncoder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/QueryParamsEncoderTest.kt
Labels: feature: jitm

#8033 Feature/per app language preferences
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/res/xml/locales_config.xml
Labels: type: enhancement

#7924 Feature/check iap eligibility
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/InAppPurchasesModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/CheckIapEligibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/WooIapLogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/navigation/nav_graph_site_picker.xml
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_web.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: mobile payments, feature: store creation

#8083 Fix crash when logging in with site address
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt
Labels: type: bug

#8053 Feature/iap payment flow
  WooCommerce/src/debug/kotlin/com.woocommerce.android/iapshowcase/purchase/IAPShowcasePurchaseFragment.kt
  WooCommerce/src/debug/kotlin/com.woocommerce.android/iapshowcase/purchase/IAPShowcasePurchaseViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/InAppPurchasesModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IsIAPEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/SiteIndependentCurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/ScopedViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/PlansViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/DefaultCurrencyFormatterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/SiteIndependentCurrencyFormatterTest.kt
  libs/iap/src/main/java/com/woocommerce/android/iap/internal/planpurchase/IAPPurchaseWPComPlanActionsImpl.kt
  libs/iap/src/main/java/com/woocommerce/android/iap/pub/IAPSitePurchasePlanFactory.kt
  libs/iap/src/main/java/com/woocommerce/android/iap/pub/PurchaseWPComPlanActions.kt
  libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPError.kt
  libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/WPComProductResult.kt
  libs/iap/src/test/kotlin/com/woocommerce/android/iap/pub/IAPPurchaseWPComPlanActionsTest.kt
Labels: feature: store creation
