Repository woocommerce/woocommerce-android, pull requests merged in 2022-09, with the labels that each got.

#7281 Refactor upsell card reader banner
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerDisplayEligibilityChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/promobanner/PromoBanner.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/banner/BannerDisplayEligibilityCheckerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/MainPresenterTest.kt
Labels: type: technical debt, feature: mobile payments

#7302 [UI Tests ] Read values from mock file for orders test assertions
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/MocksReader.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/OrdersUITest.kt
Labels: feature: order list, category: ui tests

#7280 Add Pay in Person toggle on payments screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/CashOnDeliverySettingsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_credit_card.xml
  WooCommerce/src/main/res/layout/card_reader_hub_header.xml
  WooCommerce/src/main/res/layout/card_reader_hub_toggelable_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CashOnDeliverySettingsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments

#7298 Add learn more link cod
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/LearnMoreUrlProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/layout/card_reader_hub_toggelable_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/LearnMoreUrlProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: feature: mobile payments

#7312 Login: Use the new Login help webpage when opening it from "Enter Email Address" login screen.
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/UnifiedLoginTracker.kt
Labels: feature: support, feature: login

#7326 Validate order's address only when order exits
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: feature: order details, type: crash

#7319 Login: Open related Login help webpage section when opening it from "Login with WP.com email" and "Login with Site Credentials" screens.
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
Labels: feature: support, feature: login

#7331 Changed `is_editable` to `true` in mocks for non-completed orders.
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_all_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_any_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_completed_pending_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_processing_detailed.json
Labels: category: ui tests

#7325 Tracking for pay in person
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_credit_card.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTrackerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#7314 Issue/remove ipp canada feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderCountryConfigProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/InPersonPaymentsCanadaFeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderCountryConfigProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundViewModelTest.kt
Labels: feature: mobile payments

#7295 REVIEW_OPEN event tracking on push notification click
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: category: analytics

#7335 Pass new forceRefresh param to product leaderboards request
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/data/StatsRepository.kt
  build.gradle
Labels: type: enhancement, feature: stats

#7316 Check the order exits before displaying the order
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: feature: order details, type: crash

#7340 Added release notes for 10.2
  CHANGELOG.md
Labels: Releases

#7341 Merge 10.1 final to trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  fastlane/metadata/android/ar/changelogs/324.txt
  fastlane/metadata/android/ar/changelogs/326.txt
  fastlane/metadata/android/de-DE/changelogs/324.txt
  fastlane/metadata/android/de-DE/changelogs/326.txt
  fastlane/metadata/android/es-ES/changelogs/324.txt
  fastlane/metadata/android/es-ES/changelogs/326.txt
  fastlane/metadata/android/fr-FR/changelogs/324.txt
  fastlane/metadata/android/fr-FR/changelogs/326.txt
  fastlane/metadata/android/id/changelogs/324.txt
  fastlane/metadata/android/id/changelogs/326.txt
  fastlane/metadata/android/it-IT/changelogs/324.txt
  fastlane/metadata/android/it-IT/changelogs/326.txt
  fastlane/metadata/android/iw-IL/changelogs/324.txt
  fastlane/metadata/android/iw-IL/changelogs/326.txt
  fastlane/metadata/android/ja-JP/changelogs/324.txt
  fastlane/metadata/android/ja-JP/changelogs/326.txt
  fastlane/metadata/android/ko-KR/changelogs/324.txt
  fastlane/metadata/android/ko-KR/changelogs/326.txt
  fastlane/metadata/android/nl-NL/changelogs/324.txt
  fastlane/metadata/android/nl-NL/changelogs/326.txt
  fastlane/metadata/android/pt-BR/changelogs/324.txt
  fastlane/metadata/android/pt-BR/changelogs/326.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/324.txt
  fastlane/metadata/android/ru-RU/changelogs/326.txt
  fastlane/metadata/android/sv-SE/changelogs/324.txt
  fastlane/metadata/android/sv-SE/changelogs/326.txt
  fastlane/metadata/android/tr-TR/changelogs/324.txt
  fastlane/metadata/android/tr-TR/changelogs/326.txt
  fastlane/metadata/android/zh-CN/changelogs/324.txt
  fastlane/metadata/android/zh-CN/changelogs/326.txt
  fastlane/metadata/android/zh-TW/changelogs/324.txt
  fastlane/metadata/android/zh-TW/changelogs/326.txt
Labels: Releases

#7343 Merge 10.2 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#7339 Replace deprecated menu methods
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/texteditor/SimpleTextEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt
Labels: type: technical debt

#7330 Issue/7299 site credentials mismatch
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  fastlane/resources/values/strings.xml
Labels: type: bug, feature: login

#7342 [Login] Jetpack connection Part 1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: login

#7354 Replaced deprecated menu methods usage. InboxFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxFragment.kt
Labels: type: technical debt

#7359 Refactor menu methods
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginDiscoveryErrorFragment.kt
Labels: type: enhancement

#7350 [Login] Explanation when signing using a non-atomic site
  WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_me_sites.json
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/views/LoginNoStoresView.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt
Labels: type: enhancement, feature: login

#7360 Replace deprecated menu calls login
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoWPcomAccountFoundFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginSiteCheckErrorFragment.kt
  WooCommerce/src/main/res/layout-land/fragment_login_jetpack_required.xml
  WooCommerce/src/main/res/layout/fragment_login_jetpack_required.xml
Labels: type: technical debt

#7355 Remove necessity of entering credentials in the card reader purchase flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#7362 Add swipe thresholds
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SwipeToComplete.kt
Labels: type: bug

#7356 Remove unused feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: technical debt

#7365 Fix build issue: add missing navigation argument to the second declaration of WPComWebViewFragment
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
Labels: type: task, category: tooling

#7371 Removed redundant setHasOptionsMenu call. Removed commented code
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: type: technical debt

#7376 Fix dependency injection
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListRemoteViewsFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewModel.kt
Labels: feature: Widgets

#7377 Merge 10.2 final to trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SwipeToComplete.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/326.txt
  fastlane/metadata/android/ar/changelogs/328.txt
  fastlane/metadata/android/de-DE/changelogs/326.txt
  fastlane/metadata/android/de-DE/changelogs/328.txt
  fastlane/metadata/android/es-ES/changelogs/326.txt
  fastlane/metadata/android/es-ES/changelogs/328.txt
  fastlane/metadata/android/fr-FR/changelogs/326.txt
  fastlane/metadata/android/fr-FR/changelogs/328.txt
  fastlane/metadata/android/id/changelogs/326.txt
  fastlane/metadata/android/id/changelogs/328.txt
  fastlane/metadata/android/it-IT/changelogs/326.txt
  fastlane/metadata/android/it-IT/changelogs/328.txt
  fastlane/metadata/android/iw-IL/changelogs/326.txt
  fastlane/metadata/android/iw-IL/changelogs/328.txt
  fastlane/metadata/android/ja-JP/changelogs/326.txt
  fastlane/metadata/android/ja-JP/changelogs/328.txt
  fastlane/metadata/android/ko-KR/changelogs/326.txt
  fastlane/metadata/android/ko-KR/changelogs/328.txt
  fastlane/metadata/android/nl-NL/changelogs/326.txt
  fastlane/metadata/android/nl-NL/changelogs/328.txt
  fastlane/metadata/android/pt-BR/changelogs/326.txt
  fastlane/metadata/android/pt-BR/changelogs/328.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/326.txt
  fastlane/metadata/android/ru-RU/changelogs/328.txt
  fastlane/metadata/android/sv-SE/changelogs/326.txt
  fastlane/metadata/android/sv-SE/changelogs/328.txt
  fastlane/metadata/android/tr-TR/changelogs/326.txt
  fastlane/metadata/android/tr-TR/changelogs/328.txt
  fastlane/metadata/android/zh-CN/changelogs/326.txt
  fastlane/metadata/android/zh-CN/changelogs/328.txt
  fastlane/metadata/android/zh-TW/changelogs/326.txt
  fastlane/metadata/android/zh-TW/changelogs/328.txt
Labels: Releases

#7375 [Login] Jetpack Connection: tracking and enable feature
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/FluxCExeptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: enhancement, feature: login

#7364 [Login] Jetpack connection for site credentials login Part 2
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/FluxCExeptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/UIMessageResolverModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/activity_login.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: login

#7181 Stripe SDK version update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  build.gradle
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#7379 Merge 10.3 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#7382 Refactor list repository
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/GetWidgetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/data/StatsRepository.kt
Labels: feature: Widgets

#7367 Nick/app widget selected site
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/StatsWidgetProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListRemoteViewsFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
Labels: feature: stats

#7383 Fix logic of signout function in AccountRepository
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  build.gradle
Labels: type: bug

#7385 Nick/app widget cleanup
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/res/layout/widget_site_selector_list_item.xml
  WooCommerce/src/main/res/values/integers.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainPresenterTest.kt
Labels: feature: stats

#7387 Don't round the revenue stats
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
Labels: feature: stats

#7390 Nick/app widget logged out improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetUpdater.kt
Labels: feature: stats

#7391 Widget/last updated message
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/layout/stats_widget_header.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: Widgets

#7310 Replace deprecated PackageManager methods
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/PackageManagerExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ChromeCustomTabUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/PackageUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/SystemVersionUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AppRatingDialog.kt
Labels: type: technical debt

#7389 fix: update Jacoco execution files paths after AGP update
  config/gradle/jacoco.gradle
Labels: type: bug, category: tooling, category: unit tests

#7388 Widget/analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayStatsWidgetProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListRemoteViewsFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: type: enhancement, category: analytics

#7393 Feature/stats today widget
  RELEASE-NOTES.txt
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/WidgetUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/StatsWidgetProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/GetWidgetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayStatsWidgetProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListRemoteViewsFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayWidgetUpdater.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreStatsView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/data/StatsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/main/res/drawable-hdpi/stats_today_widget_preview.png
  WooCommerce/src/main/res/drawable-xhdpi/stats_today_widget_preview.png
  WooCommerce/src/main/res/drawable-xxhdpi/stats_today_widget_preview.png
  WooCommerce/src/main/res/drawable/bg_rectangle_radius_6dp.xml
  WooCommerce/src/main/res/layout/fragment_widget_site_selector.xml
  WooCommerce/src/main/res/layout/stats_widget_error.xml
  WooCommerce/src/main/res/layout/stats_widget_header.xml
  WooCommerce/src/main/res/layout/stats_widget_list.xml
  WooCommerce/src/main/res/layout/stats_widget_list_item.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/integers.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/main/res/values/styles_widget.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/main/res/xml/stats_today_widget_info.xml
Labels: feature: stats

#7392 Added release notes for 10.4
  CHANGELOG.md
Labels: Releases

#7396 Merge 10.3 code freeze to trunk
  Gemfile.lock
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/328.txt
  fastlane/metadata/android/ar/changelogs/330.txt
  fastlane/metadata/android/de-DE/changelogs/328.txt
  fastlane/metadata/android/de-DE/changelogs/330.txt
  fastlane/metadata/android/es-ES/changelogs/328.txt
  fastlane/metadata/android/es-ES/changelogs/330.txt
  fastlane/metadata/android/fr-FR/changelogs/328.txt
  fastlane/metadata/android/fr-FR/changelogs/330.txt
  fastlane/metadata/android/id/changelogs/328.txt
  fastlane/metadata/android/id/changelogs/330.txt
  fastlane/metadata/android/it-IT/changelogs/328.txt
  fastlane/metadata/android/it-IT/changelogs/330.txt
  fastlane/metadata/android/iw-IL/changelogs/328.txt
  fastlane/metadata/android/iw-IL/changelogs/330.txt
  fastlane/metadata/android/ja-JP/changelogs/328.txt
  fastlane/metadata/android/ja-JP/changelogs/330.txt
  fastlane/metadata/android/ko-KR/changelogs/328.txt
  fastlane/metadata/android/ko-KR/changelogs/330.txt
  fastlane/metadata/android/nl-NL/changelogs/328.txt
  fastlane/metadata/android/nl-NL/changelogs/330.txt
  fastlane/metadata/android/pt-BR/changelogs/328.txt
  fastlane/metadata/android/pt-BR/changelogs/330.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/328.txt
  fastlane/metadata/android/ru-RU/changelogs/330.txt
  fastlane/metadata/android/sv-SE/changelogs/328.txt
  fastlane/metadata/android/sv-SE/changelogs/330.txt
  fastlane/metadata/android/tr-TR/changelogs/328.txt
  fastlane/metadata/android/tr-TR/changelogs/330.txt
  fastlane/metadata/android/zh-CN/changelogs/328.txt
  fastlane/metadata/android/zh-CN/changelogs/330.txt
  fastlane/metadata/android/zh-TW/changelogs/328.txt
  fastlane/metadata/android/zh-TW/changelogs/330.txt
Labels: Releases

#7398 widget/update-release-notes
  RELEASE-NOTES.txt
Labels: feature: stats

#7397 Capitalize las updated label
  WooCommerce/src/main/res/layout/stats_widget_header.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: Widgets

#7399 Update the login library reference
  build.gradle
Labels: feature: login

#7410 Merge 10.4 code freeze to trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#7402 Fix crash in Account Mismatch screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt
Labels: type: crash, feature: login

#7395 Fab with anchor view
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/message/DefaultUIMessageResolver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/message/UIMessageResolverModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
Labels: type: enhancement, category: design

#7418 order create menu deprecated
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreateEditFeeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/notes/OrderCreateEditCustomerNoteFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/products/OrderCreateEditProductSelectionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/shipping/OrderCreateEditShippingFragment.kt
Labels: type: technical debt

#7423 Replaces deprecated menu methods
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/BaseOrderEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsFragment.kt
Labels: type: technical debt

#7435 Replace deprecated menu usage
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPaymentFragment.kt
Labels: type: technical debt

#7431 Replace deprecated menu methods
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/fulfill/OrderFulfillFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteFragment.kt
Labels: type: technical debt

#7429 Fix order details performance transaction validation
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/WooPlugin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncher.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncherTest.kt
Labels: type: bug, feature: order details, category: performance

#7427 Fix Multiple Substitutions Specified in Non-Positional Format Warnings
  WooCommerce/src/main/res/values/strings.xml
Labels: category: tooling, category: i18n

#7450 issue/7449-one-per-order
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
Labels: feature: product details

#7443 [UI Tests] - Update test assertions for create order test
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/data/countries.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/2201/2201_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_all_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_create_simple_product.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/ScreenshotTest.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/CustomerDetailsScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderCreationScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/OrderSelectProductScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/UnifiedOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/OrdersUITest.kt
Labels: category: ui tests

#7455 Hackweek project - Optional leakcanary installation
  WooCommerce/build.gradle
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/leakcanary/kotlin/com/woocommerce/android/LeakCanaryInstaller.kt
Labels: type: enhancement

#7347 Removed redundant `setHasOptionsMenu` usage FeedbackCompletedFragment and FeedbackSurveyFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackCompletedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackSurveyFragment.kt
Labels: type: technical debt

#7457 [UI Tests] Enabled "reviewListShowsAllReviews" test
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/reviews/products_reviews_all.json
  WooCommerce/src/androidTest/assets/mocks/mappings/notifications/notifications_list.json
  WooCommerce/src/androidTest/assets/mocks/mappings/notifications/rest_v11_notifications.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/ReviewsListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/SingleReviewScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ReviewsUITest.kt
Labels: category: ui tests

#7461 Hackweek. Improved autofill for the login
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/EditTextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginEmailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginEmailPasswordFragment.kt
Labels: type: enhancement

#7446 Upsell card reader banner re-appears after dismissal and doing the pull to refresh on the order listing screen.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/LandscapeChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
Labels: feature: mobile payments

#7459 Fix issue causing duplicate files when uploading multiple files
  RELEASE-NOTES.txt
  build.gradle
Labels: type: bug, feature: product details

#7467 Fixed background color of the products without pictures for the dark mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemView.kt
Labels: type: bug

#7468 [UI Tests] - Add customer note assertion to create order test
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/2201/2201_detailed.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/orders/orders_create_simple_product.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/orders/UnifiedOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/OrdersUITest.kt
Labels: type: task, category: ui tests, feature: order creation

#7470 Added release notes for 10.6
  CHANGELOG.md
Labels: Releases
