Repository woocommerce/woocommerce-android, pull requests merged in 2023-06, with the labels that each got.

#9130 [UI Tests] Added existing order details E2E test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersRealAPI.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductsRealAPI.kt
Labels: category: ui tests

#9090 [TTP] Update Stripe SDK to 2.20.1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/TapToPayAvailabilityStatus.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/TapToPayAvailabilityStatusTest.kt
  build.gradle
  libs/cardreader/build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/AdditionalInfoMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/AdditionalInfoMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CollectPaymentActionTest.kt
Labels: feature: mobile payments, dependency update

#9139 Reliability: Introduce local vs store timezone difference tracks
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/TimeZoneExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TimezoneProvider.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
Labels: type: task, feature: analytics

#9175 Reliability: Persist when Timezone track is triggered for a given site
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
Labels: type: task, feature: analytics

#9141 Gift cards no order crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: bug, type: crash

#9183 Merge 13.8 finalization into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/418.txt
  fastlane/metadata/android/ar/changelogs/420.txt
  fastlane/metadata/android/de-DE/changelogs/418.txt
  fastlane/metadata/android/de-DE/changelogs/420.txt
  fastlane/metadata/android/en-US/changelogs/418.txt
  fastlane/metadata/android/en-US/changelogs/420.txt
  fastlane/metadata/android/es-ES/changelogs/418.txt
  fastlane/metadata/android/es-ES/changelogs/420.txt
  fastlane/metadata/android/fr-FR/changelogs/418.txt
  fastlane/metadata/android/fr-FR/changelogs/420.txt
  fastlane/metadata/android/id/changelogs/418.txt
  fastlane/metadata/android/id/changelogs/420.txt
  fastlane/metadata/android/it-IT/changelogs/418.txt
  fastlane/metadata/android/it-IT/changelogs/420.txt
  fastlane/metadata/android/iw-IL/changelogs/418.txt
  fastlane/metadata/android/iw-IL/changelogs/420.txt
  fastlane/metadata/android/ja-JP/changelogs/418.txt
  fastlane/metadata/android/ja-JP/changelogs/420.txt
  fastlane/metadata/android/ko-KR/changelogs/418.txt
  fastlane/metadata/android/ko-KR/changelogs/420.txt
  fastlane/metadata/android/nl-NL/changelogs/418.txt
  fastlane/metadata/android/nl-NL/changelogs/420.txt
  fastlane/metadata/android/pt-BR/changelogs/418.txt
  fastlane/metadata/android/pt-BR/changelogs/420.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/418.txt
  fastlane/metadata/android/ru-RU/changelogs/420.txt
  fastlane/metadata/android/sv-SE/changelogs/418.txt
  fastlane/metadata/android/sv-SE/changelogs/420.txt
  fastlane/metadata/android/tr-TR/changelogs/418.txt
  fastlane/metadata/android/tr-TR/changelogs/420.txt
  fastlane/metadata/android/zh-CN/changelogs/418.txt
  fastlane/metadata/android/zh-CN/changelogs/420.txt
  fastlane/metadata/android/zh-TW/changelogs/418.txt
  fastlane/metadata/android/zh-TW/changelogs/420.txt
Labels: Releases

#9166 Updates Colored Buttons Style used in Login flow
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/styles_login.xml
Labels: category: design

#9185 Merge 13.9 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#9182 Fix analytics performance measurements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
Labels: category: performance, feature: analytics, category: reliability

#9176 Handle UPC barcode formats
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CheckDigitRemover.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UPCCheckDigitRemoverTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: feature: mobile payments

#9179 Enable Sentry Profiling
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfigTest.kt
Labels: category: performance

#9123 Add product: Show celebratory view when the first product is created
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/FirstProductCelebrationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/FirstProductCelebrationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/FirstProductCelebrationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details

#9192 Privacy Choices: use Geo API to determine country
  WooCommerce/src/androidTest/assets/mocks/mappings/geo/rest_geo.json
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/privacy/GeoRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/privacy/banner/domain/IsUsersCountryGdprCompliant.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/privacy/banner/domain/ShouldShowPrivacyBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TelephonyManagerProvider.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/privacy/banner/domain/IsUsersCountryGdprCompliantTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/privacy/banner/domain/ShouldShowPrivacyBannerTest.kt
  build.gradle
Labels: status: do not merge, feature: privacy

#9203 Merge 13.9 beta 2 into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/WPComRemoteFeatureFlagRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreInstallationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/IsRemoteFeatureFlagEnabled.kt
Labels: Releases

#9201 Quick Fix: Product Selector backgroundColor and elevation of TopAppBar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
Labels: type: bug

#9197 Handle process death while scanning the barcode
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: feature: mobile payments

#9199 Fix crash when required userName is not available for closing an account
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
Labels: type: crash

#9206 Merge 13.9 finalization into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/420.txt
  fastlane/metadata/android/ar/changelogs/423.txt
  fastlane/metadata/android/de-DE/changelogs/420.txt
  fastlane/metadata/android/de-DE/changelogs/423.txt
  fastlane/metadata/android/en-US/changelogs/420.txt
  fastlane/metadata/android/en-US/changelogs/423.txt
  fastlane/metadata/android/es-ES/changelogs/420.txt
  fastlane/metadata/android/es-ES/changelogs/423.txt
  fastlane/metadata/android/fr-FR/changelogs/420.txt
  fastlane/metadata/android/fr-FR/changelogs/423.txt
  fastlane/metadata/android/id/changelogs/420.txt
  fastlane/metadata/android/id/changelogs/423.txt
  fastlane/metadata/android/it-IT/changelogs/420.txt
  fastlane/metadata/android/it-IT/changelogs/423.txt
  fastlane/metadata/android/iw-IL/changelogs/420.txt
  fastlane/metadata/android/iw-IL/changelogs/423.txt
  fastlane/metadata/android/ja-JP/changelogs/420.txt
  fastlane/metadata/android/ja-JP/changelogs/423.txt
  fastlane/metadata/android/ko-KR/changelogs/420.txt
  fastlane/metadata/android/ko-KR/changelogs/423.txt
  fastlane/metadata/android/nl-NL/changelogs/420.txt
  fastlane/metadata/android/nl-NL/changelogs/423.txt
  fastlane/metadata/android/pt-BR/changelogs/420.txt
  fastlane/metadata/android/pt-BR/changelogs/423.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/420.txt
  fastlane/metadata/android/ru-RU/changelogs/423.txt
  fastlane/metadata/android/sv-SE/changelogs/420.txt
  fastlane/metadata/android/sv-SE/changelogs/423.txt
  fastlane/metadata/android/tr-TR/changelogs/420.txt
  fastlane/metadata/android/tr-TR/changelogs/423.txt
  fastlane/metadata/android/zh-CN/changelogs/420.txt
  fastlane/metadata/android/zh-CN/changelogs/423.txt
  fastlane/metadata/android/zh-TW/changelogs/420.txt
  fastlane/metadata/android/zh-TW/changelogs/423.txt
Labels: Releases

#9207 Merge 14.0 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#9205 Upload unit tests results as Buildkite artifacts
  .buildkite/pipeline.yml
Labels: category: tooling

#9158 [JITM] Caching of JITMs
  RELEASE-NOTES.txt
  WooCommerce/src/debug/assets/jitm_testing.json
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmMessagePathsProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmStoreInMemoryCache.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmStoreInMemoryCacheTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmViewModelTest.kt
Labels: feature: jitm

#9210 Make coupon validator case insensitive
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/CouponValidator.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/coupon/CouponValidatorTest.kt
Labels: type: bug, feature: order creation

#9215 Feature/improve polling strategy new stores
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationConst.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/ObserveSiteInstallation.kt
Labels: feature: store creation

#9219 Feature/9209 add blaze entry points
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/IsBlazeEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/ic_more_menu_blaze.xml
  WooCommerce/src/main/res/menu/menu_product_detail_fragment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: type: enhancement, feature: product details, feature: more menu

#9220 Check metadataArray is not null
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailRepository.kt
Labels: type: crash, feature: product details, category: reliability

#9240 Handle EAN-13, EAN-8 barcode formats
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CheckDigitRemover.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CheckDigitRemoverFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CheckDigitRemoverFactoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EAN13CheckDigitRemoverTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EAN8CheckDigitRemoverTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: feature: mobile payments

#9243 Added release notes for 14.1
  CHANGELOG.md
Labels: Releases

#9224 AI: Generate product sharing message part 1: UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/ic_ai.xml
  WooCommerce/src/main/res/drawable/ic_regenerate.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details, compose

#9236 AI: Generate product sharing message part 2: Functionality
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details

#9229 Add AI product description generator label to product onboarding
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/IsAIProductDescriptionEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/drawable/ic_ai.xml
  WooCommerce/src/main/res/drawable/ic_ai_share_button.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModelTest.kt
Labels: feature: store onboarding

#9222 [TTP] Improve TTP pin required error handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentErrorMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: mobile payments

#9223 [IPP] Updated stripe terminal version
  RELEASE-NOTES.txt
  build.gradle
Labels: feature: mobile payments

#9253 Fix: Selected site timezone crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
Labels: type: crash

#9252 Update displayed messages while loading new store
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store creation

#9250 Add the "feature" parameter to AI completion calls
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingViewModel.kt
  build.gradle
Labels: feature: product details

#9242 [Product Search] Remove new line symbols from the search
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
Labels: type: bug

#9264 Fix/9262 tracking free trial created
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
Labels: category: analytics, feature: analytics

#9257 Add new chrome client to support picking images from authenticated we…
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/WebChromeClientWithImageChooser.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/WebView.kt
Labels: type: bug

#9261 Fixes tracking for Blaze cta displayed from product detail
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: type: bug, category: analytics, feature: analytics

#9263 Handle INVALID_COUPON error
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  build.gradle
Labels: type: enhancement

#9279 UI: update text alignment in more menu button description.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
Labels: feature: more menu, compose

#9274 Feature/ai share description design polishes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSharingBottomSheet.kt
  WooCommerce/src/main/res/drawable/ic_ai_share_button.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details, category: design, compose

#9278 Added release notes for 14.2
  CHANGELOG.md
Labels: Releases

#9283 Merge 14.2 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#9277 [UI Tests] Added Stats Chart Tap UI Test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/mystore/MyStoreScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/StatsUITest.kt
Labels: category: ui tests

#9288 AI product description: Write with AI button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyButtonView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/WCProductPropertyView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ProductPropertiesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductProperty.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ButtonViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/ComplexPropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/PropertyViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/viewholders/RatingBarViewHolder.kt
  WooCommerce/src/main/res/layout/product_property_button_view.xml
  WooCommerce/src/main/res/layout/product_property_button_view_layout.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details

#9287 Clean up the TextField declarations
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
Labels: type: technical debt

#9189 Use Annotate Tests Results to report test failures in Buildkite and Slack
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: type: task, category: tooling

#9280 change minus button click behaviour
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: type: task, feature: order creation

#9285 Issue/9284 after login redirection
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: feature: login

#9298 Migrate the scanning library from Google Code Scanner to MLKit
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/CodeScannerModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScannerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanningFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanningTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/InputImageProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleMLKitCodeScanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ScalableImageView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/layout/fragment_barcode_scanning.xml
  WooCommerce/src/main/res/layout/order_detail_install_wc_shipping_banner.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/main/res/values/attrs.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/BarcodeScanningTrackerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CodeScannerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  build.gradle
Labels: feature: mobile payments

#9317 Android CameraX version
  WooCommerce/build.gradle
  build.gradle
Labels: feature: mobile payments

#9308 [Order Creation] Feature flag and skeleton for the new screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
Labels: feature: order creation

#9302 Update the Compose BOM version
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/LiveDataUtils.kt
  build.gradle
Labels: type: technical debt

#9300 Multiple coupon support in Order creation
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/list/OrderCouponListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/list/OrderCreateCouponListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/list/OrderCreateCouponListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/res/layout/order_creation_payment_section.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/coupon/CouponValidatorTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/coupon/OrderCreateCouponEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/coupon/OrderCreateCouponEditionViewModelTest.kt
Labels: feature: order creation, feature: order editing

#9335 Avoid null pointer exception crash when tracking Blaze cta visible
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
Labels: type: crash

#9293 AI product description: Celebration dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/AIProductDescriptionBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/AIProductDescriptionBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/AIProductDescriptionViewModel.kt
  WooCommerce/src/main/res/drawable/img_ai_generated_content.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details

#9331 Added release notes for 14.3
  CHANGELOG.md
Labels: Releases
