Repository woocommerce/woocommerce-android, pull requests merged in 2023-02, with the labels that each got.

#8255 [REST API] Improve Cookie Nonce error handling
  build.gradle
Labels: type: bug, status: do not merge, priority: low, feature: REST API

#8279 Fix/crash on profiler industries step
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerIndustriesViewModel.kt
Labels: type: crash, priority: high, feature: store creation

#8285 Merge release/12.0.1 into release/12.1 (`hotfix`)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerIndustriesViewModel.kt
Labels: Releases

#8287 Merge release/12.1-rc-2 into trunk (`hotfix beta`)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerIndustriesViewModel.kt
Labels: Releases

#8206 Feature/8182 iap single subcription requirement
  WooCommerce/src/debug/kotlin/com.woocommerce.android/iapshowcase/purchase/IAPShowcaseMobilePayAPIProvider.kt
  WooCommerce/src/debug/kotlin/com.woocommerce.android/iapshowcase/purchase/IAPShowcasePurchaseFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/CheckIapEligibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapMobilePayApiProvider.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModelTest.kt
Labels: type: enhancement, feature: store creation

#8257 [Compose] Fix back button orientation in RTL languages
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/SSRScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/WooLogViewerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/ModifierExts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/details/CouponDetailsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/error/base/LoginErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/start/JetpackActivationStartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/mystoresummary/MyStoreSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryScreen.kt
Labels: type: bug, compose

#8273 Domain change: Domain search UI refacotring
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store onboarding

#8275 Domain change: Make the Learn more link interactive
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/CurrentDomainsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/CurrentDomainsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainChangeViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store onboarding

#8286 IPP: Stripetermnial SDK version update to 2.16
  RELEASE-NOTES.txt
  libs/cardreader/build.gradle
Labels: feature: mobile payments

#8292 Fix build
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/CurrentDomainsScreen.kt
Labels: type: task

#8291 TPP: Set platform = android key-value on the payment intent metadata
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/MetaDataKeys.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: mobile payments

#8296 Fix logout crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
Labels: type: crash, feature: login

#8284 TPP: handle specific tap on mobile errors from the stripe SDK
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentErrorMapperTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: feature: mobile payments

#8302 [REST API] Validate credentials' username before using
  build.gradle
Labels: type: bug, feature: REST API

#8304 Merge release/12.1 into trunk (`final`)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  fastlane/metadata/android/ar/changelogs/377.txt
  fastlane/metadata/android/ar/changelogs/381.txt
  fastlane/metadata/android/de-DE/changelogs/377.txt
  fastlane/metadata/android/de-DE/changelogs/381.txt
  fastlane/metadata/android/es-ES/changelogs/377.txt
  fastlane/metadata/android/es-ES/changelogs/381.txt
  fastlane/metadata/android/fr-FR/changelogs/377.txt
  fastlane/metadata/android/fr-FR/changelogs/381.txt
  fastlane/metadata/android/id/changelogs/377.txt
  fastlane/metadata/android/id/changelogs/381.txt
  fastlane/metadata/android/it-IT/changelogs/377.txt
  fastlane/metadata/android/it-IT/changelogs/381.txt
  fastlane/metadata/android/iw-IL/changelogs/377.txt
  fastlane/metadata/android/iw-IL/changelogs/381.txt
  fastlane/metadata/android/ja-JP/changelogs/377.txt
  fastlane/metadata/android/ja-JP/changelogs/381.txt
  fastlane/metadata/android/ko-KR/changelogs/377.txt
  fastlane/metadata/android/ko-KR/changelogs/381.txt
  fastlane/metadata/android/nl-NL/changelogs/377.txt
  fastlane/metadata/android/nl-NL/changelogs/381.txt
  fastlane/metadata/android/pt-BR/changelogs/377.txt
  fastlane/metadata/android/pt-BR/changelogs/381.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/377.txt
  fastlane/metadata/android/ru-RU/changelogs/381.txt
  fastlane/metadata/android/sv-SE/changelogs/377.txt
  fastlane/metadata/android/sv-SE/changelogs/381.txt
  fastlane/metadata/android/tr-TR/changelogs/377.txt
  fastlane/metadata/android/tr-TR/changelogs/381.txt
  fastlane/metadata/android/zh-CN/changelogs/377.txt
  fastlane/metadata/android/zh-CN/changelogs/381.txt
  fastlane/metadata/android/zh-TW/changelogs/377.txt
  fastlane/metadata/android/zh-TW/changelogs/381.txt
Labels: Releases

#8303 Added release notes for 12.2
  CHANGELOG.md
Labels: Releases

#8308 Merge release/12.2-rc-1 into trunk (`beta`)
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
  tools/rename_apk_aab.sh
Labels: Releases

#8306 [REST API] Validate credentials username before attempting password delete
  build.gradle
Labels: type: bug, feature: REST API

#8309 [Bug] [IPP Feedback Survey] Add missing dark mode icon
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/layout/ipp_feedback_banner.xml
Labels: type: bug, priority: low

#8313 Added release notes for 12.3
  CHANGELOG.md
Labels: Releases

#8315 Merge release/12.3-rc-1 into trunk (`beta`)
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/Fastfile
Labels: Releases

#8324 Add higher CI priority to release builds
  .buildkite/release-builds.yml
Labels: category: tooling

#8322 [Analysis] Resolve All Adapter Position Deprecation Warnings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailShippingLabelsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelPackagesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingClassAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ParentCategoryListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/DraggableItemTouchHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  config/detekt/baseline.xml
Labels: type: technical debt

#8320 REST API: add a zendesk tag to help HEs identify the connection type
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/ZendeskHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/support/help/HelpViewModelTest.kt
Labels: type: enhancement, feature: support, feature: REST API

#8317 IPP: Disconnect from a connected reader BT or built in if user leaves an error screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/CardReaderType.kt
Labels: feature: mobile payments

#8312 [Bug] [IPP Feedback Survey] Error handling in `GetIPPFeedbackBannerData`
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerDataTest.kt
Labels: feature: ipp feedback

#8289 Issue/8282 remove xmlrpc checks
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WPApiSiteRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModelTest.kt
  build.gradle
Labels: type: enhancement, feature: REST API

#8305 [REST API] Update wording of the logout dialog when using site credentials
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: REST API

#8300 TPP: Tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/CardReaderTypeSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/statuschecker/CardReaderStatusCheckerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/IsTapToPayAvailable.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/CardReaderTypeSelectionViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTrackerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/statuschecker/CardReaderStatusCheckerViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/IsTapToPayAvailableTest.kt
Labels: category: analytics, feature: analytics

#8325 TPP: Refactor TPP availability checker to use card reader country configuration
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReadersMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/IsTapToPayAvailable.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReadersMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/IsTapToPayAvailableTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/config/CardReaderConfigForUSA.kt
Labels: feature: mobile payments

#8323 [REST API] Remove AB test and update flow
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/ExperimentTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/FirebaseRemoteConfigRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/config/RemoteConfigRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/main/res/layout-land/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout-sw600dp/fragment_login_prologue.xml
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/config/FirebaseRemoteConfigRepositoryTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
Labels: type: enhancement, feature: REST API

#8297 Domain change: Loading of site domains & active plan
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/CurrentDomainsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainChangeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainChangeViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store onboarding

#8319 Ignore length of the lines that contains back ticks
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/iap/IapEligibilityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerDataTest.kt
  config/detekt/detekt.yml
Labels: status: do not merge, category: tooling

#8342 Fix Jetpack identification during the WPCom site discovery
  build.gradle
Labels: type: bug, feature: REST API

#8341 Fix Clear filters button visibility on Order list
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesViewModelTest.kt
Labels: type: bug, category: analytics

#8343 Fix error handling for Jetpack native installation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/sitecredentials/JetpackActivationSiteCredentialsViewModel.kt
Labels: type: bug, feature: login

#8347 Issue/track order creation ipp flows
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tracker/OrderDurationRecorder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTracker.kt
Labels: feature: mobile payments, feature: analytics

#8353 Merge release/12.3 into trunk (`final`)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt
  fastlane/metadata/android/ar/changelogs/383.txt
  fastlane/metadata/android/ar/changelogs/385.txt
  fastlane/metadata/android/de-DE/changelogs/383.txt
  fastlane/metadata/android/de-DE/changelogs/385.txt
  fastlane/metadata/android/es-ES/changelogs/383.txt
  fastlane/metadata/android/es-ES/changelogs/385.txt
  fastlane/metadata/android/fr-FR/changelogs/383.txt
  fastlane/metadata/android/fr-FR/changelogs/385.txt
  fastlane/metadata/android/id/changelogs/383.txt
  fastlane/metadata/android/id/changelogs/385.txt
  fastlane/metadata/android/it-IT/changelogs/383.txt
  fastlane/metadata/android/it-IT/changelogs/385.txt
  fastlane/metadata/android/iw-IL/changelogs/383.txt
  fastlane/metadata/android/iw-IL/changelogs/385.txt
  fastlane/metadata/android/ja-JP/changelogs/383.txt
  fastlane/metadata/android/ja-JP/changelogs/385.txt
  fastlane/metadata/android/ko-KR/changelogs/383.txt
  fastlane/metadata/android/ko-KR/changelogs/385.txt
  fastlane/metadata/android/nl-NL/changelogs/383.txt
  fastlane/metadata/android/nl-NL/changelogs/385.txt
  fastlane/metadata/android/pt-BR/changelogs/383.txt
  fastlane/metadata/android/pt-BR/changelogs/385.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/383.txt
  fastlane/metadata/android/ru-RU/changelogs/385.txt
  fastlane/metadata/android/sv-SE/changelogs/383.txt
  fastlane/metadata/android/sv-SE/changelogs/385.txt
  fastlane/metadata/android/tr-TR/changelogs/383.txt
  fastlane/metadata/android/tr-TR/changelogs/385.txt
  fastlane/metadata/android/zh-CN/changelogs/383.txt
  fastlane/metadata/android/zh-CN/changelogs/385.txt
  fastlane/metadata/android/zh-TW/changelogs/383.txt
  fastlane/metadata/android/zh-TW/changelogs/385.txt
Labels: Releases

#8352 Added release notes for 12.4
  CHANGELOG.md
Labels: Releases

#8354 Merge release/12.4-rc-1 into trunk (`beta`)
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#8344 [Support Requests] Set Support Requests Feature Flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: support

#8345 [Support Requests] Adapt zendesk code to support Request Creation from API Providers
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/SupportModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/ZendeskHelper.kt
Labels: feature: support

#8339 IPP: Use auto size with max line restriction for the labels
  WooCommerce/src/main/res/layout/card_reader_payment_dialog.xml
  WooCommerce/src/main/res/layout/card_reader_type_selection_dialog.xml
Labels: type: bug, feature: mobile payments

#8264 Send track events when exiting all product settings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductInventoryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductInventoryViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductPricingViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductShippingViewModelTest.kt
Labels: type: bug, category: analytics, feature: product details

#8384 Fix deliver results navigation in Products Filter
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterOptionListFragment.kt
Labels: type: crash, feature: coupons

#8360 Domain change: Premium domains
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/domain/DomainSuggestionsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/domain/DomainSuggestionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/CurrentDomainsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainSearchFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainSearchViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_domain_change.xml
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  build.gradle
Labels: feature: store onboarding

#8362 Domain change: Domain dashboard ViewModel refactoring
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/domain/DomainSuggestionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainDashboard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainDashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainDashboardViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainSearchFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainSearchViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_domain_change.xml
Labels: feature: store creation

#8393 refactor learn more TV to reuse card_reader_learn_more_section.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_hub.xml
  WooCommerce/src/main/res/layout/fragment_take_payment.xml
Labels: type: enhancement

#8373 Domain change: Access to domains
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcherTest.kt
Labels: feature: store onboarding

#8411 Added release notes for 12.5
  CHANGELOG.md
Labels: Releases

#8412 Merge release/12.4 into trunk (`final`)
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/385.txt
  fastlane/metadata/android/ar/changelogs/387.txt
  fastlane/metadata/android/de-DE/changelogs/385.txt
  fastlane/metadata/android/de-DE/changelogs/387.txt
  fastlane/metadata/android/es-ES/changelogs/385.txt
  fastlane/metadata/android/es-ES/changelogs/387.txt
  fastlane/metadata/android/fr-FR/changelogs/385.txt
  fastlane/metadata/android/fr-FR/changelogs/387.txt
  fastlane/metadata/android/id/changelogs/385.txt
  fastlane/metadata/android/id/changelogs/387.txt
  fastlane/metadata/android/it-IT/changelogs/385.txt
  fastlane/metadata/android/it-IT/changelogs/387.txt
  fastlane/metadata/android/iw-IL/changelogs/385.txt
  fastlane/metadata/android/iw-IL/changelogs/387.txt
  fastlane/metadata/android/ja-JP/changelogs/385.txt
  fastlane/metadata/android/ja-JP/changelogs/387.txt
  fastlane/metadata/android/ko-KR/changelogs/385.txt
  fastlane/metadata/android/ko-KR/changelogs/387.txt
  fastlane/metadata/android/nl-NL/changelogs/385.txt
  fastlane/metadata/android/nl-NL/changelogs/387.txt
  fastlane/metadata/android/pt-BR/changelogs/385.txt
  fastlane/metadata/android/pt-BR/changelogs/387.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/385.txt
  fastlane/metadata/android/ru-RU/changelogs/387.txt
  fastlane/metadata/android/sv-SE/changelogs/385.txt
  fastlane/metadata/android/sv-SE/changelogs/387.txt
  fastlane/metadata/android/tr-TR/changelogs/385.txt
  fastlane/metadata/android/tr-TR/changelogs/387.txt
  fastlane/metadata/android/zh-CN/changelogs/385.txt
  fastlane/metadata/android/zh-CN/changelogs/387.txt
  fastlane/metadata/android/zh-TW/changelogs/385.txt
  fastlane/metadata/android/zh-TW/changelogs/387.txt
Labels: Releases

#8414 Merge release/12.5-rc-1 into trunk (`beta`)
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#8351 TPP: Replace TTP specific illustration
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-hdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_ipp_reader_type_selection.webp
  WooCommerce/src/main/res/drawable/img_ipp_reader_type_selection.xml
  WooCommerce/src/main/res/layout/card_reader_type_selection_dialog.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: feature: mobile payments

#8361 [Support Requests] Create Form UI
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormViewModel.kt
  WooCommerce/src/main/res/color/button_colored_bg_purple_selector.xml
  WooCommerce/src/main/res/layout/activity_support_request_form.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: support

#8372 TTP: Adds a TPP button to the payments hub
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/res/drawable/ic_baseline_contactless.xml
  WooCommerce/src/main/res/layout/card_reader_hub_list_item.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#8359 Feature/8260 sync onboarding task list
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/onboarding/onboarding_tasks.json
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
  WooCommerce/src/main/res/drawable/ic_onboarding_about_your_store.xml
  WooCommerce/src/main/res/drawable/ic_onboarding_add_product.xml
  WooCommerce/src/main/res/drawable/ic_onboarding_customize_domain.xml
  WooCommerce/src/main/res/drawable/ic_onboarding_launch_store.xml
  WooCommerce/src/main/res/drawable/ic_onboarding_payments_setup.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store onboarding

#8388 TTP: Screen that explains tpp and allows to test a payment m2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt
  WooCommerce/src/main/res/drawable-hdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/navigation/nav_graph_payment_flow.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#8385 Feature/8260 onboarding full screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/OnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/res/layout/fragment_my_store.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store onboarding

#8391 Search in cache first on ProductSelection screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  build.gradle
Labels: type: enhancement, status: do not merge, feature: coupons

#8415 [REST API] Email screen for the Jetpack connection
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/JetpackStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WPComLoginRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/components/JetpackConsent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/dispatcher/JetpackActivationDispatcherFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/dispatcher/JetpackActivationDispatcherViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/start/JetpackActivationStartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_jetpack_activation.xml
  WooCommerce/src/main/res/navigation/nav_graph_jetpack_install.xml
  WooCommerce/src/main/res/navigation/nav_graph_site_picker.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, status: feature-flagged, feature: REST API

#8431 Update the url for onboarding survey
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackSurveyFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: feature: store onboarding
