Repository woocommerce/woocommerce-android, pull requests merged in 2023-04, with the labels that each got.

#8665 [Product Selector] Analytics events update
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_coupons.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/main/res/navigation/nav_graph_product_selector.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModelTest.kt
Labels: feature: product selector

#8653 [Speedy IPP] Cache IPP onboarding result
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/ClearCardReaderDataAction.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingCheckResultCache.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/ClearCardReaderDataActionTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingCheckResultCacheTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: mobile payments, category: performance

#8688 [TTP] change text on ttp button and feedback in the payments hub
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#8726 Update resource name
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: type: bug, feature: mobile payments

#8652 Sort products by popularity business logic
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FlowExtensions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductsMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
  build.gradle
Labels: status: do not merge

#8670 Business logic for sorting products by recently sold
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FlowExtensions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: feature: mobile payments

#8734 Fix crash on More Menu screen when site is not selected
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepositoryTest.kt
Labels: type: bug, feature: free trial

#8693 Fix "clear selection" button behavior
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorScreen.kt
Labels: feature: product selector

#8680 Free Trial: Remove store profile picker from trial flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModelTest.kt
Labels: type: task, feature: free trial

#8725 Free Trial: Make store profiler flow switchable
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModelTest.kt
Labels: type: task, feature: free trial

#8719 feat: set the correct theme during free trial site creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt
Labels: type: task, feature: free trial

#8714 Gift cards in order detail analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: feature: order details, feature: hosted woo support

#8712 Get gift card data
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GiftCardSummary.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/network/giftcard/GiftCardRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/giftcard/GiftCardRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncher.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncherTest.kt
  build.gradle
Labels: feature: order details, feature: hosted woo support

#8684 Display gift cards in order details
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GiftCardSummary.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/network/giftcard/GiftCardRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/giftcard/GiftCardRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailGiftCardListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailGiftCardListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/layout/order_detail_gift_card_list.xml
  WooCommerce/src/main/res/layout/order_detail_gift_card_list_item.xml
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncherTest.kt
  build.gradle
Labels: type: task, status: do not merge, feature: order details, feature: hosted woo support

#8715 Display quantity rules in product details
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRulesMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/fragment_product_quantity_rules.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRulesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/QuantityRulesMapperTest.kt
  build.gradle
Labels: feature: product details, feature: hosted woo support

#8666 [JITM] Refactor jitms so it can be used as plug & play component
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmClickHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
  WooCommerce/src/main/res/layout/fragment_my_store.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
Labels: feature: jitm

#8720 REST API: Clear access tokens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WPComLoginRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailViewModel.kt
Labels: feature: REST API

#8743 Use migrateAddOn on WooCommerce tables
  build.gradle
Labels: type: crash

#8685 UI for popular products
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/ProductSelectorScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductSelectorScreenTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: feature: mobile payments

#8746 Feature/store onboarding viewmodel tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModelTest.kt
Labels: feature: store onboarding

#8550 [Hack week] No more pink buttons
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Buttons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/res/color/button_colored_bg_purple_selector.xml
  WooCommerce/src/main/res/color/button_fg_selector.xml
  WooCommerce/src/main/res/color/color_primary_selector.xml
  WooCommerce/src/main/res/drawable/button_bg_oval_secondary.xml
  WooCommerce/src/main/res/drawable/ic_add.xml
  WooCommerce/src/main/res/drawable/ic_arrow_down.xml
  WooCommerce/src/main/res/drawable/ic_arrow_up.xml
  WooCommerce/src/main/res/drawable/ic_done_secondary.xml
  WooCommerce/src/main/res/drawable/ic_edit_pencil.xml
  WooCommerce/src/main/res/drawable/ic_email.xml
  WooCommerce/src/main/res/drawable/ic_external.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_heart_outline.xml
  WooCommerce/src/main/res/drawable/ic_menu_more_vert.xml
  WooCommerce/src/main/res/drawable/ic_more_menu_reviews.xml
  WooCommerce/src/main/res/drawable/ic_more_menu_store.xml
  WooCommerce/src/main/res/drawable/ic_more_screen_settings.xml
  WooCommerce/src/main/res/drawable/ic_onboarding_task_completed.xml
  WooCommerce/src/main/res/layout/activity_support_request_form.xml
  WooCommerce/src/main/res/layout/feedback_request_card.xml
  WooCommerce/src/main/res/layout/site_picker_item.xml
  WooCommerce/src/main/res/layout/wc_actionable_empty_label.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/main/res/values/styles_login.xml
  WooCommerce/src/main/res/values/themes.xml
Labels: type: enhancement, category: design

#8690 UI for recently sold products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: feature: mobile payments

#8738 Analytics for sort by popularity/recently sold feature
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductSelectorScreenTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_product_selector.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModelTest.kt
Labels: category: analytics, feature: mobile payments

#8756 Sort by popularity and last sold feature
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/ProductSelectorScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductSelectorScreenTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FlowExtensions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductsMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_product_selector.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationSelectorViewModelTest.kt
Labels: feature: mobile payments

#8752 Subscription review issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/SubscriptionProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailSubscriptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSubscriptionFragment.kt
  WooCommerce/src/main/res/layout/fragment_product_subscription.xml
  WooCommerce/src/main/res/layout/order_detail_subscription_list_item.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: bug

#8739 Free Trial: Introduce store creation summary base view
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/res/drawable-hdpi/free_trial_summary_illustration.png
  WooCommerce/src/main/res/drawable-xhdpi/free_trial_summary_illustration.png
  WooCommerce/src/main/res/drawable-xxhdpi/free_trial_summary_illustration.png
  WooCommerce/src/main/res/drawable-xxxhdpi/free_trial_summary_illustration.png
  WooCommerce/src/main/res/drawable/ic_cloud.xml
  WooCommerce/src/main/res/drawable/ic_gift.xml
  WooCommerce/src/main/res/drawable/ic_globe_2.xml
  WooCommerce/src/main/res/drawable/ic_letter.xml
  WooCommerce/src/main/res/drawable/ic_powered_by.xml
  WooCommerce/src/main/res/drawable/ic_two_persons.xml
  WooCommerce/src/main/res/drawable/ic_update_clock.xml
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: free trial

#8758 Free Trial: Connect summary to store creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModelTest.kt
Labels: type: task, feature: free trial

#8764 Added release notes for 13.1
  CHANGELOG.md
Labels: Releases

#8763 Rename recent to last_sold
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: feature: mobile payments, feature: analytics

#8721 [UI Tests] Added "Orders Search" e2e test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/OrderSearchScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersRealAPI.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersUITest.kt
Labels: category: ui tests

#8761 REST API: Jetpack setup event tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkHandlerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkRequestViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPCom2FAViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPasswordViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPostLoginViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
Labels: feature: analytics, feature: REST API

#8733 [REST API] Check for user role before proceeding with Jetpack activation process
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpOrigin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackActivationEligibilityErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackActivationEligibilityErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackActivationEligibilityErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkHandlerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkRequestViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPCom2FAViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPasswordViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPostLoginViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_jetpack_install.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: REST API

#8767 Merge release/13.0 into trunk (`final`)
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/SubscriptionProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailSubscriptionListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSubscriptionFragment.kt
  WooCommerce/src/main/res/layout/fragment_product_subscription.xml
  WooCommerce/src/main/res/layout/order_detail_subscription_list_item.xml
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  fastlane/metadata/android/ar/changelogs/398.txt
  fastlane/metadata/android/ar/changelogs/400.txt
  fastlane/metadata/android/de-DE/changelogs/398.txt
  fastlane/metadata/android/de-DE/changelogs/400.txt
  fastlane/metadata/android/en-US/changelogs/398.txt
  fastlane/metadata/android/en-US/changelogs/400.txt
  fastlane/metadata/android/es-ES/changelogs/398.txt
  fastlane/metadata/android/es-ES/changelogs/400.txt
  fastlane/metadata/android/fr-FR/changelogs/398.txt
  fastlane/metadata/android/fr-FR/changelogs/400.txt
  fastlane/metadata/android/id/changelogs/398.txt
  fastlane/metadata/android/id/changelogs/400.txt
  fastlane/metadata/android/it-IT/changelogs/398.txt
  fastlane/metadata/android/it-IT/changelogs/400.txt
  fastlane/metadata/android/iw-IL/changelogs/398.txt
  fastlane/metadata/android/iw-IL/changelogs/400.txt
  fastlane/metadata/android/ja-JP/changelogs/398.txt
  fastlane/metadata/android/ja-JP/changelogs/400.txt
  fastlane/metadata/android/ko-KR/changelogs/398.txt
  fastlane/metadata/android/ko-KR/changelogs/400.txt
  fastlane/metadata/android/nl-NL/changelogs/398.txt
  fastlane/metadata/android/nl-NL/changelogs/400.txt
  fastlane/metadata/android/pt-BR/changelogs/398.txt
  fastlane/metadata/android/pt-BR/changelogs/400.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/398.txt
  fastlane/metadata/android/ru-RU/changelogs/400.txt
  fastlane/metadata/android/sv-SE/changelogs/398.txt
  fastlane/metadata/android/sv-SE/changelogs/400.txt
  fastlane/metadata/android/tr-TR/changelogs/398.txt
  fastlane/metadata/android/tr-TR/changelogs/400.txt
  fastlane/metadata/android/zh-CN/changelogs/398.txt
  fastlane/metadata/android/zh-CN/changelogs/400.txt
  fastlane/metadata/android/zh-TW/changelogs/398.txt
  fastlane/metadata/android/zh-TW/changelogs/400.txt
Labels: Releases

#8698 [REST API] Finalize Jetpack activation for application password case and logs user in
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpOrigin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackActivationEligibilityErrorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackActivationEligibilityErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackActivationEligibilityErrorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/JetpackBenefitsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/JetpackActivationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkHandlerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationMagicLinkRequestViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPCom2FAViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComEmailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPasswordViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/wpcom/JetpackActivationWPComPostLoginViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_jetpack_install.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: REST API

#8771 Support log screen crash fix
  WooCommerce/src/main/res/values/colors_base.xml
Labels: type: crash

#8728 Quantity rules analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
Labels: type: task, feature: analytics, feature: hosted woo support

#8772 Merge release/13.1-rc-1 into trunk (`beta`)
  CHANGELOG.md
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/colors_base.xml
  fastlane/resources/values/strings.xml
Labels: Releases

#8703 [JITM] Support flexible jitms so we can promote TTP better
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/promobanner/PromoBanner.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  build.gradle
Labels: feature: mobile payments, feature: jitm

#8774 Quantity rules empty state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: hosted woo support

#8755 Add subscription sales price
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSubscriptionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/res/layout/fragment_product_subscription.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
Labels: type: bug, feature: hosted woo support

#8792 Track onboarding completed only if it was shown at least once
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingRepository.kt
Labels: feature: store onboarding

#8770 [Product Selector] Add support for RTL languages in `WCSearchField`
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
Labels: feature: product selector

#8775 Free Trial: Remove store creation code from Store Name Picker
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModelTest.kt
Labels: type: task, feature: free trial

#8789 Hide popular and Last Sold sections when filter is enabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: feature: mobile payments

#8812 Merge 13.1-rc-2 to trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/WaitingTimeTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationTransactionLauncher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/InstallationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModelTest.kt
Labels: Releases

#8768 [Mobile Payments] With TTP visible, onboarding error hides bottom rows on the payments hub
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewState.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_hub.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModelTest.kt
Labels: feature: mobile payments

#8798 Show variation picker in case of variable subscription
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModelTest.kt
Labels: type: bug

#8776 Free Trial: Remove store creation code from Store Country Picker
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/countrypicker/CountryPickerViewModel.kt
Labels: type: task, feature: free trial

#8782 Free Trial: Adjust store creation use case
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModelTest.kt
Labels: type: task, feature: free trial

#8794 Free Trial: Add store creation error dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryFragment.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: bug, feature: free trial

#8806 Display bundle products from product table
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/BundledProduct.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetBundledProducts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetBundledProductsCount.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductBundleFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductBundleViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/RefreshBundledProducts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/BundleProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/BundleProductViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/bundled_product_item_view.xml
  WooCommerce/src/main/res/layout/fragment_bundle_product_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetBundledProductsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/RefreshBundledProductsTest.kt
  build.gradle
Labels: feature: product details, feature: hosted woo support

#8807 Bundled products analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
Labels: feature: analytics, feature: hosted woo support

#8793 [UI Tests] Added Stats UI tests.
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-hour.json
  WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc-analytics/reports_revenue_stats-month.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-day.json
  WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_visits-month.json
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/DataClasses.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/MocksReader.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/mystore/MyStoreScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/mystore/StatsComponent.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/StatsUITest.kt
Labels: category: ui tests

#8821 Added release notes for 13.2
  CHANGELOG.md
Labels: Releases

#8829 Merge 13.1 final into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/400.txt
  fastlane/metadata/android/ar/changelogs/403.txt
  fastlane/metadata/android/de-DE/changelogs/400.txt
  fastlane/metadata/android/de-DE/changelogs/403.txt
  fastlane/metadata/android/en-US/changelogs/400.txt
  fastlane/metadata/android/en-US/changelogs/403.txt
  fastlane/metadata/android/es-ES/changelogs/400.txt
  fastlane/metadata/android/es-ES/changelogs/403.txt
  fastlane/metadata/android/fr-FR/changelogs/400.txt
  fastlane/metadata/android/fr-FR/changelogs/403.txt
  fastlane/metadata/android/id/changelogs/400.txt
  fastlane/metadata/android/id/changelogs/403.txt
  fastlane/metadata/android/it-IT/changelogs/400.txt
  fastlane/metadata/android/it-IT/changelogs/403.txt
  fastlane/metadata/android/iw-IL/changelogs/400.txt
  fastlane/metadata/android/iw-IL/changelogs/403.txt
  fastlane/metadata/android/ja-JP/changelogs/400.txt
  fastlane/metadata/android/ja-JP/changelogs/403.txt
  fastlane/metadata/android/ko-KR/changelogs/400.txt
  fastlane/metadata/android/ko-KR/changelogs/403.txt
  fastlane/metadata/android/nl-NL/changelogs/400.txt
  fastlane/metadata/android/nl-NL/changelogs/403.txt
  fastlane/metadata/android/pt-BR/changelogs/400.txt
  fastlane/metadata/android/pt-BR/changelogs/403.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/400.txt
  fastlane/metadata/android/ru-RU/changelogs/403.txt
  fastlane/metadata/android/sv-SE/changelogs/400.txt
  fastlane/metadata/android/sv-SE/changelogs/403.txt
  fastlane/metadata/android/tr-TR/changelogs/400.txt
  fastlane/metadata/android/tr-TR/changelogs/403.txt
  fastlane/metadata/android/zh-CN/changelogs/400.txt
  fastlane/metadata/android/zh-CN/changelogs/403.txt
  fastlane/metadata/android/zh-TW/changelogs/400.txt
  fastlane/metadata/android/zh-TW/changelogs/403.txt
Labels: Releases

#8808 Free Trial: Redesign app menu to use row button sections
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MenuUiButton.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: type: task, feature: free trial

#8831 Merge 13.2 code freeze into trunk
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#8801 [JITM] Support modal jitms
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmModal.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/Banner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/banner/BannerState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/promobanner/PromoBanner.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
Labels: feature: jitm

#8835 [UI Tests] Update `Reviews` UI test to account for redesigned Hub Menu.
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/moremenu/MoreMenuScreen.kt
Labels: category: ui tests

#8840 Release analytics survey
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: analytics

#8799 Feature/8747 store creation loading improvements
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreCreationLoadingTimer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/res/drawable-xhdpi/store_creation_loading_image_bottom_start.webp
  WooCommerce/src/main/res/drawable-xhdpi/store_creation_loading_image_top_end.webp
  WooCommerce/src/main/res/drawable-xxhdpi/store_creation_loading_image_bottom_start.webp
  WooCommerce/src/main/res/drawable-xxhdpi/store_creation_loading_image_top_end.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/store_creation_loading_image_bottom_start.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/store_creation_loading_image_top_end.webp
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/InstallationViewModelTest.kt
Labels: type: enhancement, feature: store creation

#8844 Fix the new icon colors in More menu screen
  WooCommerce/src/main/res/drawable/ic_more_menu_upgrades.xml
  WooCommerce/src/main/res/drawable/ic_more_screen_settings.xml
Labels: feature: more menu

#8819 Fix Login Prologue UI issues
  WooCommerce/src/main/res/layout/fragment_login_prologue.xml
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: bug, feature: login

#8830 Free Trial: Add missing redesign for More menu header
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
Labels: type: task, feature: free trial

#8813 Display composite products
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Component.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ComponentMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ComponentListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/CompositeProductFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetComponentProducts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/ComponentsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/component_item_view.xml
  WooCommerce/src/main/res/layout/fragment_componets_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product details, feature: hosted woo support

#8849 feat: remove WooExpress prefix from upgrades
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesViewModel.kt
Labels: feature: free trial

#8818 Display components details
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetCategoriesByIds.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetComponentOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetProductsByIds.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentDetailsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentDetailsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentOptionsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentsListAdapter.kt
  WooCommerce/src/main/res/layout/component_option_item_view.xml
  WooCommerce/src/main/res/layout/fragment_component_details.xml
  WooCommerce/src/main/res/layout/fragment_component_list.xml
  WooCommerce/src/main/res/layout/skeleton_component_option_list_item.xml
  WooCommerce/src/main/res/layout/skeleton_component_options.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetBundledProductsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetCategoriesByIdsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetComponentOptionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetProductsByIdsTest.kt
Labels: feature: product details, feature: hosted woo support

#8820 Composite products analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
Labels: feature: analytics, feature: hosted woo support

#8836 [TTP] Automatically refund TTP test payments
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/WooCommerceComUTMProviderModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SharePaymentUrl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_payment_flow.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
Labels: feature: mobile payments

#8845 [TTP] Specific tap to pay trial payment customer note
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/simplepayments/SimplePaymentsFragmentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModelTest.kt
  build.gradle
Labels: status: do not merge, feature: mobile payments

#8858 Fix quantity rules detected issues
  WooCommerce/src/main/res/layout/fragment_product_quantity_rules.xml
Labels: type: enhancement, feature: hosted woo support

#8853 Gift card issues
  WooCommerce/src/main/res/layout/order_detail_gift_card_list_item.xml
Labels: type: bug, feature: hosted woo support

#8832 Store Creation: Reintroduce store profiler steps and send info during free trial creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/NewStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/plans/networking/SitePlanRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/CreateFreeTrialStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModelTest.kt
Labels: feature: store creation

#8538 Hack week: Update target SDK from 31 to 33
  WooCommerce/build.gradle
  WooCommerce/src/debug/AndroidManifest.xml
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerSetupFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/NotificationsPermissionBar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt
  WooCommerce/src/main/res/drawable/ic_megaphone.xml
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/main/res/layout/fragment_my_store.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  libs/cardreader/build.gradle
  libs/cardreader/src/main/AndroidManifest.xml
  libs/iap/build.gradle
  libs/iap/src/main/AndroidManifest.xml
  quicklogin/build.gradle
  quicklogin/src/main/AndroidManifest.xml
  settings.gradle
Labels: type: technical debt

#8847 Mark "Launch Store" onboarding task as complete when site is public
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingRepository.kt
Labels: type: bug, feature: store onboarding

#8855 Release composite products
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: hosted woo support

#8848 Store creation: Update list of industries and tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/mystoresummary/MyStoreSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/ProfilerOptionsModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerIndustriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/plans/networking/SitePlanRestClient.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: store creation

#8857 Free Trial: Introduce More menu header badge
  WooCommerce/src/androidTest/assets/mocks/mappings/sites/site_plans.json
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/plans/domain/SitePlan.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/plans/trial/TrialStatusBarFormatter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesViewModel.kt
  WooCommerce/src/main/res/layout/activity_main.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/upgrades/UpgradesViewModelTest.kt
Labels: type: task, feature: free trial

#8864 Save store phone number for shipping labels
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModelTest.kt
Labels: feature: shipping labels

#8852 Store creation: Add tracking for Skip button clicks and finalize feature release
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/BaseStoreProfilerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerCommerceJourneyViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerEcommercePlatformsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/profiler/StoreProfilerIndustriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: store creation

#8860 Free Trial: Handle non jetpack sites in More menu header
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
Labels: type: task, feature: free trial

#8866 Added release notes for 13.3
  CHANGELOG.md
Labels: Releases

#8802 [REST API] Remove the need for cookie+nonce authentication for Jetpack activation process in REST API login flow.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/WebView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/JetpackActivationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
Labels: feature: REST API

#8873 Free Trial: Fix More menu drop down arrow visibility issue
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
Labels: type: bug, feature: free trial

#8502 [Hackweek] Partial height chrome tab
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ChromeCustomTabUtils.kt
Labels: status: do not merge, category: design

#8876 Fix/handle store installation retries
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreInstallationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreInstallationLoadingTimer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreInstallationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/StoreInstallationViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/StoreInstallationViewModelTest.kt
Labels: feature: store creation

#8871 Feature/8861 new signup flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/TextExts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginEmailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/overrides/WooLoginEmailPasswordFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpCredentialsValidator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpStepScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpViewModel.kt
  WooCommerce/src/main/res/layout/fragment_login_email_screen.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/signup/SignUpRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/signup/SignUpViewModelTest.kt
Labels: feature: login, feature: store creation

#8877 Pop the back-stack before opening an order detail
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: type: bug, feature: notifications

#8879 Free Trial: Adjust Summary back button
  WooCommerce/src/main/res/navigation/nav_graph_store_creation_native.xml
Labels: type: bug, feature: free trial

#8885 Remove AD_ID permission from merged Manifest
  WooCommerce/src/main/AndroidManifest.xml
Labels: type: bug

#8880 Merge 13.3 code freeze into trunk
  WooCommerce/build.gradle
  WooCommerce/metadata/PlayStoreStrings.pot
  WooCommerce/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#8875 [IPP] Track error type and error description in the human readable way
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/CapturePaymentResponseMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentErrorMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderTrackerTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderStore.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
Labels: feature: mobile payments

#8841 Revert FAB animation behavior
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
Labels: type: bug, feature: order list, feature: product list

#8850 [TTP] Add successful refund notification after TTP test payment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SharePaymentUrl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_payment_flow.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModelTest.kt
Labels: feature: mobile payments

#8896 Order creation: Remove product status filter option
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_product_filters.xml
  WooCommerce/src/main/res/navigation/nav_graph_product_selector.xml
Labels: type: enhancement, feature: order creation

#8899 Update bottom nav selected tab color to primary color
  WooCommerce/src/main/res/color/button_toggle_fg_selector.xml
Labels: type: enhancement

#8903 Fix a product filter crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductFilterListViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
Labels: type: crash

#8897 Feature/8791 sitepicker navigation improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt
Labels: type: enhancement, feature: login

#8868 feat: close upgrade flow if user is not in trial
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/dispatcher/PlanUpgradeStartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/dispatcher/PlanUpgradeStartViewModelTest.kt
Labels: feature: free trial

#8901 Update Kotlin Version
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
  build.gradle
  settings.gradle
Labels: dependency update

#8911 [Signup] Set minimum password length to 6
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpCredentialsValidator.kt
Labels: type: bug, feature: store creation

#8906 Configure Dependabot to ignore AGP plugins
  .github/dependabot.yml
Labels: category: tooling

#8907 Enable hiding and showing onboarding list on demand
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/ShouldShowOnboarding.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsContract.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsPresenter.kt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModelTest.kt
Labels: feature: store onboarding

#8912 Updated release notes for 13.4
  CHANGELOG.md
Labels: Releases

#8919 Merge 13.3 finalization into trunk
  WooCommerce/build.gradle
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/405.txt
  fastlane/metadata/android/ar/changelogs/408.txt
  fastlane/metadata/android/de-DE/changelogs/405.txt
  fastlane/metadata/android/de-DE/changelogs/408.txt
  fastlane/metadata/android/en-US/changelogs/405.txt
  fastlane/metadata/android/en-US/changelogs/408.txt
  fastlane/metadata/android/es-ES/changelogs/405.txt
  fastlane/metadata/android/es-ES/changelogs/408.txt
  fastlane/metadata/android/fr-FR/changelogs/405.txt
  fastlane/metadata/android/fr-FR/changelogs/408.txt
  fastlane/metadata/android/id/changelogs/405.txt
  fastlane/metadata/android/id/changelogs/408.txt
  fastlane/metadata/android/it-IT/changelogs/405.txt
  fastlane/metadata/android/it-IT/changelogs/408.txt
  fastlane/metadata/android/iw-IL/changelogs/405.txt
  fastlane/metadata/android/iw-IL/changelogs/408.txt
  fastlane/metadata/android/ja-JP/changelogs/405.txt
  fastlane/metadata/android/ja-JP/changelogs/408.txt
  fastlane/metadata/android/ko-KR/changelogs/405.txt
  fastlane/metadata/android/ko-KR/changelogs/408.txt
  fastlane/metadata/android/nl-NL/changelogs/405.txt
  fastlane/metadata/android/nl-NL/changelogs/408.txt
  fastlane/metadata/android/pt-BR/changelogs/405.txt
  fastlane/metadata/android/pt-BR/changelogs/408.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/405.txt
  fastlane/metadata/android/ru-RU/changelogs/408.txt
  fastlane/metadata/android/sv-SE/changelogs/405.txt
  fastlane/metadata/android/sv-SE/changelogs/408.txt
  fastlane/metadata/android/tr-TR/changelogs/405.txt
  fastlane/metadata/android/tr-TR/changelogs/408.txt
  fastlane/metadata/android/zh-CN/changelogs/405.txt
  fastlane/metadata/android/zh-CN/changelogs/408.txt
  fastlane/metadata/android/zh-TW/changelogs/405.txt
  fastlane/metadata/android/zh-TW/changelogs/408.txt
Labels: Releases
