Repository woocommerce/woocommerce-android, pull requests merged in 2024-09, with the labels that each got.

#12472 [Tooling] Fix hotfix pipeline
  .buildkite/release-pipelines/new-hotfix-release.yml
Labels: category: tooling

#12473 Manually update version.properties for 20.1.1
  version.properties
Labels: Releases

#12475 Merge 20.1 into 20.1.1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStoreTest.kt
Labels: Releases

#12477 Merge/release 20.1.1 into 20.2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStoreTest.kt
  version.properties
Labels: Releases

#12481 [Tooling] Fix too-early interpolation of `${VERSION_CODE}` in inline script of `new-hotfix-release`
  .buildkite/release-pipelines/new-hotfix-release.yml
Labels: category: tooling, milestone-not-required

#12416 Issue/12414 custom fields editor
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_custom_fields.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details, feature: product details, unit-tests-exemption

#12468 Update endpoint used to fetch site status after activating Jetpack
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackCPInstallViewModel.kt
  WooCommerce/src/main/res/layout/dialog_jetpack_install_progress.xml
  WooCommerce/src/main/res/layout/dialog_jetpack_install_start.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/styles_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jetpack/JetpackCPInstallViewModelTest.kt
Labels: type: bug, feature: jetpack cp

#12486 [Login] Fix for the "Open Mail" button
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
Labels: type: bug, feature: login

#12488 Fix product filter `NoSuchElementException` crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/filter/FilterListItemUiModelTest.kt
Labels: type: bug, feature: product list

#12471 Fix/12470 display click through rate correctly
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#12423 [Blaze i4] Setting local notification for abandoned campaign
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: notifications, feature: blaze

#12435 [Custom Fields] Use Aztec for editing HTML fields
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditorState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/res/layout/view_aztec.xml
  WooCommerce/src/main/res/layout/view_aztec_outlined.xml
Labels: type: enhancement, feature: order details, compose, unit-tests-exemption

#12451 Issue/12445 budget screen redesign
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Switch.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#12449 [Woo POS] UI changes to the splash screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosCircularLoadingIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12502 [Woo POS] 32dp instead of 24 to determine if gesture navigation enabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
Labels: feature: point of sale

#12510 [HACK Week: Wear app] Update WooCommerce Wear complications icons
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/ComplicationUtils.kt
  WooCommerce-Wear/src/main/res/drawable/img_woo_bubble_monochrome.xml
Labels: type: task, feature: android wear

#12482 [Crash] `IllegalArgumentException` when navigating to Filters in Orders list
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: feature: order list, type: crash

#12514 Issue/12302 show toast undo from review notification
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailViewModelTest.kt
Labels: type: bug, feature: notifications, feature: review details

#12489 Remove duplicate toolbar from package details screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
Labels: type: bug, feature: shipping labels

#12505 Enforce default dollar currency when displaying budget value for Blaze
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModelTest.kt
Labels: feature: blaze

#12478 [Aztec in Compose] Few fixes and improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: enhancement, feature: order details, compose

#12452 [Blaze i4] Logic of abandoned campaign notification
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationScheduler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/BlazeCampaignCreationDispatcher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/AbandonedCampaignReminder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserver.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/BlazeCampaignCreationDispatcherTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserverTest.kt
Labels: type: task, feature: notifications, feature: blaze, unit-tests-exemption

#12512 [Woo POS] UI changes on product info dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosDialogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosExitConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
Labels: type: task, feature: point of sale

#12523 Fix bug where the App Bar and Bottom Nav don't get updated when navigation is interrupted
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: type: bug, category: design

#12535 [Order Tracking] Avoid reseting the carrier value when coming back from another screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
Labels: type: bug, feature: order creation

#12537 [Order Tracking] Remove duplicated toolbar in carriers list
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListFragment.kt
Labels: type: bug, feature: order creation

#12522 [Woo POS] Checkout screen UI adjustments #1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosLazyColumn.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#12499 [Google Listings & Ads] Add support for picking local images from the WebView
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/WPComWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/ModalStatusBarBottomSheetLayout.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/WebChromeClientWithImageChooser.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/web/ComposeWebChromeClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/web/WebView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/connection/JetpackActivationWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/applicationpassword/ApplicationPasswordTutorialScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/onboarding/aboutyourstore/AboutYourStoreScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/onboarding/launchstore/LaunchStoreScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/onboarding/payments/GetPaidScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainPurchaseScreen.kt
Labels: type: enhancement, unit-tests-exemption

#12450 [Tooling] Add Release Publishing automation
  .buildkite/release-pipelines/publish-release.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: category: tooling

#12544 Fix the pagination jumping
  build.gradle
Labels: type: bug, feature: order list

#12545 Fix pagination load more
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/ShouldUpdateOrdersList.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/list/ShouldUpdateOrdersListByStoreIdTest.kt
  build.gradle
Labels: type: bug, feature: order list

#12530 Fix of the theoretical race condition in case of multiple calls to JITM cache
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmStoreInMemoryCache.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/jitm/JitmStoreInMemoryCacheTest.kt
Labels: type: crash

#12524 Ensures budget label doesn't get cut off in smaller screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExtensionsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModelTest.kt
Labels: type: bug, feature: blaze

#12551 Bump fluxc
  build.gradle
Labels: Releases

#12552 Update release notes for version 20.3
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12554 Fix Stackoverflow crash
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExtensionsWrapper.kt
Labels: type: crash, feature: My Store screen

#12467 [Woo POS] WooPosCardReaderActivity blocking the app when reader connection flow canceled with back-press
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
Labels: type: bug, feature: point of sale

#12511 [HACK Week: Wear app] Introduce Store Order Totals complication
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/ordertotals/FetchTodayOrderTotals.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/ordertotals/OrderTotalsComplicationService.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/shortcut/AppShortcutComplicationService.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/di/AppConfigModule.kt
  WooCommerce-Wear/src/main/res/values/strings.xml
Labels: type: task, unit-tests-exemption, feature: android wear

#12493 [Bug] Order creation screen freezes after adding products
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CreateOrderItem.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetComponentOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/media/ProductImagesUploadWorkerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreateOrderItemTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetComponentOptionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
Labels: type: bug, feature: order creation

#12567 Only filterable product types in product filter
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListViewModelTest.kt
Labels: type: bug, feature: product list

#12500 [Woo POS] Custom card component to remove simulation of the light source from the top right
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosDialogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosLazyColumn.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
Labels: feature: point of sale

#12533 [HACK Week] Scan tracking number
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingViewModel.kt
  WooCommerce/src/main/res/layout/fragment_add_shipment_tracking.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderShipmentTrackingViewModelTest.kt
Labels: type: task, feature: order details

#12484 [Custom Fields] Handle saving changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_custom_fields.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details, feature: product details, unit-tests-exemption

#12531 Issue/12525 custom field creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_custom_fields.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details, feature: product details

#12515 [Woo POS] Products UI adjustments #2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
Labels: feature: point of sale

#12564 Issue/12539 blaze push notification navigation
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/WooNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  build.gradle
Labels: type: task, feature: blaze

#12584 Custom package with dimensions field
  build.gradle
Labels: type: crash, feature: shipping labels

#12589 [Product Variations] Fix variations not updating in product details
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationListViewModelTest.kt
Labels: type: bug, feature: product details, feature: variation list

#12391 [Order Creation] Introduce Any Variation support to Bundles
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/configuration/ProductConfigurationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/configuration/ProductConfigurationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/configuration/ProductConfigurationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/configuration/ProductRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/picker/VariationPickerViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/picker/VariationPickerViewModelTest.kt
Labels: type: task, feature: order creation, unit-tests-exemption

#12576 Remove duplicate toolbar from package details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
Labels: type: bug, feature: shipping labels

#12546 [Woo POS] Fixes for UI Changes on Exit POS Dialog and Product Info Icon Color Update
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosExitConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: type: task, feature: point of sale

#12581 Fix no campaign reminder shown logic
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
Labels: type: bug, feature: blaze

#12598 Fix/12594 crash on date formatting
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
Labels: type: crash

#12586 Remove site condition from abandoned Blaze campaign reminder
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/AbandonedCampaignReminder.kt
Labels: type: enhancement, feature: blaze

#12602 Wrong package calculation
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModelTest.kt
Labels: type: bug, feature: shipping labels

#12585 Optimize the logic of "no blaze campaign" local notification
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationScheduler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserver.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserverTest.kt
Labels: type: enhancement, feature: blaze

#12566 Issue/12563 delete custom fields
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/OverflowMenu.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details

#12595 [WOO POS] UI changes on the cart screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooAnimUtils.kt
Labels: type: bug, unit-tests-exemption, feature: point of sale

#12603 Fix NoSuchElementException on the site picker screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
Labels: type: crash, feature: login

#12569 [Woo POS] Cannot reconnect to Reader after turning internet off and on
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/WooPosNetworkStatus.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
Labels: type: bug, unit-tests-exemption, feature: point of sale

#12606 Update release notes for 20.4
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12583 [Woo POS] Totals calculation app-side issue
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12612 [Wear] Use black as a background for the Spalsh Screen
  WooCommerce-Wear/src/main/res/values/colors_base.xml
Labels: type: task, feature: android wear

#12543 [Woo POS] Improve Card Reader Payment Flow Error Handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: type: bug

#12600 Send sarif reports to GitHub Code Scanning
  .buildkite/commands/lint.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  WooCommerce/build.gradle
Labels: type: enhancement, category: tooling

#12614 Add unit test for sitepicker loading state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt
Labels: category: unit tests

#12611 [Woo POS] Products and Cart card tops not aligned
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: feature: point of sale

#12610 Issue/11323 new product image picker
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerDialogScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/ProductImagePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/ProductImagePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/ProductImageScreen.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: blaze, unit-tests-exemption

#12579 [Custom Fields] Support for copying key and value
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
Labels: type: enhancement, feature: order details

#12622 [Tooling] Release Publishing fix
  .buildkite/release-builds.yml
  fastlane/Fastfile
Labels: category: tooling

#12621 [Woo POS] UI issues fix with the cart screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosLazyColumn.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt
Labels: feature: point of sale

#12540 Unify the logic of fetching product by SKU
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
Labels: type: bug, type: enhancement

#12631 [Woo POS] Simulate overlay for the connect reader button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
Labels: feature: point of sale

#12582 [Custom Fields] Some fixes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: task, feature: order details

#12605 An attempt to fix a crash in the Dashboard Performance card
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt
Labels: status: do not merge, type: crash, feature: My Store screen

#12615 [Woo POS] Ensure Product Names are Displayed Correctly
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
Labels: feature: point of sale

#12580 Issue/12539 notification type api improvements
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/notifications/NotificationsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/WooNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationAnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/NotificationTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: feature: notifications

#12634 [Wear App] Update Wear app with Play Store review rejection requests
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce-Wear/src/main/res/values/strings.xml
  WooCommerce-Wear/src/main/res/values/styles.xml
Labels: type: task, feature: android wear

#12646 [Notifications] Fix for ConcurrentModificationException while handling notification
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandlerTest.kt
Labels: type: crash, feature: notifications

#12640 Issue/12146 enable for jetpack plugin
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/IsBlazeEnabled.kt
  build.gradle
Labels: feature: blaze

#12616 Campaigns objectives endpoint
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
Labels: type: task, feature: blaze

#12641 [Woo POS] Hide POS mode for ineligible users
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsFeatureFlagEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/IsRemoteFeatureFlagEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/RemoteFeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabledTest.kt
Labels: feature: point of sale

#12649 Release: Update 20.4 with Wear Release notes and Play Store review process changes
  RELEASE-NOTES.txt
  version.properties
Labels: type: task, Releases, feature: android wear

#12652 Release 20.5 release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12557 [Woo POS] Design: Products Screen animation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
Labels: category: design, feature: point of sale

#12663 Bump CI toolkit to 3.7.1
  .buildkite/commands/lint.sh
  .buildkite/shared-pipeline-vars
Labels: type: enhancement, category: tooling

#12675 Make UserAgent a singleton
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/di/AppConfigModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/AppConfigModule.kt
Labels: type: bug

#12601 Issue/12597 custom fields banner
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/ExpandableTopBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details, feature: product details

#12630 [Woo POS] Animated transition to the Get Support screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormActivity.kt
  WooCommerce/src/main/res/anim/woopos_slide_in_left.xml
  WooCommerce/src/main/res/anim/woopos_slide_in_right.xml
  WooCommerce/src/main/res/anim/woopos_slide_out_left.xml
  WooCommerce/src/main/res/anim/woopos_slide_out_right.xml
Labels: feature: point of sale

#12648 Issue/12494 blaze webview fragment
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUrlsHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/detail/BlazeCampaignDetailWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/detail/BlazeCampaignDetailWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/detail/BlazeCampaignDetailWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/detail/BlazeCampaignDetailWebViewViewModelTest.kt
Labels: type: task, feature: blaze, unit-tests-exemption

#12639 [Wear App] Remove NavController injection from all Wear ViewModels
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/MyStoreScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/Navigation.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/FetchSiteData.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/LoginScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/LoginViewModel.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/list/OrdersListScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/list/OrdersListViewModel.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/stats/StoreStatsScreen.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/login/FetchSiteDataTest.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/login/LoginViewModelTest.kt
Labels: type: enhancement, feature: android wear

#12695 [Woo POS] Softer and bigger shadows for the products cards
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: unit-tests-exemption, feature: point of sale

#12698 Dependency tree diff from ci toolkit
  .buildkite/commands/dependency-tree-diff.sh
  .buildkite/pipeline.yml
  WooCommerce/build.gradle
  settings.gradle
Labels: type: enhancement, category: tooling

#12697 Revert UserAgent ANR fix
  RELEASE-NOTES.txt
  build.gradle
Labels: type: bug

#12674 [HACK] Research if CallThrottler can be implemented without assumption on 200ms
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavControllerExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ProductImagesViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: type: enhancement, Tech Debt

#12678 [Bug] Fix weird animation of toolbar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackCompletedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackSurveyFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/hub/PaymentsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/hub/PaymentsHubViewModel.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_detail.xml
  WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
  WooCommerce/src/main/res/layout/fragment_feedback_survey.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/hub/PaymentsHubViewModelTest.kt
Labels: type: bug

#12670 [Custom Fields] HTML toggle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
Labels: type: enhancement, feature: order details, feature: product details

#12710 [Android Wear] Fix Order Details failing to handle Orders with no products
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/OrdersRepository.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/details/FetchOrderProducts.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/orders/details/FetchOrderProductsTest.kt
Labels: type: bug, feature: android wear

#12682 [Custom Fields] Show an entry point in product details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailBottomSheetBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/main/res/drawable/ic_custom_fields.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailBottomSheetBuilderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel_AddFlowTest.kt
Labels: type: enhancement, feature: product details

#12694 [Custom Fields] Update the order details button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomFieldsCard.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/layout/order_detail_custom_fields_card.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: enhancement, feature: order details

#12683 [Order Bundles] Fix never ending loading for Bundles
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/OrderMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationProduct.kt
Labels: type: bug, feature: order creation

#12726 Update 20.6 release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12719 [Woo POS] Change colors for the payment success screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12724 [Bug] Coupons dissapearing from order
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
Labels: type: bug

#12716 [HACK] Remove unused dependency
  WooCommerce/build.gradle
  build.gradle
  libs/cardreader/build.gradle
Labels: Tech Debt

#12717 [Login] Fix issue where Application Passwords disabled screen is not shown
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModelTest.kt
Labels: type: bug, feature: login
