Repository woocommerce/woocommerce-android, pull requests merged in 2024-08, with the labels that each got.

#12162 Woo POS: Simple products info dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/ProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: type: task, feature: point of sale

#12184 Hotfix: Fix broken TTP on Android 14
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  settings.gradle
Labels: feature: mobile payments

#12179 Issue/12141 hide illustration in phone landscape
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderWelcomeDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/WCSettingsToggleOptionView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiHelpers.kt
Labels: feature: mobile payments

#12180 [Contact Support Form] Add Site Address Field
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskTicketRepository.kt
  WooCommerce/src/main/res/layout/activity_support_request_form.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/support/ZendeskTicketRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/support/requests/SupportRequestFormViewModelTest.kt
Labels: type: task, feature: support

#12143 Allow signing in to duplicated Jetpack websites
  RELEASE-NOTES.txt
  build.gradle
Labels: feature: login

#12181 Background tasks analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/BackgroundUpdatesDisabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/OrderNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateDataOnBackgroundWorker.kt
Labels: type: task, category: tracks, unit-tests-exemption

#12177 [Woo POS] Crash when multiple connection flows are started and cancelled
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12202 Fix refresh last update on resume
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: enhancement, feature: order list

#12204 Issue/release background tasks
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, Feature: Background Updates

#12165 [Woo POS] M2: Update UI based on design for success screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12195 Update instructions in release-notes
  RELEASE-NOTES.txt
Labels: category: tooling

#12211 Update release notes copy for 19.8
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: category: releases, type: documentation

#12205 Update PR template to encourage adding unit tests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: category: tooling

#12186 Update Android Material from 1.9.0 to 1.10.0
  RELEASE-NOTES.txt
  build.gradle
Labels: dependency update

#12227 Fix Rerty typo in POS
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12210 [Woo POS] Product list UI improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: feature: point of sale

#12042 Bump AGP to `8.5.1`
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/taxes/OrderTaxesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListAdapter.kt
  libs/cardreader/build.gradle
  libs/commons/build.gradle
  libs/iap/build.gradle
  settings.gradle
Labels: category: tooling

#12229 Update android-core from 1.12.0 to 1.13.1
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/AlignedDividerDecoration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/FlowLayout.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCSelectableTextView.kt
  build.gradle
Labels: dependency update

#12214 [Custom Fields] Align with FluxC storage changes - part 1
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/OrderMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GetProductRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/GetOrderSubscriptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundViewModelTest.kt
  build.gradle
Labels: type: task, feature: order details

#12246 Remove feature flag product creation with AI V2 - M3
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task

#12244 Adds text recognition for Japanese, Korean, and Chinese
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/TextRecognitionEngine.kt
Labels: type: task

#12251 Update ci toolkit to `3.5.1`
  .buildkite/shared-pipeline-vars
Labels: type: enhancement, category: tooling

#12255 Update Ruby Gems
  Gemfile.lock
Labels: category: tooling

#12253 Fix sync last update on background task
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateAnalyticsDataByRangeSelection.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateAnalyticsDataByRangeSelectionTest.kt
Labels: type: bug, type: enhancement

#12230 Update android-lifecycle from 2.6.2 to 2.7.0
  RELEASE-NOTES.txt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModelTest.kt
  build.gradle
Labels: dependency update

#12231 Update androidx-fragment from 1.6.2 to 1.8.2
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
Labels: dependency update

#12237 Update material and transition dependencies
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  build.gradle
Labels: dependency update

#12239 Proper fix for broken TTP - Update Stripe Terminal SDK to 3.7.1
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/TapToPayAvailabilityStatus.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/taptopay/TapToPayAvailabilityStatusTest.kt
  build.gradle
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/RefundParams.kt
  settings.gradle
Labels: dependency update

#12247 [Woo POS] Update scrolling visualisation of the lists shadows
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosLazyColumn.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: feature: point of sale

#12224 [Woo POS] M2: Implement payment success screen as per design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
Labels: feature: point of sale

#12228 [Woo POS] Use in memory cache for products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceTest.kt
Labels: feature: point of sale

#12215 Remove retaining the version 16.4 in the release process
  fastlane/Fastfile
Labels: type: task, Releases

#12232 [Woo POS] Return to POS right after payment success
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
Labels: feature: point of sale

#12235 Add subtotal and taxes fields to each refund item
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/RefundsExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/res/layout/refund_by_items_products.xml
  WooCommerce/src/main/res/layout/refunds_product_list_item.xml
Labels: type: enhancement, feature: refunds

#12257 [Wear App] Fix Google Analytics CTA placement in Analytics Hub
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/res/layout/analytics_call_to_action_view.xml
  WooCommerce/src/main/res/layout/analytics_custom_selection_card_view.xml
  WooCommerce/src/main/res/layout/fragment_analytics.xml
Labels: type: task, feature: analytics, unit-tests-exemption

#12226 [WOO POS]M2: Change close icon colour in Product info dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
Labels: type: bug, feature: point of sale

#12218 [WOO POS]M2: Prevent Multiple Instances of Card Reader Connect Dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
Labels: type: bug, feature: point of sale

#12272 [Woo POS] Transition back from the success screen to the products is not ideal
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
Labels: feature: point of sale

#12276 Update FluxC version
  build.gradle
Labels: type: task, category: tooling

#12277 Update changelogs for 19.9 release
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: category: releases, Releases

#12279 Add more named block arguments usages in `Fastfile`
  fastlane/Fastfile
Labels: category: tooling

#12190 [Woo POS] Fix for broken Home screen state after Activity death.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: feature: point of sale

#12292 Bring back instrumented tests annotations
  fastlane/Fastfile
Labels: type: enhancement, category: ui tests

#12263 [Bug] Disallow applying coupons and discounts together
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreateEditViewModelTest.kt
Labels: feature: coupons, feature: order creation, feature: order editing

#12295 Unit tests merge improvements
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  merge_junit.sh
Labels: type: enhancement, category: unit tests

#12300 [Woo POS] Make bottom navigation bar transparent when its gesture based and keep it as it is in button based
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
Labels: feature: point of sale

#12309 [Woo POS] Polish transition between splash and home screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashScreen.kt
Labels: feature: point of sale

#12311 Product Creation with AI: Fix the visibility of “Write with AI” button
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/description/AIProductDescriptionBottomSheetFragment.kt
  WooCommerce/src/main/res/values/styles_base.xml
Labels: type: bug, feature: product details

#12306 [Login] Fix "send SMS" button during 2FA login
  RELEASE-NOTES.txt
  build.gradle
Labels: type: bug, priority: high, feature: login

#12233 [Wear App] Introduce sentry to wear
  WooCommerce-Wear/build.gradle
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/crashlogging/FluxCCrashLoggerImpl.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/crashlogging/WCWearCrashLoggingDataProvider.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/di/CrashLoggingModule.kt
Labels: type: enhancement, unit-tests-exemption, feature: android wear

#12280 [Wear App] Introduce app settings sync with phone
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/crashlogging/WCWearCrashLoggingDataProvider.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/phone/PhoneConnectionRepository.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/settings/AppSettings.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/settings/SettingsRepository.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/crashlogging/WCWearCrashLoggingDataProviderTest.kt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/FeedbackPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/wear/WearableConnectionRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/wear/WearableConnectionService.kt
  libs/commons/src/main/java/com/woocommerce/commons/Paths.kt
  libs/commons/src/main/java/com/woocommerce/commons/WearSharedModels.kt
  libs/commons/src/main/java/com/woocommerce/commons/prefs/PreferenceUtils.kt
Labels: type: task, unit-tests-exemption, feature: android wear

#12317 [Woo POS] 24dp as cut off for determining the gesture way of navigation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
Labels: feature: point of sale

#12193 [Woo POS] M2: Update total's design
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12303 Remove QR code scanning CTA from login flow
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginMagicLinkSentImprovedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/qrcode/QrCodeLoginListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/qrcode/ValidateScannedValue.kt
  WooCommerce/src/main/res/layout/fragment_login_magic_link_sent_improved.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: category: tracks, feature: login, unit-tests-exemption

#12258 [Woo POS] M2: Fix Pagination Issue on Pull-to-Refresh in POS Mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
Labels: type: bug, feature: point of sale

#12256 Fix last update with failed source
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/domain/ObserveLastUpdate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt
Labels: type: bug, Feature: Background Updates

#12329 [UI Tests] Address Emulator slowness.
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/reviews/ReviewsListScreen.kt
Labels: category: ui tests

#12323 Update PR Template according to best practices
  .github/PULL_REQUEST_TEMPLATE.md
Labels: category: tooling

#12274 [Woo POS] [Bug] No pictures shown in card reader tutorial
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt
Labels: feature: point of sale

#12327 Add new suspended status to Blaze campaigns
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiModels.kt
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: blaze

#12252 [Custom Fields] Metadata refactor - part 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GetProductRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
  build.gradle
Labels: type: task, feature: order details, feature: product details

#12313 [Wear App] Initialize and activate crashlogging on wear
  .configure
  .configure-files/gradle.properties.enc
  WooCommerce-Wear/build.gradle
  WooCommerce-Wear/src/main/java/com/woocommerce/android/app/WooCommerceWear.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/crashlogging/WCWearCrashLoggingDataProvider.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/settings/AppSettings.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/settings/SettingsRepository.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/FetchSiteData.kt
  gradle.properties-example
Labels: type: task, feature: android wear

#12320 [Woo POS] Analytics – part 1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsTracker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsEventTrackerTest.kt
Labels: feature: analytics, feature: point of sale

#12319 [Login] Fix to make sure SMS OTP is triggered automatically
  RELEASE-NOTES.txt
  build.gradle
Labels: type: bug, feature: login

#12349 Allow collecting payment for failed order
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentCollectibilityChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentCollectibilityCheckerTest.kt
Labels: feature: mobile payments

#12332 [Woo POS] M2: Improve accessibility talkback
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: category: accessibility, feature: point of sale

#12353 Update Release Notes with Wear changes
  RELEASE-NOTES.txt
Labels: type: task, feature: android wear

#12354 Fix low stock in filter options
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/filter/ProductFilterListViewModel.kt
  build.gradle
Labels: type: bug, feature: product list

#12358 [Release] Update 20.0 Release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/wear/en-US/changelogs/default.txt
Labels: Releases

#12310 [Woo POS] Open Zendesk support form from toolbar
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpOrigin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/support/WooPosGetSupportFacade.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
Labels: feature: point of sale

#12271 [Woo POS] Error screens UI updates
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooPosErrorScreenTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_error.xml
Labels: feature: point of sale

#12351 [Woo POS] Products background has incorrect color screen. The totals has rounded corners instead of being flat
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
Labels: feature: point of sale

#12337 Resolve `androidx.navigation.safeargs.kotlin` in root module
  build.gradle
Labels: type: enhancement

#12316 Bump Aztec to `2.1.4`
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCBottomSheetDialogFragment.kt
  build.gradle
Labels: Tech Debt

#12347 [Woo POS] Dark mode improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
Labels: feature: point of sale

#12293 [WOO POS] M2: Refactor process death handling logic for Product info dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
Labels: type: technical debt

#12267 [Woo POS] M2: Update POS Exit Dialog to New Design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosExitConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: point of sale

#12380 Some clarifications on the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation

#12330 [Mobile Payments] Add support for pending_verification account status
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
Labels: feature: point of sale

#12384 Allow private products in order creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductRestrictions.kt
Labels: type: task, feature: order creation

#12238 [WOO POS]M2: Filter Simple Products for POS Display
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: type: task, feature: point of sale

#12371 [Woo POS] Fix for app crashing in payment flow on config change
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderMode.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt
Labels: feature: point of sale

#12352 [Woo POS] Appearance animation of the products in the cart
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#12336 [Blaze i4] Setting local notification for no campaign during 30 days
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUrlsHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: notifications, feature: blaze

#12219 Adds support to display Blaze push notfication status updates correctly
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/WooNotificationType.kt
  build.gradle
Labels: feature: blaze, unit-tests-exemption

#12374 [Blaze i4] Logic of blaze reminder notification
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationScheduler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserver.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserverTest.kt
Labels: type: task, feature: notifications, feature: blaze

#12383 [Bug] LearnMore in Payments is cut-off
  WooCommerce/src/main/res/layout/fragment_payments_hub.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: bug

#12372 [Blaze] Fix date formatting for the campaign creation API request
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt
Labels: type: bug, feature: blaze

#12378 [Woo POS] ConcurrentModificationException in WooPosProductsViewModel
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceTest.kt
Labels: type: bug, feature: point of sale

#12382 Fix crashes on navigation events in order creation screens
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
Labels: type: crash, feature: order editing

#12369 [WOO POS] M2: Add Accessibility Labels to Missing UI Components
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/ToolbarAccessibilityLabels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, category: accessibility, feature: point of sale

#12366 [Product AI v2] Remove feature flag and code cleanup
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAISubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/GenerateProductWithAILegacy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductNameSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductNameSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/ai/PackagePhotoViewModelTest.kt
Labels: type: task, category: tracks, feature: product details

#12395 [Woo POS] Products should be added to the top of the cart
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#12361 [Bugfix] Improve Error Handling and Path Validation for Large Image Uploads
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt
Labels: type: crash

#12397 [Woo POS] 12386 Fix for Cart animated overlay not showing
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
Labels: feature: point of sale

#12363 [Custom Fields] Update FluxC to use the new metadata package
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/OrderMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/SubscriptionDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/SubscriptionDetailsMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/GetOrderSubscriptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
  build.gradle
Labels: type: task

#12400 [Woo POS] Align Products and Cart toolbars sizes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosLazyColumn.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
Labels: feature: point of sale

#12404 Fix sku ellipsize
  WooCommerce/src/main/res/layout/order_detail_product_child_item.xml
  WooCommerce/src/main/res/layout/order_detail_product_item.xml
Labels: type: enhancement, feature: order details

#12405 Check changes before exiting
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailsToolbarHelper.kt
Labels: type: enhancement, feature: product details

#12375 [Mobile Payments] Handle incorrect pin error for UK and Canadian stores during IPP
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentErrorMapperTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: type: bug, feature: mobile payments

#12362 [Woo POS] Disconnect from a reader if readers button clicked when its connected
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12381 Log a case when order and store currencies mismatch
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodCurrencyMissMatchLog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLogWrapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodCurrencyMissMatchLogTest.kt
Labels: feature: mobile payments

#12387 [Bug] Fix for Orders screen stuck at skeleton loading view
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: feature: order details, feature: order list

#12402 Blaze budget screen scroll issues
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
Labels: type: bug, feature: blaze

#12265 [Tooling] Release-on-CI automation improvements
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  fastlane/Fastfile
Labels: category: tooling

#12410 Update for release of beta
  CHANGELOG.md
  build.gradle
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12408 [Woo POS] Remove custom text style. Extract overlay into reusable base in product info dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosBackgroundOverlay.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosDialogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosExitConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeProductInfoDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
Labels: feature: point of sale

#12421 [Edit Orders] Show a back button in the Order Edit Screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
Labels: type: bug, feature: order creation

#12415 Fix for payment selection screen shown after successful payment
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
Labels: feature: order creation

#12427 Remove unused Feature Flags from past Eagle projects
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetAnalyticPluginsCardActive.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: enhancement

#12406 Issue/12365 custom fields list
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsViewModelTest.kt
Labels: type: enhancement, feature: order details

#12324 Issue/12248 evergreen campaign support
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/ranges/StatsTimeRangeSelectionTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModelTests.kt
Labels: feature: blaze, unit-tests-exemption

#12424 [Tooling] Report an error when no milestone is set to a PR
  Dangerfile
  Gemfile.lock
  fastlane/Fastfile
Labels: category: tooling

#12403 [Woo POS] We end up in inconsistent state after failed payments flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: type: bug, feature: point of sale

#12417 [Stats Widget] Handle widget battery saver mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/IsDeviceBatterySaverActive.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/GetWidgetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/UpdateTodayStatsWorker.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/appwidgets/IsDeviceBatterySaverActiveTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/appwidgets/stats/GetWidgetStatsTest.kt
Labels: type: task, feature: Widgets

#12433 Update campaign list to support Evergreen campaigns and display CTR
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserver.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/BlazeRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserverTest.kt
  build.gradle
Labels: feature: blaze

#12447 Evergreen campaign support tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
Labels: category: tracks, feature: blaze

#12454 Issue/12453 enable evergreen campaigns feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: blaze

#12455 Add revamp shipping labels feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: shipping labels

#12436 [Beta Fix] Fix navigation for "Collect payment" tap in order creation flow
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
Labels: feature: order creation

#12463 Update release notes for v20.2
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: category: releases, Releases

#12466 Fix last update always empty
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStoreTest.kt
Labels: type: crash
