Repository woocommerce/woocommerce-android, pull requests merged in 2024-07, with the labels that each got.

#11857 Fix the broken table on the documentation page of the Tracking Events
  docs/tracking-events.md
Labels: type: documentation

#11856 Remove a reference to an unused page from README.md
  README.md
Labels: type: documentation

#11863 [Buildkite] Add Agent Attribute with Queue Android to Every YML File
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/schedules/dependency-analysis.yml
Labels: category: tooling

#11839 Track when loading starts and finishes for each of the dashboard cards
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/inbox/DashboardInboxViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt
Labels: category: tracks

#11840 [Woo POS] Correctly Display Sub-Amounts on Totals Screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, unit-tests-exemption, feature: point of sale

#11872 [Tooling] Replace `wear-` prefix with `w` suffix in the release name
  fastlane/Fastfile
Labels: category: tooling

#11820 Play Store Listing: Update for Wear app
  fastlane/Fastfile
  fastlane/metadata/PlayStoreStrings.pot
  fastlane/metadata/android/ar/full_description.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/fr-FR/full_description.txt
  fastlane/metadata/android/id/full_description.txt
  fastlane/metadata/android/it-IT/full_description.txt
  fastlane/metadata/android/iw-IL/full_description.txt
  fastlane/metadata/android/ja-JP/full_description.txt
  fastlane/metadata/android/ko-KR/full_description.txt
  fastlane/metadata/android/nl-NL/full_description.txt
  fastlane/metadata/android/pt-BR/full_description.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/full_description.txt
  fastlane/metadata/android/sv-SE/full_description.txt
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/zh-CN/full_description.txt
  fastlane/metadata/android/zh-TW/full_description.txt
Labels: category: tooling, category: releases

#11874 Merge 19.3 Code Freeze to trunk
  fastlane/Fastfile
  fastlane/metadata/PlayStoreStrings.pot
  fastlane/metadata/android/ar/full_description.txt
  fastlane/metadata/android/de-DE/full_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/fr-FR/full_description.txt
  fastlane/metadata/android/id/full_description.txt
  fastlane/metadata/android/it-IT/full_description.txt
  fastlane/metadata/android/iw-IL/full_description.txt
  fastlane/metadata/android/ja-JP/full_description.txt
  fastlane/metadata/android/ko-KR/full_description.txt
  fastlane/metadata/android/nl-NL/full_description.txt
  fastlane/metadata/android/pt-BR/full_description.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/full_description.txt
  fastlane/metadata/android/sv-SE/full_description.txt
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/zh-CN/full_description.txt
  fastlane/metadata/android/zh-TW/full_description.txt
Labels: Releases

#11864 Issue/product creation ai i2 feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductInformationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductInformationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product list

#11876 11844 remove test error snackbars
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/snackbar/WooPosSnackbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/snackbar/WooPosSnackbarState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
Labels: feature: point of sale

#11882 [Tooling] Use a shared Buildkite pipeline vars file
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/schedules/dependency-analysis.yml
  .buildkite/shared-pipeline-vars
Labels: category: tooling

#11888 [Wear App] Improve stats screen big text handling
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/stats/StoreStatsScreen.kt
Labels: type: enhancement, feature: android wear

#11891 [Wear App] Add missing Wear app release notes
  fastlane/metadata/PlayStoreStrings.pot
  fastlane/metadata/wear/en-US/changelogs/default.txt
Labels: type: task, Releases

#11893 [Tooling] Use Android Queue by default
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/schedules/dependency-analysis.yml
Labels: category: tooling

#11846 Update bottom toolbar UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/res/drawable/woopos_ic_exit_pos.xml
  WooCommerce/src/main/res/drawable/woopos_ic_reader_disconnected.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#11865 Removes dynamic dashboard M2 feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/DashboardWidget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: My Store screen

#11887 [Woo POS] Rename strings we use for POS to make them consistent
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: Tech Debt, feature: point of sale

#11866 [Woo POS] Empty/half hidden cart state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
Labels: unit-tests-exemption, feature: point of sale

#11905 [Wear App] Adjust orders list to Play Store requirements
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/list/OrdersListScreen.kt
Labels: type: enhancement, feature: android wear

#11789 Remove separate `RELEASE-NOTES-WEAR.txt` file for Wear app
  RELEASE-NOTES-WEAR.txt
  RELEASE-NOTES.txt
  fastlane/Fastfile
Labels: category: tooling

#11778 Bump Gradle wrapper to 8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: category: tooling

#11879 [Woo POS] Hide cart when payment succeed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
Labels: unit-tests-exemption, feature: point of sale

#11900 Enable Inbox Notes
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxUtils.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: enhancement, feature: inbox

#11920 [Wear App] Adjust orders details to play store
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/compose/theme/WooTypography.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/details/OrderDetailsScreen.kt
Labels: type: enhancement, feature: android wear

#11898 Issue/11878 new promt screen UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductInformationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_camera_primary.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_double_chevron.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, unit-tests-exemption

#11924 Update changelog 19.4
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#11907 Issue/11899 new image selector
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, unit-tests-exemption

#11885 [Woo POS] Empty state for products
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: feature: point of sale

#11825 [Hackweek] Customer more menu
  build.gradle
Labels: type: enhancement, category: tracks, feature: more menu, unit-tests-exemption

#11890 [Wear App] Fix wear dependencies
  WooCommerce-Wear/build.gradle
  build.gradle
Labels: type: task, feature: android wear

#11947 Fix widget size
  WooCommerce/src/main/res/values/dimens_base.xml
Labels: type: bug, feature: Widgets

#11950 Use `dependency-submission@v3`
  .github/workflows/dependabot.yml
Labels: category: tooling

#11935 Support Themed App Icons
  RELEASE-NOTES.txt
  WooCommerce/src/jalapeno/res/mipmap-anydpi-v26/ic_launcher.xml
  WooCommerce/src/jalapeno/res/mipmap-anydpi-v26/ic_launcher_round.xml
  WooCommerce/src/main/res/drawable/ic_launcher_background.xml
  WooCommerce/src/main/res/drawable/ic_launcher_foreground.xml
  WooCommerce/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  WooCommerce/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  WooCommerce/src/wasabi/res/drawable/ic_launcher_foreground.xml
  WooCommerce/src/wasabi/res/mipmap-anydpi-v26/ic_launcher.xml
  WooCommerce/src/wasabi/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: type: enhancement, category: design

#11951 Address WireMock security vulnerabilities
  .github/dependabot.yml
  WooCommerce/build.gradle
Labels: category: ui tests

#11925 Issue/11909 scan image and fill text
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/TextRecognitionEngine.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product details, unit-tests-exemption

#11829 Add new step to run UI Tests on tablet emulator
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/pipeline.yml
  .configure
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/moremenu/MoreMenuScreen.kt
  fastlane/Fastfile
Labels: category: ui tests

#11962 Remove WireMock duplication from Dependabot ignore config
  .github/dependabot.yml
Labels: category: tooling

#11877 [Google for Woo] Hub Menu functionality part 1
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/GoogleRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/HasGoogleAdsCampaigns.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/IsGoogleForWooEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/IsGoogleListingsAdsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: feature: more menu, unit-tests-exemption

#11918 [Google for Woo] Custom Webview that can detect success URL
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/exitawarewebview/ExitAwareWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/exitawarewebview/ExitAwareWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/exitawarewebview/ExitAwareWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/layout/fragment_exitaware_webview.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
Labels: unit-tests-exemption

#11952 [Product AI v2 M1] New preview screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Image.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product details, status: feature-flagged, unit-tests-exemption

#11958 Fix analytics cache
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/domain/ObserveLastUpdate.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/UpdateAnalyticsHubStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/topperformers/GetTopPerformersTest.kt
Labels: type: task, feature: analytics

#11934 [Woo POS] Tests for classes in com.woocommerce.android.ui.woopos.home dir
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartCartRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: Testing, feature: point of sale

#11886 [Tooling] Use a trusted CI agent for pipelines that require push access
  .buildkite/commands/configure-environment.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  Gemfile.lock
Labels: category: tooling

#11971 Clean up shipping lines
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/shipping/OrderCreateEditShippingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/shipping/OrderCreateEditShippingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/shipping/OrderCreateEditShippingViewModelTest.kt
Labels: type: enhancement, feature: order creation

#11975 [Tooling] Cherry pick #11886 (trusted agent for push)
  .buildkite/commands/configure-environment.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  Gemfile.lock
Labels: category: tooling

#11897 [Woo POS] Entry point eligibility conditions improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsFeatureFlagEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsScreenSizeAllowed.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/ext/WooPosContextExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiHelpers.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabledTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11904 [GLA Analytics] Adapt Analytics Hub with new section for the GLA Analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/AnalyticCardConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStat.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetAnalyticPluginsCardActive.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateStates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/layout/analytics_custom_list_card_item_view.xml
  WooCommerce/src/main/res/layout/analytics_custom_selection_card_view.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsRepositoryTest.kt
  build.gradle
Labels: type: task, feature: analytics, unit-tests-exemption

#11965 Dynamic dashboard cards data failure tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/inbox/DashboardInboxViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStatsTest.kt
Labels: category: tracks

#11966 [Google for Woo] Logic to choose which webview to use based on Jetpack connection
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
Labels: feature: more menu

#11940 [Woo POS] Adapt the UI to be usable on smaller devices
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosComposePreviewAnnotation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosSizes.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/ext/WooPosContextExt.kt
Labels: feature: point of sale

#11984 Remove unused navigation-dynamic-features-fragment dependency
  WooCommerce/build.gradle
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentReaderTypeStateProviderTest.kt
Labels: type: enhancement, dependency update

#11970 Update target SDK to Android 14
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  build.gradle
  settings.gradle
Labels: feature: login, dependency update

#11953 [Woo POS] Fix preview of the home screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosComposeIsPreviewMode.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
Labels: feature: point of sale

#11969 [Product AI v2] Photo section in preview + other changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/components/FullScreenImageViewer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/components/SelectedImageSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: product details, status: feature-flagged

#11923 [Woo POS] Move order creation logic from cart to totals
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/data/WooPosGetProductById.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11901 [Woo POS] Products - Pull to refresh
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: feature: point of sale

#11990 [Woo POS] The UI of the pos should be placed under the systems toolbar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
Labels: feature: point of sale

#11961 Update dashboard task
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateAnalyticsDashboardRangeSelections.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateAnalyticsDataByRangeSelection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateDataOnBackgroundWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateAnalyticsDashboardRangeSelectionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateAnalyticsDataByRangeSelectionTest.kt
Labels: type: task, unit-tests-exemption, Feature: Background Updates

#12005 Update 19.5 release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#11979 Use v32 instead of v34 to avoid nuage laboratoire login screen
  .buildkite/pipeline.yml
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/mystore/settings/SettingsScreen.kt
Labels: category: ui tests

#11892 [Woo POS] Small updates to checkout screen per M2 Design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
Labels: feature: point of sale

#11993 [Product AI v2] generation prompt + option selector
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/BuildProductPreviewProperties.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/GenerateProductWithAILegacy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: product details, unit-tests-exemption

#11988 [GLA Analytics] Handle google ads selection
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/PluginUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetAnalyticPluginsCardActive.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/GetAnalyticPluginsCardActiveTest.kt
Labels: type: task, feature: analytics

#11991 [Google for Woo] Dashboard Card UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/DashboardWidget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: My Store screen

#12022 Disable Tablet instrumentation tests
  .buildkite/pipeline.yml
Labels: category: ui tests

#11968 [Woo POS] Add POS entry point asynchronously after the eligibility check completes
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/animations/SkeletonAnimation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuItemSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/drawable/ic_more_menu_pos_extra.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: feature: more menu, unit-tests-exemption, feature: point of sale

#11983 [Woo POS] Handle order creation failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12035 Fix Application Password tracks and presentation rule
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/applicationpassword/ApplicationPasswordTutorialViewModel.kt
Labels: type: task, feature: login

#11982 Issue/11862 product prompt suggestion bar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AiFeedbackForm.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: product details, unit-tests-exemption

#12011 [Product AI v2] Support editing the text fields
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: product details, status: feature-flagged, unit-tests-exemption

#12020 Issue/12004 upload selected photo
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/UploadImage.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product details, unit-tests-exemption

#12048 Fix overflowing SKU text in the Order Creation Flow
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableGroupedProductCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
Labels: feature: order creation

#12010 [Woo POS] M2: Update carts design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_empty_cart.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#12033 [Login] Fix some issues
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  build.gradle
Labels: type: bug, feature: login

#12024 [Product AI v2] Generate Again button + Feedback banner logic
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: product details

#12049 Issue/12021 handle saving product
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/SaveAiGeneratedProduct.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
Labels: feature: product details, unit-tests-exemption

#12053 Adds new feature flag to hide advice box from product prompt screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task

#12029 Integrate UI tests sharding
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/pipeline.yml
  WooCommerce/build.gradle
  fastlane/Fastfile
  settings.gradle
Labels: type: enhancement, category: ui tests

#12061 [Product AI v2] Delete publish button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/SaveAiGeneratedProduct.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product details

#12066 [Product AI v2] Handle saving the AI generation tone
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AiTone.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/GenerateProductWithAILegacy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
Labels: type: enhancement, feature: product details

#12062 [Product AI v2] Tracking + enabling feature
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AiTone.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/GenerateProductWithAILegacy.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: category: tracks, feature: product details

#11976 [Woo POS] Remove usage of BaseUnitTest that comes from the main app
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt
Labels: Testing, feature: point of sale

#12003 Show outdated data
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/data/StatsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStats.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStatsTest.kt
  build.gradle
Labels: type: task, feature: analytics

#12069 Outdated data top performers
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/domain/GetTopPerformers.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/GetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ResultWithOutdatedFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/topperformers/GetTopPerformersTest.kt
Labels: type: enhancement, type: task, feature: analytics

#12055 [GLA Analytics] Complete Google ads card UI mapping and presentation
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStat.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetAnalyticPluginsCardActive.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetReportUrl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListCardItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListCardItemViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsRepository.kt
  WooCommerce/src/main/res/layout/analytics_custom_list_card_item_view.xml
  WooCommerce/src/main/res/layout/analytics_custom_selection_card_view.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: analytics, unit-tests-exemption

#12050 [Woo POS] Correctly show error state at the right time
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12067 Update Payment Method On Cash Payments
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt
  build.gradle
Labels: feature: order creation

#12013 [Google for Woo] Dashboard Card Functionality part I
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/data/DashboardRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/data/ObserveGoogleAdsWidgetStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/CanUseAutoLoginWebview.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/GoogleRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/HasGoogleAdsCampaigns.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: feature: My Store screen, unit-tests-exemption

#12073 [GLA Analytics] Allow tracks name support for analytics cards
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/AnalyticCardConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetReportUrl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
Labels: type: task, feature: analytics

#12084 [GLA Analytics] Release GLA Analytics M1
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: analytics

#12088 Updated fluxc version to a 2.89 tag
  build.gradle
Labels: Releases

#12091 Update fluxc version
  build.gradle
Labels: Releases

#12090 Update release notes
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#12045 [Woo POS] M2: Update the floating toolbar design and add pop up menu
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootFloatingToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreenState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/res/drawable/woopos_ic_get_support.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#12059 Don't ensure screenshot tests build
  .buildkite/pipeline.yml
Labels: category: tooling, category: ui tests

#12107 Ignore failing e2e tests
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/StatsUITest.kt
Labels: type: enhancement, category: ui tests

#12093 [Product AI v2] Undo snackbar when package photo is removed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: product details

#12106 Fix TransactionTooLarge by not saving recoverable state
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
Labels: feature: order details

#12030 [Google for Woo] Dashboard Card Functionality part II (Stats)
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsViewModel.kt
  build.gradle
Labels: feature: My Store screen

#12109 [Product AI v2] Unit tests for the Preview viewmodel + some fixes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/SaveAiGeneratedProduct.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAITest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/WooLog.kt
Labels: feature: product details, category: unit tests

#12112 Logging and null checking to help with issue 11941
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
Labels: type: crash

#12123 Update orders task
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateAnalyticsDashboardRangeSelections.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateDataOnBackgroundWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateOrdersList.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateAnalyticsDashboardRangeSelectionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateOrdersListTest.kt
  build.gradle
Labels: type: task, feature: order list

#12121 Issue/12108 fix crash on stats card
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt
Labels: feature: stats, type: crash

#12038 [Google for Woo] Success handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/ads/success/GoogleAdsCampaignSuccessBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/ads/success/GoogleAdsCampaignSuccessBottomSheetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: My Store screen, feature: more menu

#12097 [Google for Woo] Refactor Webview usage to use its own GoogleAdsWebView
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/exitawarewebview/ExitAwareWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/layout/fragment_exitaware_webview.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: category: woo extensions, unit-tests-exemption

#12099 [Woo POS] M2: Move floating toolbar to the home screen from the root
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModelTest.kt
Labels: feature: point of sale

#12127 Issue/12126 fix image upload issues
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt
  build.gradle
Labels: type: bug, feature: product details

#12120 Add new select image button independent from text field
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/components/SelectImageSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/res/drawable/ic_gridicons_camera_primary.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: product details, unit-tests-exemption

#12094 Orders list with last update
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/LastUpdateDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFiltersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/FetchOrdersRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/ObserveOrdersListLastUpdate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/ShouldUpdateOrdersList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/StoreOrdersListLastUpdate.kt
  WooCommerce/src/main/res/layout/order_filters_card.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/LastUpdateDataStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/list/ObserveOrdersListLastUpdateTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/list/ShouldUpdateOrdersListTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/list/StoreOrdersListLastUpdateTest.kt
Labels: type: task, feature: order list, unit-tests-exemption, Feature: Background Updates

#12124 [Wear App] Handle application password stores scenario
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/di/AppConfigModule.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/system/ConnectionStatus.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/system/NetworkStatus.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/LoginRepository.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/details/FetchOrderProducts.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/list/FetchOrders.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/stats/datasource/FetchStats.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/orders/details/FetchOrderProductsTest.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/orders/list/FetchOrdersTest.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/wear/ui/stats/datasource/FetchStatsTest.kt
Labels: type: crash, feature: android wear

#12070 [Woo POS] Ensure order creation retry button works correctly
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12129 Track the number of words for the product prompt used
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: category: tracks

#12089 [Woo POS] Make sure strings are correct for order creation failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12098 [Google for Woo] Tracking
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ReviewsUITest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
Labels: category: tracks, unit-tests-exemption

#12119 [Woo POS] M2: Products loading errors and empty state
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashViewModel.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_empty_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#12134 [GLA Analytics] Introduce metrics selection into google stats card
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsRepository.kt
  WooCommerce/src/main/res/layout/analytics_custom_selection_card_view.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: task, feature: analytics, unit-tests-exemption

#12137 [GLA Analytics] Connect google stats filter with network layer
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStat.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStatUIData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt
  WooCommerce/src/main/res/drawable/ic_filter.xml
  WooCommerce/src/main/res/layout/analytics_custom_selection_card_view.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/GoogleAdsStatUIDataTest.kt
  build.gradle
Labels: type: task, feature: analytics, unit-tests-exemption

#12147 Fix UserAgent ANR
  RELEASE-NOTES.txt
  build.gradle
Labels: type: crash

#12155 Update changelogs for 19.7 release
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: category: releases, Releases

#12161 [GLA Analytics] Introduce Google Ads CTA into Analytics Hub
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStat.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStatUIData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/cta/AnalyticsHubUserCallToActionView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/customlistcard/AnalyticsHubCustomSelectionCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateStates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewViewModel.kt
  WooCommerce/src/main/res/layout/analytics_call_to_action_view.xml
  WooCommerce/src/main/res/layout/fragment_analytics.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, category: tracks, feature: analytics, unit-tests-exemption

#12156 [Woo POS] Make a WooLog.T for our project
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/WooLog.kt
Labels: feature: point of sale

#12095 [Woo POS] Display "Simple products only" banner in POS mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/di/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/datastore/WooPosPreferencesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/ext/WooPosContextExt.kt
  WooCommerce/src/main/res/drawable/info.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: feature: point of sale

#12166 [GLA Analytics] M2 Analytics tracks
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/GoogleAdsStat.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
Labels: type: task, category: tracks, feature: analytics

#12163 [Google for Woo] Update `CanUseAutoLoginWebview` only to support WordPress.com sites.
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/CanUseAutoLoginWebview.kt
Labels: type: bug

#12158 [Woo POS] Do not send price when create an order, only product ids
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
Labels: feature: point of sale

#12149 Update orders on notification
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/OrderNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateDataOnBackgroundWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateOrderAndOrderList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateOrderListBySelectedStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/UpdateOrdersListByStoreId.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/background/WorkManagerScheduler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetWCOrderListDescriptorWithFilters.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/GetWCOrderListDescriptorWithFiltersBySiteId.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateOrderAndOrderListTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateOrdersListBySelectedStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/background/UpdateOrdersListByStoreIdTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/list/ShouldUpdateOrdersListByStoreIdTest.kt
Labels: type: task, feature: order list, unit-tests-exemption

#12153 Fix ANR about Zendesk SDK initialization
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/WooNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/requests/SupportRequestFormActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/model/NotificationTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/main/MainActivityViewModelTest.kt
Labels: type: crash, feature: support

#12140 [Woo POS] M2: Update totals subscreen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#12133 [Woo POS] Match design for order creation failure
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
Labels: feature: point of sale

#12154 [Woo POS] Double check order creation failure classes for missing unit tests
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooPosErrorStateTest.kt
Labels: feature: point of sale
