Repository woocommerce/woocommerce-android, pull requests merged in 2024-02, with the labels that each got.

#10659 Revert commits pushed to trunk
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/DialogParams.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/WooDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
Labels: type: task

#10637 [Backend Receipts] Abstract old stripe and the new way of retriving receipts based on WC version
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingChecker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentOrderHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelper.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentOrderHelperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelperTest.kt
  build.gradle
Labels: feature: order details

#10646 [Backend Receipts] Loading indicator when receipt is fetching on the order details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt
  WooCommerce/src/main/res/layout/order_detail_payment_info.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: feature: order details

#10658 [Issue 4156] Disable Pull-to-Refresh During Product Search
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
Labels: type: bug

#10650 [Backed Receipt] Download and share a file not a link
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptShare.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewViewModelEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/tracking/PaymentsFlowTracker.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptShareTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewViewModelTest.kt
  build.gradle
Labels: feature: order details

#10654 [Backend Receipts] Add tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/tracking/PaymentsFlowTracker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/tracking/PaymentsFlowTrackerTest.kt
Labels: feature: order details, feature: analytics

#10624 Fix widget for woo express stores
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/GetWidgetStats.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/appwidgets/stats/today/TodayStatsWidgetUIHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/data/StatsRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/appwidgets/stats/GetWidgetStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/StatsRepositoryTests.kt
Labels: type: bug, feature: stats

#10674 Update CHANGELOG for 17.2
  CHANGELOG.md
Labels: Releases

#10660 [UI Test] - Re-enable Create Order test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/UnifiedOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersUITest.kt
Labels: category: ui tests

#10673 [Order creation] Display prices only for synced items
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
Labels: type: enhancement, good first issue

#10682 Generalize the toolbar fix when changing visibility during a pending animation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
Labels: type: task, unit-tests-exemption, Tech Debt

#10688 Fix Jetpack CP login
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
Labels: type: bug, feature: login

#10680 Blaze: Target location selection
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FlowExtensions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/MultiSelectList.kt
  WooCommerce/src/main/res/drawable/search_failed_illustration.xml
  WooCommerce/src/main/res/drawable/search_illustration.xml
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze, unit-tests-exemption

#10677 Add see report button in Analytic Hub
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetReportUrl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/informationcard/AnalyticsHubInformationCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/informationcard/AnalyticsHubInformationViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsRepository.kt
  WooCommerce/src/main/res/layout/analytics_information_card_view.xml
  WooCommerce/src/main/res/layout/analytics_list_card_view.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/hub/GetReportUrlTest.kt
Labels: type: task, feature: analytics

#10681 [Backend Receipt] Add a text that we share along with the file
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptShare.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptShareTest.kt
Labels: feature: order details

#10697 build: bump Kotlin and dependent libraries
  build.gradle
  settings.gradle
Labels: category: tooling

#10685 Blaze: Ad destination screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze, unit-tests-exemption

#10687 Add track event to see analytic report
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/GetReportUrl.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
Labels: type: task, category: analytics, feature: analytics

#10664 [Issue 3885] product variation delete confirmation dialog to a dialog fragment
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/DialogParams.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/WooDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt
Labels: type: enhancement, unit-tests-exemption

#10711 [Blaze] Network implementations
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModel.kt
  build.gradle
Labels: type: enhancement, feature: blaze

#10691 Add see report to UI interactions
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
Labels: type: task, category: analytics, feature: analytics

#10686 Remove BoxWithConstraints from domain search
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/domain/DomainSuggestionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/domainpicker/DomainPickerScreen.kt
Labels: type: crash

#10716 Blaze: Ad destination URL dialog
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#10733 Blaze: Target URL nullability
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#10706 build: bump Glide to `4.16.0`
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListCardItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginNoJetpackFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreTopPerformersView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailProductChildItemListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/adapters/BundleProductViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentDetailsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentOptionsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentsListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/views/LoginUserInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCProductImageGalleryView.kt
  build.gradle
Labels: category: tooling

#10709 Budget screen logic
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
Labels: feature: blaze, unit-tests-exemption

#10732 [Blaze] Payment summary screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/CreditCardType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/PaymentMethodUiExts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/drawable/credit_card_amex.xml
  WooCommerce/src/main/res/drawable/credit_card_diners.xml
  WooCommerce/src/main/res/drawable/credit_card_discover.xml
  WooCommerce/src/main/res/drawable/credit_card_jcb.xml
  WooCommerce/src/main/res/drawable/credit_card_mastercard.xml
  WooCommerce/src/main/res/drawable/credit_card_placeholder.xml
  WooCommerce/src/main/res/drawable/credit_card_unionpay.xml
  WooCommerce/src/main/res/drawable/credit_card_visa.xml
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: type: enhancement, feature: blaze

#10730 Update CHANGELOG for 17.3
  CHANGELOG.md
Labels: Releases

#10727 [Better Tablet Products] Feature Flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: feature: product list, category: tablet

#10729 [Order creation] Add @Preview annotation for prices
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
Labels: feature: order creation

#10734 Fetch and display ad impressions forecast
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#10759 Add EXPANDED_ANALYTIC_HUB_M2 feature flag
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: analytics

#10484 GHA Workflow for validating issues
  .github/workflows/validate-issues.yml
Labels: category: tooling

#10775 [Bug] IllegalArgumentException Destination not found – Update `navigation-fragment-ktx` to 2.7.7
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeCampaignCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/hub/depositsummary/PaymentsHubDepositSummaryView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/shipping/InstallWCShippingScreen.kt
  settings.gradle
Labels: type: bug, type: crash

#10739 Fix budget slider responsiveness
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
Labels: feature: blaze

#10602 Fix for NotificationMessageHandler Concurrent Modification Exception
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationsProcessingService.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
Labels: type: bug

#10786 [hotfix][17.2] Revert `navigationVersion` bump
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  settings.gradle
Labels: type: crash

#10708 Migrate to `ksp`
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/ProductImageMapModule.kt
  build.gradle
  gradle.properties-example
  settings.gradle
Labels: category: tooling, type: technical debt

#10777 Issue/10721 blaze add new payment method
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: blaze

#10781 Display campaign created success bottom sheet
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/success/BlazeCampaignSuccessBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/success/BlazeCampaignSuccessBottomSheetFragment.kt
  WooCommerce/src/main/res/drawable-night/blaze_campaign_created_success.xml
  WooCommerce/src/main/res/drawable/blaze_campaign_created_success.xml
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze

#10692 Dangermattic checks update
  .github/workflows/run-danger.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: category: tooling

#10793 Blaze: Add campaign creation help buttons
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpOrigin.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
Labels: feature: blaze

#10592 Business logic to open order detail on order item click in 2 pane layout
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: task, category: tablet

#10642 Select the first order by default in tablet
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListView.kt
Labels: type: task, feature: order details, feature: order list, category: tablet

#10643 Highlight the selected order in the order list
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListItemUIType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListListener.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SelectedOrderTrackerViewModel.kt
  WooCommerce/src/main/res/layout/order_list_item.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
Labels: type: task, feature: order details, feature: order list, category: tablet

#10740 Add toolbar for Order list and Order detail
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/OrderEditingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListView.kt
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
Labels: type: task, feature: order details, feature: order list, category: tablet

#10741 Add toolbar for CustomerOrderNoteEditingFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/BaseOrderEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/CustomerOrderNoteEditingFragment.kt
  WooCommerce/src/main/res/layout/fragment_order_create_edit_customer_note.xml
Labels: type: task, category: tablet

#10742 Add toolbar for BaseAddressEditingFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BillingAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/ShippingAddressEditingFragment.kt
  WooCommerce/src/main/res/layout/fragment_base_edit_address.xml
Labels: type: task, category: tablet

#10743 Add toolbar for AddOrderNoteFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteFragment.kt
  WooCommerce/src/main/res/layout/fragment_add_order_note.xml
Labels: type: task, category: tablet

#10744 Add toolbar to PrintShippingLabelFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelFragment.kt
  WooCommerce/src/main/res/layout/fragment_print_shipping_label.xml
Labels: type: task, category: tablet

#10745 Add toolbar to label format options fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/LabelFormatOptionsFragment.kt
  WooCommerce/src/main/res/layout/fragment_label_format_options.xml
Labels: type: task, category: tablet

#10746 Add toolbar to PrintShippingLabelInfoFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelInfoFragment.kt
  WooCommerce/src/main/res/layout/fragment_print_shipping_label_info.xml
Labels: type: task, category: tablet

#10747 Add toolbar to print shipping label customs form fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/PrintShippingLabelCustomsFormFragment.kt
  WooCommerce/src/main/res/layout/fragment_print_label_customs_form.xml
Labels: type: task, category: tablet

#10748 Add toolbar to ShippingLabelRefundFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRefundFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_refund.xml
Labels: type: task, category: tablet

#10749 Add toolbar for ShippingPackageSelectorFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingPackageSelectorFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_packages_selector.xml
Labels: type: task, category: tablet

#10750 Add toolbar for ShippingLabelCreatePackageFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreatePackageFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_package.xml
Labels: type: task, category: tablet

#10751 Add toolbar for create custom package screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_custom_package.xml
Labels: type: task, category: tablet

#10752 Add toolbar for ShippingLabelAddressSuggestionFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressSuggestionFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_label_address_suggestion.xml
Labels: type: task, category: tablet

#10753 Add toolbar for ShippingCustomsFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCustomsFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_customs.xml
Labels: type: task, category: tablet

#10754 Add toolbar for ShippingCarrierRatesFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingCarrierRatesFragment.kt
  WooCommerce/src/main/res/layout/fragment_shipping_carrier_rates.xml
Labels: type: task, category: tablet

#10755 Add toolbar for CreateShippingLabelFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
  WooCommerce/src/main/res/layout/fragment_create_shipping_label.xml
Labels: type: task, category: tablet

#10756 Add toolbar for EditShippingLabelAddressFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_address.xml
Labels: type: task, category: tablet

#10757 Add toolbar to edit shipping label package screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_packages.xml
Labels: type: task, category: tablet

#10765 Add toolbar for SelectPaymentMethodFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/res/layout/fragment_select_payment_method.xml
Labels: type: task, category: tablet

#10766 Add toolbar for PaymentsHubFragment screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/hub/PaymentsHubFragment.kt
  WooCommerce/src/main/res/layout/fragment_payments_hub.xml
Labels: type: task, category: tablet

#10767 Add toolbar for CardReaderOnboardingFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
Labels: type: task, category: tablet

#10768 Refresh orders list on a successfull IPP transaction
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/SelectedOrderTrackerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
Labels: type: task, category: tablet

#10770 Add toolbars to refund screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/IssueRefundFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundByItemsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/refunds/RefundSummaryFragment.kt
  WooCommerce/src/main/res/layout/fragment_issue_refund.xml
  WooCommerce/src/main/res/layout/fragment_refund_summary.xml
Labels: type: task, category: tablet

#10771 Add toolbar elevation
  WooCommerce/src/main/res/layout/fragment_add_order_note.xml
  WooCommerce/src/main/res/layout/fragment_base_edit_address.xml
  WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
  WooCommerce/src/main/res/layout/fragment_edit_shipping_label_payment.xml
  WooCommerce/src/main/res/layout/fragment_label_format_options.xml
  WooCommerce/src/main/res/layout/fragment_order_create_edit_customer_note.xml
  WooCommerce/src/main/res/layout/fragment_order_detail.xml
  WooCommerce/src/main/res/layout/fragment_payments_hub.xml
  WooCommerce/src/main/res/layout/fragment_select_payment_method.xml
  WooCommerce/src/main/res/layout/fragment_shipping_carrier_rates.xml
  WooCommerce/src/main/res/layout/fragment_shipping_customs.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_address_suggestion.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_custom_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_label_create_package.xml
  WooCommerce/src/main/res/layout/fragment_shipping_packages_selector.xml
Labels: type: task, category: tablet

#10662 Printing receipts instructions screen as dialog on tablets
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/PrintingInstructionsFragment.kt
  WooCommerce/src/main/res/layout/fragment_printing_instructions.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
Labels: type: task, feature: order details, category: tablet

#10663 Resize filter fragment into dialog in tablet
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterOptionsFragment.kt
  WooCommerce/src/main/res/layout/fragment_order_filter_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_filters.xml
Labels: type: task, feature: order list, category: tablet

#10812 Add analytics to track device type on some screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ActivityExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/tracking/PaymentsFlowTracker.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/EditFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/tracking/PaymentsFlowTrackerTest.kt
Labels: category: analytics, category: tablet

#10790 Issue/10785 blaze creation endpoint
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  build.gradle
Labels: type: task, feature: blaze, unit-tests-exemption

#10821 Adds existing Blaze tracking to the new native implementation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/BlazeCampaignCreationDispatcher.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/BlazeCampaignCreationDispatcherTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroViewModelTests.kt
Labels: feature: analytics, feature: blaze

#10816 [Better Tablet Products] Open order detail on order item click in 2 pane layout
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesNotificationHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/AIProductDescriptionDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributesAddedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TabletLayoutSetupHelper.kt
  WooCommerce/src/main/res/layout/fragment_product_list.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt
Labels: feature: product list, category: tablet

#10818 Manage analytic configuration UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/res/drawable/ic_configuration.xml
  WooCommerce/src/main/res/menu/menu_analytics_settings.xml
  WooCommerce/src/main/res/navigation/nav_graph_main.xml
  WooCommerce/src/main/res/values/ids.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: analytics, unit-tests-exemption

#10696 [Issue 10695] Fix Button Text Cut Off on 'Orders' Screen
  WooCommerce/src/main/res/layout/view_expandable_notice_card.xml
Labels: type: bug

#10647 Add credential manager support
  RELEASE-NOTES.txt
  build.gradle
Labels: type: task, feature: login

#10829 Blaze: loading and error screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/res/drawable/ic_timer.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: blaze, unit-tests-exemption

#10819 Blaze: Destination URL parameter editing
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationParametersBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationParametersScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationParametersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/ModalStatusBarBottomSheetLayout.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: blaze, unit-tests-exemption

#10848 Danger check: update Tracks label
  Dangerfile
Labels: category: tooling

#10838 Update CHANGELOG for 17.4
  CHANGELOG.md
Labels: Releases

#10835 Blaze: show an error if one of the requirements of the creation is missing
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/DialogState.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: blaze, unit-tests-exemption

#10841 Blaze: Unit tests for BlazeCampaignCreationPreviewViewModel
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModelTests.kt
Labels: category: unit tests, feature: blaze

#10849 Danger: remove strings.xml check
  Dangerfile
Labels: category: tooling

#10817 [Better Tablet Products] Select the first product by default in tablet
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TabletLayoutSetupHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiHelpers.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt
Labels: feature: product list, category: tablet, unit-tests-exemption

#10871 Update semver comparison logic to fix indexOutOfBounds
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/receipt/PaymentReceiptHelperTest.kt
Labels: feature: order details

#10844 [Better Tablet Products] Adapt toolbar for the 2 pane layout on the list part
  RELEASE-NOTES.txt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductsRealAPI.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListToolbarHelper.kt
  WooCommerce/src/main/res/layout/fragment_product_list.xml
Labels: feature: product list, category: tablet, unit-tests-exemption

#10877 [Tablet Support M2] Bug/10862 crash when no orders
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: bug, category: tablet

#10887 [Tablet Support M2] Issue 10860 - Improve Order List & Details UI in Small Tablets
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/res/values-sw720dp/bools.xml
  WooCommerce/src/main/res/values/bools.xml
Labels: type: enhancement, category: tablet

#10883 [Tablet Support M2] Issue 10863 - Fix order list reload on search view expand
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: bug, category: tablet

#10872 [Tablet Support M2] Bug/10861 Navigation during dynamic screen size changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/res/layout/fragment_order_list.xml
Labels: type: bug, category: tablet

#10894 Tooling: fix issue labels validation
  .github/workflows/validate-issues.yml
Labels: category: tooling

#10876 Refactor Address handling to avoid using shared viewmodels
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditCustomerAddFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BaseAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/BillingAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/ShippingAddressEditingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
Labels: feature: order details, Tech Debt

#10902 [Tablet Support M2] Prevent ConcurrentModificationException in ProductImageMap with CopyOnWriteArrayList
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
Labels: type: bug, category: tablet

#10857 Prevent all cards to be disabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/AnalyticCardConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/ObserveAnalyticsCardsConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/SaveAnalyticsCardsConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsSettingsDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsSettingsResourcesRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/ObserveAnalyticsCardsConfigurationTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/settings/AnalyticsHubSettingsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/settings/SaveAnalyticsCardsConfigurationTest.kt
Labels: type: task, feature: analytics

#10905 Update CHANGELOG for 17.5
  CHANGELOG.md
Labels: Releases

#10925 Meetup [Order filtering]: networking changes + guests handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlist/CustomerListViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/navigation/OrderCreateEditNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/data/OrderFiltersRepository.kt
  WooCommerce/src/main/res/navigation/nav_graph_order_creations.xml
  WooCommerce/src/main/res/navigation/nav_graph_order_filters.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: feature: order list

#10921 [Tablet Support M2] Fix back navigation on Order screen on phones
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: crash

#10820 Issue/10784 blaze analytics part ii
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModelTests.kt
Labels: category: tracks, feature: blaze

#10910 Fix ProductImageMap ConcurrentModificationException by Safely Managing WeakReferences
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt
Labels: type: bug

#10866 [Better Tablet Products] Adapt toolbar for the 2 pane layout on the details part
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/products/SingleProductScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailsToolbarHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TabletLayoutSetupHelper.kt
  WooCommerce/src/main/res/layout/fragment_product_detail.xml
  WooCommerce/src/main/res/layout/fragment_product_list.xml
Labels: feature: product details, category: tablet, unit-tests-exemption

#10917 [Tablet Support] Order Details - Pencil Icon Clickability in Customer Note Section
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
Labels: type: bug

#10931 Skip `hilt` in unit tests. Do not execute `ksp` on unit test sources.
  .buildkite/commands/run-unit-tests.sh
  WooCommerce/build.gradle
  config/gradle/build_optimization.gradle
  gradle.properties-example
Labels: type: enhancement, category: tooling

#10934 Update secrets to disable ksp in test sources
  .configure
  .configure-files/gradle.properties.enc
Labels: category: tooling

#10828 Blaze: Add unit tests from the destination screen
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModelTest.kt
Labels: category: unit tests

#10926 Issue/10784 blaze analytics part iii
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
Labels: category: tracks, feature: blaze

#10938 [Beta fix 17.5] Fix NullPointerException in OrderListFragment::onSaveInstanceState
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: crash

#10939 [Beta fix 17.5] Fix navigation back on phones
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: type: crash

#10875 [Better Tablet Products] Adapt toolbar for the nested product details fragments Part 1
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/aztec/AztecEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductInventoryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductShippingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ParentCategoryListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/price/ProductPricingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributesAddedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FragmentSecondPaneExt.kt
  WooCommerce/src/main/res/layout/fragment_add_attribute.xml
  WooCommerce/src/main/res/layout/fragment_add_attribute_terms.xml
  WooCommerce/src/main/res/layout/fragment_add_product_category.xml
  WooCommerce/src/main/res/layout/fragment_attribute_list.xml
  WooCommerce/src/main/res/layout/fragment_attributes_added.xml
  WooCommerce/src/main/res/layout/fragment_aztec_editor.xml
  WooCommerce/src/main/res/layout/fragment_product_categories_list.xml
  WooCommerce/src/main/res/layout/fragment_product_images.xml
  WooCommerce/src/main/res/layout/fragment_product_inventory.xml
  WooCommerce/src/main/res/layout/fragment_product_pricing.xml
  WooCommerce/src/main/res/layout/fragment_product_shipping.xml
  WooCommerce/src/main/res/layout/fragment_reviews_list.xml
  WooCommerce/src/main/res/layout/fragment_variation_list.xml
Labels: feature: product details, category: tablet

#10892 [Better Tablet Products] Adapt toolbar for the nested product details fragments part 2
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GroupedProductListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/LinkedProductsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductBundleFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductExternalLinkFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/product/ProductAddonsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentDetailsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/components/ComponentListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadDetailsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/downloads/ProductDownloadsSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/BaseProductSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductCatalogVisibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductMenuOrderFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSettingsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductSlugFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductStatusFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductVisibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/subscriptions/ProductSubscriptionExpirationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/subscriptions/ProductSubscriptionFreeTrialFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/RenameAttributeFragment.kt
  WooCommerce/src/main/res/layout/fragment_bundle_product_list.xml
  WooCommerce/src/main/res/layout/fragment_component_details.xml
  WooCommerce/src/main/res/layout/fragment_component_list.xml
  WooCommerce/src/main/res/layout/fragment_grouped_product_list.xml
  WooCommerce/src/main/res/layout/fragment_linked_products.xml
  WooCommerce/src/main/res/layout/fragment_media_upload_error_list.xml
  WooCommerce/src/main/res/layout/fragment_product_addons.xml
  WooCommerce/src/main/res/layout/fragment_product_catalog_visibility.xml
  WooCommerce/src/main/res/layout/fragment_product_download_details.xml
  WooCommerce/src/main/res/layout/fragment_product_downloads_list.xml
  WooCommerce/src/main/res/layout/fragment_product_downloads_settings.xml
  WooCommerce/src/main/res/layout/fragment_product_external_link.xml
  WooCommerce/src/main/res/layout/fragment_product_image_viewer.xml
  WooCommerce/src/main/res/layout/fragment_product_menu_order.xml
  WooCommerce/src/main/res/layout/fragment_product_quantity_rules.xml
  WooCommerce/src/main/res/layout/fragment_product_settings.xml
  WooCommerce/src/main/res/layout/fragment_product_slug.xml
  WooCommerce/src/main/res/layout/fragment_product_status.xml
  WooCommerce/src/main/res/layout/fragment_product_tags.xml
  WooCommerce/src/main/res/layout/fragment_product_visibility.xml
  WooCommerce/src/main/res/layout/fragment_rename_attribute.xml
Labels: feature: product details, category: tablet

#10911 [Better Tablet Products] Fix back navigation on 2 pane layout
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListToolbarHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/TabletLayoutSetupHelper.kt
Labels: feature: product list, category: tablet

#10854 [Blaze] Fixes + unit tests for the payment viewmodels
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_blaze_campaign_creation.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentMethodsListViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazePaymentSampleData.kt
Labels: category: unit tests, feature: blaze

#10936 [Meetup Project] Order Details: Support contacting customers through WhatsApp or Telegram
  RELEASE-NOTES.txt
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ActivityUtils.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: order details, category: tracks

#10948 [Linked Products] Product Selection Issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductSelectionListFragment.kt
  WooCommerce/src/main/res/menu/menu_action_mode_check.xml
Labels: type: bug, feature: product details

#10853 Blaze: Fix a crash when no ad suggestions
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationViewModelTest.kt
Labels: type: crash, feature: blaze

#10954 Automate the Play Store submission
  .buildkite/release-pipelines/new-hotfix-release.yml
  fastlane/Fastfile
Labels: category: tooling

#10955 Revert accidental trunk push
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionViewModelTests.kt
Labels: type: task

#10956 [Blaze] Error state for location search + Unit tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/TargetSelectionViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetLocationSelectionViewModelTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionViewModelTests.kt
Labels: type: enhancement, status: feature-flagged, feature: blaze

#10900 [Better Errors] Handle timeout errors inside Orders list
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
  build.gradle
Labels: type: task, feature: order list

#10923 Hide cards based on analytics configuration
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/AnalyticCardConfiguration.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubCardViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/informationcard/AnalyticsHubInformationCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/informationcard/AnalyticsHubInformationSectionViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/informationcard/AnalyticsHubInformationViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListCardView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/listcard/AnalyticsHubListViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsSettingsDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsSettingsResourcesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/ObserveAnalyticsCardsConfigurationTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/UpdateAnalyticsHubStatsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/settings/AnalyticsHubSettingsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/settings/SaveAnalyticsCardsConfigurationTest.kt
Labels: type: task, feature: analytics

#10937 Reorder cards
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/settings/AnalyticsHubSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/LazyListDragAndDrop.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/settings/AnalyticsHubSettingsViewModelTest.kt
Labels: type: task, feature: analytics, unit-tests-exemption
