Repository woocommerce/woocommerce-android, pull requests merged in 2024-06, with the labels that each got.

#11549 Add check if plugin setup is completed
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabled.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabledTest.kt
Labels: feature: point of service

#11638 [Woo POS] Payments dialogs bigger on the big screens
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/values-sw600dp/dimens_payments.xml
Labels: feature: mobile payments, feature: point of service

#11616 [Woo POS] Start card reader connection flow and adapt to return result of connection to pos
  WooCommerce/src/main/AndroidManifest.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/statuschecker/CardReaderStatusCheckerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/hub/PaymentsHubViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderMode.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderPaymentResult.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosRootHost.kt
  WooCommerce/src/main/res/layout/activity_woo_pos_card_reader.xml
  WooCommerce/src/main/res/values/themes.xml
Labels: category: tracks, unit-tests-exemption, feature: point of service

#11648 [Woo POS] Bottom toolbar that shared across the screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/checkout/WooPosCheckoutScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/checkout/WooPosCheckoutViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosComposePreviewAnnotation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvents.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosRootHost.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: unit-tests-exemption, feature: point of service

#11642 [Woo POS] Removed usages of ScopedViewModel
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/checkout/WooPosCheckoutViewModel.kt
Labels: feature: point of service

#11645 [Stats] Fix issue with date formatting of selected dates
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt
Labels: type: bug, feature: stats

#11539 [Woo POS] Products grid
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/di/POSModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/CartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/ProductSelectorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/ProductSelectorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/ProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/ProductsDataSourceImpl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/ViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: unit-tests-exemption, feature: point of service

#11650 Fix Application Passwords login issue
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt
Labels: type: bug, priority: high, feature: login

#11631 Issue/11559 product sales last 30 days
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductStockStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
Labels: unit-tests-exemption

#11636 [Tooling][Wear] Add Prototype Builds for Wear app
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/release-build.sh
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  Gemfile
  Gemfile.lock
  config/gradle/jacoco.gradle
  fastlane/Fastfile
Labels: category: tooling, feature: android wear

#11659 [Dynamic Dashboard] Orders card unit tests
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersViewModelTest.kt
Labels: category: unit tests, feature: My Store screen

#11665 [Dynamic Dashboard] Hide inbox card when its feature flag is disabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/DashboardWidget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: My Store screen, feature: inbox

#11666 [Dynamic Dashboard] Update products stock card error when WCAnalytics is disabled
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: My Store screen, unit-tests-exemption

#11669 [Woo POS] Update entry point eligibility condition to use woo 6.6.0
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabled.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabledTest.kt
Labels: feature: point of sale

#11658 [Woo POS] Implement skeleton of the i3 of the wireframes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/checkout/WooPosCheckoutNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/checkout/WooPosCheckoutScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/di/WooPosModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/di/POSModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/CartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceImpl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvents.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
Labels: unit-tests-exemption, feature: point of sale

#11670 Adds tracking for dynamic dashboard M2
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/DashboardWidget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/inbox/DashboardInboxViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/widgeteditor/DashboardWidgetEditorViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsViewModelTest.kt
Labels: category: tracks, unit-tests-exemption

#11682 [Application Passwords Login] Replace empty error messages with generic error message
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/WPApiSiteRepository.kt
Labels: type: bug, feature: login

#11672 Refresh FCM tokens periodically
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/FCMRefreshWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/RegisterDevice.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/GMSUtils.kt
Labels: type: bug, feature: notifications, unit-tests-exemption

#11690 [Dynamic Dashboard] Hide the new widgets announcement card when the "share store" card is shown
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/DashboardWidget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: My Store screen

#11688 [Dynamic Dashboard] Enable M2 feature flag
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: My Store screen

#11684 [Woo POS] Show pictures in landscape mode on tablets in card reader flows
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/adapter/MultipleCardReadersFoundViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/detail/CardReaderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderWelcomeDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/WCSettingsToggleOptionView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiHelpers.kt
Labels: feature: mobile payments, feature: point of sale

#11701 Release notes update
  CHANGELOG.md
  WooCommerce/metadata/release_notes.txt
  build.gradle
Labels: Releases

#11697 Convert AnalyticsEvent back to be an Enum
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
Labels: type: task, category: tracks

#11685 Update `release-toolkit` to latest 9.x to fix QR code in GitHub
  Gemfile
  Gemfile.lock
Labels: category: tooling

#11700 Issue/11520 invalidate pos eligibility cache
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabled.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/IsWooPosEnabledTest.kt
Labels: feature: point of sale

#11699 [Woo Pos] Allow adding products to Cart
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11705 [Woo POS] Using selected products create an order draft
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartCartRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#11686 [Woo POS] Add exiting functionality from the POS
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosConfirmationDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosBottomToolbarState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreenState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosRootHost.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/connection/CardReaderStatus.kt
Labels: unit-tests-exemption, feature: point of sale

#11654 [Payment Method Improvements] Bug: Support all currency symbols and formatting correctly
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TypedTextField.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/changeduecalculator/ChangeDueCalculatorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/changeduecalculator/ChangeDueCalculatorViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/changeduecalculator/CurrencyVisualTransformation.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/compose/component/NullableCurrencyTextFieldValueMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/changeduecalculator/ChangeDueCalculatorViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/changeduecalculator/CurrencyVisualTransformationTest.kt
Labels: type: bug, feature: mobile payments

#11715 [Woo POS] Disable products addition and removal when order is being created
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#11716 [Tooling] Fix changelogs management
  fastlane/Fastfile
  fastlane/metadata/android/ar/changelogs/default.txt
  fastlane/metadata/android/de-DE/changelogs/default.txt
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/android/es-ES/changelogs/default.txt
  fastlane/metadata/android/fr-FR/changelogs/default.txt
  fastlane/metadata/android/id/changelogs/default.txt
  fastlane/metadata/android/it-IT/changelogs/default.txt
  fastlane/metadata/android/iw-IL/changelogs/default.txt
  fastlane/metadata/android/ja-JP/changelogs/default.txt
  fastlane/metadata/android/ko-KR/changelogs/default.txt
  fastlane/metadata/android/nl-NL/changelogs/default.txt
  fastlane/metadata/android/pt-BR/changelogs/default.txt
  fastlane/metadata/android/ru-RU/changelogs/default.txt
  fastlane/metadata/android/sv-SE/changelogs/default.txt
  fastlane/metadata/android/tr-TR/changelogs/default.txt
  fastlane/metadata/android/zh-CN/changelogs/default.txt
  fastlane/metadata/android/zh-TW/changelogs/default.txt
Labels: category: tooling

#11721 [Dynamic Dashboard] Improve colors in Dark Mode for better visibility
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersCard.kt
  WooCommerce/src/main/res/drawable/ic_rounded_chcekbox_unchecked.xml
Labels: feature: My Store screen

#11717 [Woo POS] Start payment flow in Totals screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/layout/activity_woo_pos_card_reader.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartCartRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: unit-tests-exemption

#11728 Update fluxC changes to get latest fixes
  build.gradle
Labels: feature: blaze

#11734 Update build.gradle with new FluxC tag
  build.gradle
Labels: Releases

#11735 Add release notes
  CHANGELOG.md
  WooCommerce/metadata/release_notes.txt
Labels: Releases

#11611 [Min/Max Quantities Editing Support] Networking & Model
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/SubscriptionProductVariation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRulesMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/QuantityRulesMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRulesTest.kt
  build.gradle
Labels: feature: product details, category: woo extensions

#11740 Shipping lines design recommendations
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/FeedbackDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/totals/OrderCreateEditTotalsFullView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/totals/OrderCreateEditTotalsHelper.kt
  WooCommerce/src/main/res/layout/fragment_order_create_edit_form.xml
Labels: type: task, feature: order creation

#11722 [Dependency Analysis] Add Android Gradle Plugin
  .buildkite/schedules/dependency-analysis.yml
  .configure
  .configure-files/gradle.properties.enc
  build.gradle
  gradle.properties-example
  settings.gradle
Labels: category: tooling, Core

#11730 [Dynamic Dashboard] Stock card 19.0 beta feedback updates
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
Labels: feature: My Store screen

#11102 Product creation: Add search functionality into category selection
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/ProductCategoriesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
Labels: feature: product details

#11742 [Min/Max Quantities] Edit Support Core Implementation
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/res/layout/fragment_product_quantity_rules.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRulesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRulesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
  build.gradle
Labels: type: task, feature: product details, category: woo extensions

#11695 [UI Tests] - Run tests on tablet device locally
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/helpers/util/Screen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/OrderListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersRealAPI.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/ProductsRealAPI.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
Labels: category: ui tests

#11720 [Woo POS] Calculate and Display Order Totals on Totals Screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
Labels: type: task, feature: point of sale

#11745 [Watch App] Introduce better products loading
  WooCommerce-Wear/src/main/java/com/woocommerce/android/extensions/OrderEntityExt.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/model/OrderItem.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/model/Refund.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/ui/orders/OrdersRepository.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/ui/orders/details/FetchOrderProducts.kt
  WooCommerce-Wear/src/test/java/com/woocommerce/android/ui/orders/details/FetchOrderProductsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/wear/GetWearableOrderProducts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/wear/WearableConnectionRepository.kt
  libs/commons/src/main/java/com/woocommerce/commons/WearSharedModels.kt
Labels: type: task, unit-tests-exemption, feature: android wear

#11752 [Min-Max Quantities Edit Support] Tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModelTest.kt
Labels: type: task, category: tracks, feature: analytics

#11737 Issue/11321 improvements over blaze i3
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/IsBlazeEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/ad/BlazeCampaignCreationEditAdScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/preview/BlazeCampaignCreationPreviewViewModel.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: feature: blaze, unit-tests-exemption

#11753 [Min-Max Quantities] Main Feature
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductEditorFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRules.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigationTarget.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationNavigator.kt
  WooCommerce/src/main/res/layout/fragment_product_quantity_rules.xml
  WooCommerce/src/main/res/navigation/nav_graph_products.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/GetProductQuantityRulesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelGenerateVariationFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/quantityRules/ProductQuantityRulesViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/GetProductVariationQuantityRulesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
Labels: type: task, category: tracks, feature: product details, category: woo extensions

#11652 [Payment Method Improvements] Remove Feature Flag and related old code
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cashpayments/OtherPaymentMethodsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: enhancement, feature: mobile payments

#11768 Release/19.2 release notes
  CHANGELOG.md
  RELEASE-NOTES.txt
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/wear/en-US/changelogs/default.txt
Labels: type: task, category: releases, feature: android wear

#11772 [Tooling] Fix `create_gh_release` lane parameters
  fastlane/Fastfile
Labels: category: tooling

#11744 [Woo POS] Handle card payment cancelation and failure events
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/snackbar/WooPosSnackbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/snackbar/WooPosSnackbarState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: unit-tests-exemption, feature: point of sale

#11766 [HACK Week: Watch App] Introduce complications support
  WooCommerce-Wear/src/main/AndroidManifest.xml
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/AppShortcutComplicationService.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/complications/ComplicationUtils.kt
  WooCommerce-Wear/src/main/res/values/strings.xml
Labels: type: task, feature: android wear

#11773 [Tooling] Fix Wear app Google Play Console app prefix
  fastlane/Fastfile
Labels: category: tooling

#11780 [Tooling] Fix outdated changelogs removal logic
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/wear/en-US/changelogs/default.txt
Labels: category: tooling

#11763 Issue/11381 update variation name in order creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableGroupedProductCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/ProductUtils.kt
Labels: feature: order creation

#11764 [Woo POS] Compose theme colors, Woo Pos button, Bottom Toolbar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButton.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootBottomToolbar.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: point of sale

#11786 [Tooling] Fix Wear App Universal .apk download
  fastlane/Fastfile
Labels: category: tooling

#11765 [Woo POS] Add toolbar to the cart's subscreen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11801 [Min-Max Quantities Edit Support] Show Backend Error Messages
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductErrorExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/inventory/ScanToUpdateInventoryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/media/ProductImagesUploadWorkerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel_AddFlowTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/inventory/ScanToUpdateInventoryViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModelTest.kt
  build.gradle
Labels: type: task, category: woo extensions

#11743 Issue/11718 minor beta fixes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
Labels: feature: My Store screen

#11758 Fetch only simple products in the POS mode
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceImpl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
Labels: feature: point of sale

#11809 [Dependency Analysis] Add Custom Meta-Data to CI Schedule
  .buildkite/schedules/dependency-analysis.yml
Labels: category: tooling, Core

#11784 [Tooling] Ruby-fy `send_strings_for_translation` & `commit_strings` lanes
  fastlane/Fastfile
Labels: category: tooling

#11804 Fix NPE in ReceiptPreviewFragment
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewFragment.kt
Labels: feature: order details

#11788 [Woo POS] The UI of the cart items
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/format/WooPosFormatPrice.kt
  WooCommerce/src/main/res/drawable/ic_pos_remove_cart_item.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt
Labels: feature: point of sale

#11819 Migrate to use `jetpack-ai-query` endpoint for ai generated content
  WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIRepository.kt
  build.gradle
Labels: type: task, feature: product details, unit-tests-exemption

#11749 [Woo Pos] #11724 Redirect to payment success screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/WooPosRootViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_payment_success.xml
  WooCommerce/src/main/res/drawable/woo_pos_ic_return_home.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11779 Remove obsolete logs from OrderListFragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
Labels: category: reliability

#11824 Avoid race conditions and ensure statsTimeRangeSelection is set
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt
Labels: type: crash

#11833 [Min-Max Quantities] M1 Fixes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExtTest.kt
Labels: type: task, category: woo extensions

#11837 Fix the visibility issue of the Blaze button on product detail screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiModels.kt
Labels: type: bug, feature: blaze

#11843 [Min-Max Quantities] M1 Fixes PR Improvements
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/QuantityRulesExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/models/QuantityRulesExtTest.kt
Labels: type: task, category: woo extensions

#11827 [Woo POS] Clean up strings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: point of sale

#11842 Revert changes that made changing stock status stop working
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockViewModel.kt
Labels: type: bug

#11821 [Woo POS] Implement the UI of the product list
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosShimmerBox.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/di/WooPosActivityModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsDataSourceImpl.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#11847 [Wear App] Fix Play Store rejection issues
  WooCommerce-Wear/build.gradle
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/compose/component/ScrollStateAdapter.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/login/LoginScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/details/OrderDetailsScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/orders/list/OrdersListScreen.kt
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/ui/stats/StoreStatsScreen.kt
  WooCommerce-Wear/src/main/res/values/dimens.xml
  WooCommerce-Wear/src/main/res/values/strings.xml
Labels: type: task, unit-tests-exemption, feature: android wear

#11850 [Tooling] Fix `finalize_release` lane and `options` parameter not needed anymore
  fastlane/Fastfile
Labels: category: tooling

#11852 Update the release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases
