Repository woocommerce/woocommerce-android, pull requests merged in 2024-12, with the labels that each got.

#13026 [Product Global Unique Id] Show values in product/variation details
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailCardBuilder.kt
  WooCommerce/src/main/res/layout/fragment_product_inventory.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: product details

#13034 [Woo POS][Cash & Receipts] Update customer with email and use action to send it
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosTotalsPaymentReceiptIsSendingAvailable.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosTotalsPaymentReceiptRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosIsReceiptSendingAvailableTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosTotalsPaymentReceiptRepositoryTest.kt
  gradle/libs.versions.toml
Labels: feature: point of sale

#12995 [Custom Fields] Code cleanup
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsHelper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/customfields/CustomOrderFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailBottomSheetBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: task

#13024 Return user to email screen after entering wrong email
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/error/LoginNoWPcomAccountFoundDialogFragment.kt
Labels: feature: login

#13035 Product details: Keep Shipping card with One Time Shipping available when changing from Subscription to Non-Subscription Type Product
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/details/ProductDetailViewModelTest.kt
Labels: feature: product details

#13059 [Shipping Labels Revamp] Fix Shipping Label package serialization
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/WooShippingLabelPackageMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/networking/CarrierPackageDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/networking/PackageResponseDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/networking/StorePackageDTOs.kt
Labels: type: task, feature: shipping labels

#13054 Fix/dashboard custom range tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersWidgetCard.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt
Labels: category: tracks, feature: My Store screen

#13046 Update androidx.lifecycle dependency to use 2.8.7
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/ScopedViewModel.kt
  gradle/libs.versions.toml
Labels: dependency update

#13042 [Woo POS][Cash & Receipts] Add optional take payment button and empty state for cash
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/cash/WooPosTotalsPaymentCashScreen.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#13049 [Woo POS][Cash & Receipts] Prompt alert when woo core versions are no correct and receipt clicked
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosTotalsPaymentReceiptIsSendingSupported.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/receipt/WooPosIsReceiptSendingAvailableTest.kt
Labels: feature: point of sale

#13060 Update androidx-compose-bom dependency to use '2024.09.01'
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/destination/BlazeCampaignCreationAdDestinationParametersScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/objective/BlazeCampaignObjectiveScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/payment/BlazeCampaignPaymentSummaryScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/targets/BlazeCampaignTargetSelectionScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/TextExts.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Buttons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/SearchLayoutWithParams.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/WidgetError.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/blaze/DashboardBlazeCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/coupons/DashboardCouponsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/google/DashboardGoogleAdsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/inbox/DashboardInboxCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/orders/DashboardOrdersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/reviews/DashboardReviewsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersWidgetCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/components/JetpackConsent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/sitecredentials/JetpackActivationSiteCredentialsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/onboarding/payments/PaymentsPreSetupScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/onboarding/payments/WooPaymentsSetupInstructionsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/shipping/AmountBigDecimalTextField.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableGroupedProductCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/views/ExpandableProductCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainDashboardScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AddProductWithAIBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/productinfo/AiProductPromptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsScreen.kt
  gradle/libs.versions.toml
Labels: dependency update

#13077 Removes coupons outdated banner as well as its associated survey
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/FeedbackSurveyFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/feedback/SurveyType.kt
  WooCommerce/src/main/res/layout/fragment_coupon_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, category: tracks

#13051 [Hack Week] ApiFaker: Refactor the developer screen viewmodel and fragment
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewHolder.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsViewModel.kt
  WooCommerce/src/main/res/layout/developer_options_list_item.xml
  WooCommerce/src/main/res/layout/developer_options_togglable_item.xml
  WooCommerce/src/main/res/layout/developer_options_update_reader_item.xml
  WooCommerce/src/main/res/layout/fragment_developer_options.xml
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModelTest.kt
Labels: type: task, Tech Debt

#13087 [Product List] Avoid direct binding reference with bangs
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/list/ProductListFragment.kt
Labels: type: crash, feature: product list

#13071 [Shipping Labels Revamp] Add Custom package creation support
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/WooShippingLabelPackageMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/WooShippingLabelPackageRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/networking/PackageResponseDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/networking/WooShippingLabelPackageRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/UIModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCustomPackageScreen.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModelTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#13036 Shipping labels: Connecting addresses
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/AddressSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveOriginAddresses.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/OriginShippingAddress.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
Labels: type: task, feature: shipping labels

#13078 Update external contributors documentation related to `secrets.properties`
  README.md
  docs/project-overview.md
Labels: type: documentation

#13066 Enable `e2eRealApiOrderDetails` UI test
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/orders/SingleOrderScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/ui/OrdersRealAPI.kt
Labels: category: ui tests

#13088 Fix create products screenshot
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/screens/products/ProductListScreen.kt
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/e2e/tests/screenshot/ScreenshotTest.kt
Labels: category: ui tests

#13094 [Tooling] Publish GitHub Releases for beta immediately
  fastlane/Fastfile
Labels: category: tooling

#13095 [Shipping Labels Revamp] Add Weight support to custom package creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/components/WooShippingPackageListItem.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/PackageDAOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/WooShippingLabelPackageMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/UIModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCarrierPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCustomPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingSavedPackageScreen.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/CustomPackageCreationDataTest.kt
Labels: type: task, feature: shipping labels

#13069 [Woo POS][Cash & Receipts] Navigation via navigation component to the cash payment screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/cash/WooPosTotalsPaymentCashScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#13073 Update function usage in SSR and remove need for commons-io
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringExt.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCSSRModelExt.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/extensions/StringExtTest.kt
  gradle/libs.versions.toml
Labels: feature: support, dependency update

#13067 [Product Global Unique Identifier] Add search by global unique identifier
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/inventory/FetchProductByIdentifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/inventory/FetchProductBySKU.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/inventory/ScanToUpdateInventoryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/list/ProductListRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/CreationFocusedOrderCreateEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/inventory/FetchProductByIdentifierTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/inventory/ScanToUpdateInventoryViewModelTest.kt
  gradle/libs.versions.toml
Labels: type: task, feature: product details

#13053 [POS][Custom payment UI] – Reader not connected error handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: status: do not merge

#13057 [POS][Custom payment UI] – Failed payment error handling
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/failed/WooPosTotalsPaymentFailedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/processing/WooPosTotalsPaymentProcessingScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiStringParser.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_error_x.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: status: do not merge

#13090 [POS][Custom payment UI] – UI animation for `Loading` data and `CollectingPayment` states
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/res/drawable/woopos_ic_collect_payment.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#12972 [WooPos][Non Simple Product types] Retry UI for pagination errors on variations screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/selector/VariationListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosPaginationErrorIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosBaseViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosVariationsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/VariationsLRUCache.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsUIEvents.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/variations/WooPosVariationsViewModelTest.kt
Labels: type: task, unit-tests-exemption, feature: point of sale

#13072 [Woo POS][non-simple products] Integrate "include_types" parameter for product endpoint
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/list/ProductListRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/featureflags/IsNonSimpleProductTypesEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosProductsDataSourceTest.kt
  gradle/libs.versions.toml
Labels: type: task, feature: point of sale

#13119 [Product Global Unique Identifier Support] Tracking
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductInventoryViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/inventory/FetchProductByIdentifier.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductInventoryViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/inventory/FetchProductByIdentifierTest.kt
Labels: category: tracks, feature: product details, feature: analytics

#13113 [Bulk Update Orders] Feature flag.
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task

#13100 [POS][Custom payment UI] – Payment processing animation with Lottie
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/inprogress/WooPosTotalsPaymentInProgressScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/processing/WooPosTotalsPaymentProcessingScreen.kt
  WooCommerce/src/main/res/raw/woopos_card_ilustration.json
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  gradle/libs.versions.toml
Labels: feature: point of sale

#13111 [Shipping Labels Revamp] Handle Package selection on the main form
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/GetShippingRates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/PackageDAOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/WooShippingLabelPackageMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/UIModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCarrierPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCustomPackageScreen.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/CustomPackageCreationDataTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#12977 [POS][Custom payment UI] – Switch to Payment Controller in POS Totals | Base PR
  RELEASE-NOTES.txt
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/controller/CardReaderPaymentController.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/controller/CardReaderPaymentControllerFactory.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderMode.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderPaymentStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/TTPPaymentProgressDelegate.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/failed/WooPosTotalsPaymentFailedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/inprogress/WooPosTotalsPaymentInProgressScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/UiStringParser.kt
  WooCommerce/src/main/res/drawable/woo_pos_ic_error_x.xml
  WooCommerce/src/main/res/raw/woopos_card_ilustration.json
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/controller/CardReaderPaymentControllerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt
  gradle/libs.versions.toml
Labels: feature: mobile payments, unit-tests-exemption, feature: point of sale

#13124 [Tooling] Update GitHub Actions
  .github/workflows/gradle-wrapper-validation.yml
Labels: category: tooling

#13120 [woo pos][non-simple products]updated designs retry pagination error
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosPaginationErrorIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/variations/WooPosVariationsViewModelTest.kt
Labels: type: task, feature: point of sale

#13134 [Product Global Unique Identifier] Remove feature flag to enable it in production
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductInventoryFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task, feature: product details

#13109 [Woo POS[Cash & Receipts] Implement navigation via nav component to the full receipts sending screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptIsSendingSupported.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptIsSendingSupportedTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: unit-tests-exemption, feature: point of sale

#13137 Remove Purple 15 color
  WooCommerce-Wear/src/main/res/values/colors_base.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
Labels: type: task, category: design

#13083 [Hack Week] ApiFaker: match endpoints using query parameters
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/ApiFakerDatabase.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/EndpointDao.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/QueryParameterConverter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/QueryParameter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Request.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Response.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsViewModel.kt
  libs/apifaker/src/test/java/com/woocommerce/android/apifaker/EndpointProcessorTest.kt
Labels: type: task, status: do not merge

#13070 [Hack Week] ApiFaker: Adding, deleting and deleting endpoints
  WooCommerce/src/debug/kotlin/com/woocommerce/android/WooCommerceDebug.kt
  libs/apifaker/build.gradle
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerUiHelper.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/ApiFakerDatabase.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/EndpointDao.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/QueryParameterConverter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/di/ApiFakerModule.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/HttpMethod.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/QueryParameter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Request.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Response.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/ApiFakerNavHost.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/DropDownMenu.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/Screen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/util/JSONObjectProvider.kt
  libs/apifaker/src/test/java/com/woocommerce/android/apifaker/EndpointProcessorTest.kt
Labels: type: task

#13064 [Hack Week] ApiFaker: Home screen and integration with the app
  WooCommerce/build.gradle
  WooCommerce/src/debug/kotlin/com/woocommerce/android/WooCommerceDebug.kt
  WooCommerce/src/debug/kotlin/com/woocommerce/android/apifaker/ApiFakerHostFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  WooCommerce/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  libs/apifaker/build.gradle
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerConfig.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerUiHelper.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/ApiFakerDatabase.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/EndpointDao.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/QueryParameterConverter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/di/ApiFakerModule.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/HttpMethod.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/QueryParameter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Request.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Response.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/ApiFakerNavHost.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/DropDownMenu.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/Screen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/util/JSONObjectProvider.kt
  libs/apifaker/src/test/java/com/woocommerce/android/apifaker/EndpointProcessorTest.kt
Labels: type: task

#13147 Update theme colors
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/compose/theme/WooColors.kt
  WooCommerce-Wear/src/main/res/values/colors_base.xml
  WooCommerce-Wear/src/wasabi/res/values/ic_launcher_background.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/FeedbackDialog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/theme/WooColors.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/res/color/button_toggle_fg_selector.xml
  WooCommerce/src/main/res/drawable/list_primary_selector.xml
  WooCommerce/src/main/res/layout/product_filter_option_list_item.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/ic_launcher_background.xml
  WooCommerce/src/main/res/values/wc_colors_base.xml
  WooCommerce/src/wasabi/res/values/ic_launcher_background.xml
Labels: type: task, category: design

#13123 [Woo POS][Cash & Receipts] Implement receipts UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosInputFields.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/emailreceipt/WooPosEmailReceiptViewModelTest.kt
Labels: feature: point of sale

#13139 Shipping rates custom weight support
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/OriginShippingAddress.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/StoreOptionsModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRates.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/PackageDataTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesRepositoryTest.kt
Labels: type: task, feature: shipping labels

#13138 Select shipping rate
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/ShippingRateModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesDatasourceMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesSection.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesDatasourceMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRatesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapperTest.kt
Labels: type: task, feature: shipping labels

#13126 Shipping rates networking
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/GetShippingRates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveOriginAddresses.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/OriginShippingAddress.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/StoreOptionsModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/WooShippingCarrier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/components/PackageItemComponents.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/UIModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCarrierPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingSavedPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/ShippingRateModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesDatasourceMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRates.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/networking/ShippingRatesDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/networking/WooShippingRatesRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesSection.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/WooShippingLabelPackageCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/datasource/FetchPredefinedPackagesFromStoreTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/PackageDataTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesDatasourceMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRatesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapperTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#13144 [Woo POS][Cash & Receipts] Reimlement the UI of the cash payment screen as per new design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosInputFields.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentViewModelTest.kt
Labels: feature: point of sale

#13148 [Shipping Labels Revamp] Introduce Printing networking layer and file creation support
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/printing/FetchShippingLabelFile.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/printing/ShippingLabelPrintingResponse.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/printing/FetchShippingLabelFileTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#13143 [Woo POS][Cash & Receipts] Go directly forward to the payment success screen from cash payment
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeScreen.kt
Labels: feature: point of sale

#13153 Shipping label cost
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
Labels: type: task, feature: shipping labels

#13052 [Hack Week] ApiFaker: introduce new module and logic
  .buildkite/commands/run-unit-tests.sh
  WooCommerce/build.gradle
  WooCommerce/src/debug/kotlin/com/woocommerce/android/WooCommerceDebug.kt
  WooCommerce/src/debug/kotlin/com/woocommerce/android/apifaker/ApiFakerHostFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_settings.xml
  gradle/libs.versions.toml
  libs/apifaker/build.gradle
  libs/apifaker/src/main/AndroidManifest.xml
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerConfig.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerUiHelper.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/LogTag.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/ApiFakerDatabase.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/EndpointDao.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/EndpointTypeConverter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/db/QueryParameterConverter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/di/ApiFakerModule.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/ApiType.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/HttpMethod.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/MockedEndpoint.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/QueryParameter.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Request.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/models/Response.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/ApiFakerNavHost.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/DropDownMenu.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/Screen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/details/EndpointDetailsViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeScreen.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
  libs/apifaker/src/main/java/com/woocommerce/android/apifaker/util/JSONObjectProvider.kt
  libs/apifaker/src/test/java/com/woocommerce/android/apifaker/EndpointProcessorTest.kt
  settings.gradle
Labels: type: task, unit-tests-exemption

#13155 [Woo POS][Cash & Receipts] Do not play animations when coming back from receipts screens
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
Labels: feature: point of sale

#13149 [Woo POS][Cash Receipts] Reimplement the payment success screen as per changed design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosPaginationErrorIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/failed/WooPosTotalsPaymentFailedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/res/drawable/ic_woo_pos_check.xml
  WooCommerce/src/main/res/drawable/ic_woo_pos_empty_cart.xml
  WooCommerce/src/main/res/drawable/ic_woo_pos_empty_products.xml
  WooCommerce/src/main/res/drawable/ic_woo_pos_error.xml
  WooCommerce/src/main/res/drawable/ic_woo_pos_error_x.xml
  WooCommerce/src/main/res/drawable/ic_woo_pos_exit.xml
  WooCommerce/src/main/res/drawable/woo_pos_ic_payment_success.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
Labels: feature: point of sale

#13167 [Shipping labels]: Get account settings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/FetchAccountSettings.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/DTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/FetchAccountSettingsTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapperTest.kt
Labels: type: task, feature: shipping labels

#13168 [Shipping labels] Shipping labels networking
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/ShippingLabelModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/DTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapperTest.kt
Labels: type: task, feature: shipping labels

#13157 [Woo POS][Cash & Receipts] Remove cash and receipts feature flags
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/featureflags/WooPosIsCashPaymentsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/featureflags/WooPosIsReceiptsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/success/WooPosTotalsPaymentSuccessScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#13172 [Crash] Camera with LENS_FACING_BACK not available making app crash when scanning barcode
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanner.kt
Labels: type: crash

#13131 [Bulk Update Orders] Enable multiple selection in Order List: Part I
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/DefaultOrderListItemLookup.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderSelectionItemKeyProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/menu/menu_action_mode_orders_list.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: type: task, feature: order list, unit-tests-exemption

#13165 Purchase shipping label
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/PurchaseShippingLabel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/PurchasedLabelData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/DTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/ShippingRateModels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/datasource/WooShippingRatesDatasourceMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/networking/ShippingRatesDTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/GetShippingRatesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/domain/WooShippingRatesDomainMapperTest.kt
Labels: type: task, feature: shipping labels

#13164 [Shipping Labels Revamp] Finish Purchased screen UI feedback and data
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/PurchasedShippingLabelData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#13135 Issue/13127 add edit sites button
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/main/res/menu/menu_site_picker.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerTestUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt
Labels: unit-tests-exemption, feature: site picker

#13141 Issue/13136 manage stores visibility
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/StoreVisibilityScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModel.kt
  WooCommerce/src/main/res/menu/menu_site_picker.xml
  WooCommerce/src/main/res/navigation/nav_graph_site_picker.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModelTest.kt
Labels: feature: site picker

#13162 [Woo POS – Custom Payment UI] Fix state mismatch after system "back" in Payment failed screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/failed/WooPosTotalsPaymentFailedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/payment/inprogress/WooPosTotalsPaymentInProgressScreen.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: type: bug

#13175 [Shipping Label Revamp] Add Shipping Label status observer in Purchased UI
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/ObserveShippingLabelStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/PurchasedShippingLabelData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_orders.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/ObserveShippingLabelStatusTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt
Labels: type: task, feature: shipping labels

#13181 Update `21.3` release notes
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#13183 Settings: Fix overlap issue on WooCommerce Version string.
  RELEASE-NOTES.txt
  WooCommerce/src/main/res/layout/fragment_settings_main.xml
Labels: feature: app settings

#13179 Add bottomsheet to final screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/AddressSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/OriginShippingAddress.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/PurchasedShippingLabelData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt
Labels: type: task, feature: shipping labels

#13185 Update primary colors
  WooCommerce-Wear/src/main/java/com/woocommerce/android/wear/compose/theme/WooColors.kt
  WooCommerce-Wear/src/main/res/values/colors_base.xml
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/theme/WooColors.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
Labels: category: design

#13160 Show currently selected site in site visibility editor screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/StoreVisibilityScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModelTest.kt
Labels: feature: site picker

#13186 Update illustrations in the JC flow
  WooCommerce/src/main/res/drawable-hdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-hdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-hdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-ldpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-ldpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-mdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-mdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-mdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_connect_jetpack.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_install_jetpack.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_jetpack_connection_dismissed.webp
  WooCommerce/src/main/res/drawable/ic_woo_bubble.xml
Labels: category: design

#13177 [Woo POS][Cash & Receipts] Implement UI changes
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cashpayment/WooPosCashPaymentScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosTheme.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeParentToChildCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
  WooCommerce/src/main/res/values-ar/strings.xml
  WooCommerce/src/main/res/values-de/strings.xml
  WooCommerce/src/main/res/values-es/strings.xml
  WooCommerce/src/main/res/values-fr/strings.xml
  WooCommerce/src/main/res/values-he/strings.xml
  WooCommerce/src/main/res/values-id/strings.xml
  WooCommerce/src/main/res/values-it/strings.xml
  WooCommerce/src/main/res/values-ja/strings.xml
  WooCommerce/src/main/res/values-ko/strings.xml
  WooCommerce/src/main/res/values-nl/strings.xml
  WooCommerce/src/main/res/values-pt-rBR/strings.xml
  WooCommerce/src/main/res/values-ru/strings.xml
  WooCommerce/src/main/res/values-sv/strings.xml
  WooCommerce/src/main/res/values-tr/strings.xml
  WooCommerce/src/main/res/values-zh-rCN/strings.xml
  WooCommerce/src/main/res/values-zh-rTW/strings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
Labels: feature: point of sale

#13190 [Woo POS][non-simple products] Add tests for Variations data source and remove virtual filtering
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/di/WooPosDataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/products/WooPosProductsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/VariationsLRUCache.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosProductsDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/variations/WooPosVariationsDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/variations/WooPosVariationsViewModelTest.kt
Labels: type: task, feature: point of sale

#13196 [Woo POS][Non-Simple Products] Add downloadable products filter from API and remove client side filtering
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/products/WooPosProductsDataSource.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosIsEnabledTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosProductsDataSourceTest.kt
  gradle/libs.versions.toml
Labels: type: task, feature: point of sale

#13197 [Woo POS][TPV tracking] Send channel metadata in payment intent
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/controller/CardReaderPaymentController.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/controller/CardReaderPaymentControllerTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/MetaDataKeys.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentAction.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/PaymentInfo.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentManagerTest.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/actions/CreatePaymentActionTest.kt
Labels: feature: point of sale

#13193 [DateUtils] Improve Date string formatting fallback strategy
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/DateUtilsTest.kt
Labels: type: bug, feature: shipping labels

#13205 Fix design issues
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingProductsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/packages/ui/WooShippingCarrierPackageScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/rates/ui/ShippingRatesCard.kt
Labels: type: enhancement, feature: shipping labels

#13151 [Bulk Update Orders] Enable multiple selection in Order List: Part II
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFiltersCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListAdapter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
  WooCommerce/src/main/res/layout/order_list_item.xml
Labels: type: task, feature: order list

#13203 [Woo POS] Crash when plugin either attempted to be installed or activated by a show manager
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/res/layout/activity_woo_pos_card_reader.xml
Labels: type: crash, feature: point of sale

#13199 Cache account settings
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveStoreOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/datasource/ShippingLabelsDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveStoreOptionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
Labels: type: task, feature: shipping labels, unit-tests-exemption

#13211 Get origin address network
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveOriginAddresses.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveStoreOptions.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/AddressSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/FetchOriginAddresses.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/ObserveOriginAddresses.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/datasource/WooShippingAddressDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/datasource/WooShippingConfigurationDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/DTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRestClient.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ObserveStoreOptionsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/FetchOriginAddressesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/ObserveOriginAddressesTest.kt
Labels: type: task, feature: shipping labels

#13184 Dashboard: Update Card Menu sizing to fit content better
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/OverflowMenu.kt
Labels: type: bug, feature: dashboard

#13191 Fix for the IllegalArgumentException required value was null crash
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
Labels: type: crash

#13194 Update TTP illustrations
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-hdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-hdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-mdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-mdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-mdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-mdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-mdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-hdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-mdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-night-xxxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-night/ic_woo_illustrated_icon.xml
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_collecting_payment.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_connecting.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_payment_failed.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_card_reader_tpp_successful_payment.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_tap_to_pay_summary.webp
  WooCommerce/src/main/res/drawable/ic_woo_illustrated_icon.xml
Labels: category: design
