Repository woocommerce/woocommerce-android, pull requests merged in 2025-10, with the labels that each got.

#14667 [CIAB] A minor refactoring to avoid leaking the booking status to UI layer
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/BookingsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingAttendanceSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingAttendanceStatusBottomSheet.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingAttendanceStatusTag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingStatusTag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingSummary.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/PaymentStatusTag.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewState.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModelTest.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/bookings/BookingsStore.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/BookingEntity.kt
Labels: type: task, feature: CIAB Mobile Bookings MVP

#14643 [POS][Local Catalog] Fix Variation.attributes deserializing
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/model/pos/WooPosVariationApiResponse.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/WooPosProductResponseToEntityMapper.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/pos/WooPosVariationEntity.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/WooPosVariationMapperTest.kt
Labels: type: task, feature: point of sale

#14666 [WOOMOB-1346] Booking details - payment section
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/compose/BookingPaymentSection.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewState.kt
  WooCommerce/src/main/res/navigation/nav_graph_bookings.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModelTest.kt
Labels: New Feature, feature: CIAB Mobile Bookings MVP

#14632 [HACK] Remove unused resources
  WooCommerce/src/main/res/color/action_menu_fg_selector.xml
  WooCommerce/src/main/res/color/button_toggle_fg_secondary_selector.xml
  WooCommerce/src/main/res/drawable-hdpi/img_plan.webp
  WooCommerce/src/main/res/drawable-ldpi/img_plan.webp
  WooCommerce/src/main/res/drawable-mdpi/img_plan.webp
  WooCommerce/src/main/res/drawable-night/ic_bell_64dp.xml
  WooCommerce/src/main/res/drawable-xhdpi/img_plan.webp
  WooCommerce/src/main/res/drawable-xxhdpi/img_plan.webp
  WooCommerce/src/main/res/drawable-xxxhdpi/img_plan.webp
  WooCommerce/src/main/res/drawable/ic_bell_64dp.xml
  WooCommerce/src/main/res/drawable/ic_dollar.xml
  WooCommerce/src/main/res/drawable/ic_gridicons_bug.xml
  WooCommerce/src/main/res/drawable/ic_powered_by.xml
  WooCommerce/src/main/res/drawable/ic_present.xml
  WooCommerce/src/main/res/drawable/ic_star.xml
  WooCommerce/src/main/res/drawable/ic_truck.xml
  WooCommerce/src/main/res/values-night/colors_base.xml
  WooCommerce/src/main/res/values/alphas.xml
  WooCommerce/src/main/res/values/colors_base.xml
  WooCommerce/src/main/res/values/dimens_base.xml
  WooCommerce/src/main/res/values/media_picker_drawables.xml
  WooCommerce/src/main/res/values/strings.xml
Labels: Tech Debt

#14673 [CIAB] Bookings search
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/BookingsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/TextFields.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModelTest.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/bookings/BookingsFetchResult.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/bookings/BookingsRestClient.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/bookings/BookingsStore.kt
Labels: type: enhancement, feature: CIAB Mobile Bookings MVP

#14675 [POS][Local Catalog] Run incremental sync on splash screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/localcatalog/WooPosIncrementalSyncReason.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/splash/WooPosSplashViewModelTest.kt
Labels: type: task

#14684 [POS Orders] Pagination: Search and Error
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosPaginationErrorIndicator.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersDataSourceTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersViewModelTest.kt
Labels: type: task

#14686 [CIAB Bookings] Update logic of tabs filtering
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListFiltersBuilder.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListFilterBuilderTest.kt
Labels: type: enhancement, feature: CIAB Mobile Bookings MVP

#14693 Fix Room crash in 23.3
  WooCommerce/src/main/kotlin/com/woocommerce/android/applicationpasswords/WooApplicationPasswordsConfiguration.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/FeatureFlagConfigDao.kt
Labels: type: crash, category: performance

#14671 [Bookings] Add "Sort by" UI to booking list screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingSortBottomSheet.kt
  WooCommerce/src/main/res/drawable/ic_check.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModelTest.kt
Labels: New Feature, feature: CIAB Mobile Bookings MVP

#14702 Update developer.properties-example
  developer.properties-example
Labels: category: tooling

#14694 [WOOMOB-1411][Woo POS][Surveys] Add local notification infrastructure for Woo POS surveys
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationType.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: POS

#14682 [WOOMOB-1400] - Observe booking object from DB on the details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/BookingMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/BookingsRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewState.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/BookingMapperTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/details/BookingDetailsViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModelTest.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/bookings/BookingsStore.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/dao/BookingsDao.kt
Labels: New Feature, feature: CIAB Mobile Bookings MVP

#14709 [Booings] Show filter button only for All tab
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/bookings/list/BookingListViewState.kt
Labels: Enhancement

#14703 [WOOMOB-1428][Woo POS][Surveys] Show potential user push notification after order creation
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/util/WooPosSurveysNotificationSchedular.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/common/util/WooPosSurveysNotificationSchedularTest.kt
Labels: feature: POS

#14695 [POS Orders] Empty and Error states
  Add_WooPosEmptyScreen_component_and_refactor_empty_list_handling.patch
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosEmptyScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorAndEmptyStateButtonModifier.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosErrorScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/coupons/WooPosCouponsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/coupons/search/WooPosCouponsSearchScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/products/WooPosProductsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/search/WooPosItemsSearchScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersViewModel.kt
  WooCommerce/src/main/res/drawable/ic_woo_pos_orders_empty.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/orders/WooPosOrdersViewModelTest.kt
Labels: type: task

#14669 Buildkite 🤝 Claude integration
  .buildkite/commands/comment-claude-analysis.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
Labels: category: tooling

#14712 [WOOMOB-1433][Woo POS][Surveys] Schedule current user survey notification on app start
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/util/WooPosSurveysNotificationScheduler.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/UnifiedOrderEditViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/common/util/WooPosSurveysNotificationSchedulerTest.kt
Labels: feature: POS
