Repository woocommerce/woocommerce-android, pull requests merged in 2025-08, with the labels that each got.

#14414 Fix Apply button on add gift card screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/giftcards/EditGiftCardScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/giftcards/OrderCreateEditGiftCardFragment.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/persistence/dao/OrderStatusDaoTest.kt
Labels: feature: order creation

#14419 [Dependabot] Add `automattic-encryptedlogging` to Ignore Configuration
  .github/dependabot.yml
Labels: category: tooling, dependency update, Core

#14404 [WOOMOB-946] Remove deprecated testing approach
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/reviews/ReviewModerationHandlerTests.kt
Labels: Tech Debt

#14412 Add json smart library dependency constraints
  WooCommerce/build.gradle
  gradle/libs.versions.toml
Labels: dependency update, dependencies

#14411 Update jackson version and add constraints for jackson core
  .github/dependabot.yml
  WooCommerce/build.gradle
  gradle/libs.versions.toml
Labels: dependency update, dependencies

#14422 [WOOMOB-961] Remove unused libsapachehttpclientandroid dependency
  libs/fluxc/build.gradle
Labels: type: technical debt

#14408 Fix memory leak product image viewer
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ProductImageViewerFragment.kt
Labels: Bug

#14427 [WOOMOB-922][Woo POS] Update illustrations to follow the updated Woo design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/WooPosItemsList.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/res/drawable/ic_woo_pos_not_found.xml
  WooCommerce/src/main/res/drawable/img_card_reader_not_connected_v2.xml
Labels: feature: POS

#14429 [POS as Tab i2] Show labels in navigation menu on tablets
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt
Labels: type: task

#14421 Remove background from product images | Analytics
  WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ai/ProductImageRemoveBackgroundFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ai/ProductImageRemoveBackgroundViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/images/ai/ProductImageRemoveBackgroundViewModelTest.kt
Labels: type: task, category: tracks

#14441 [WOOMOB-1012] POS: Replace clear cart button with delete icon and add confirmation dropdown menu
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosButtons.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: Enhancement, feature: POS

#14440 [POS] Remove deprecated accessibility function
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosAccessibilityAnnouncement.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/ext/WooPosContextExt.kt
Labels: type: task, category: accessibility

#14445 HACK: Release Product background removal
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/images/ProductImageViewerFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
Labels: type: task

#14407 [Hack Week] App logs improvements: persist logs on disk
  WooCommerce/build.gradle
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/di/AppConfigModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/WooLogViewerActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/WooLogViewerScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskEnvironmentDataSource.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskTicketRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodCurrencyMissMatchLog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductListHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/RollingLogEntries.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLogWrapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/EncryptedLogsFileProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/EnqueueSendingEncryptedLogs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WooLogFileProvider.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/logs/LogEntry.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/logs/LogFileWriter.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/util/logs/WooFileLogger.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandlerTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/support/ZendeskTicketRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodCurrencyMissMatchLogTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/RollingLogEntriesTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/WooLog.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/EncryptedLogsFileProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/EnqueueSendingEncryptedLogsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WooLogFileProviderTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/logs/LogFileWriterTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/util/logs/WooFileLoggerTest.kt
  gradle/libs.versions.toml
Labels: type: task

#14457 Handle null values when API returns null user roles
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt
  WooCommerce/src/main/res/values/strings.xml
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRestClient.kt
Labels: type: crash, feature: login

#14455 [Shipping Labels] Add purchased message to shipment tabs
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingProductsCard.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/split/WooShippingSplitShipmentScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: shipping labels, Enhancement

#14454 [WOOMOB-1022][Woo POS][Settings] Implement settings navigation infrastructure to Settings screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeChildToParentCommunication.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosMainFlowGraph.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosNavigationEventHandler.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/root/navigation/WooPosRootHost.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsNavigation.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModelTest.kt
Labels: feature: POS

#14459 [WOOMOB-1023][Woo POS][Settings] Implement 2-pane layout with Android-style UI design
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/component/WooPosToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/categories/WooPosSettingsCategoriesPaneScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/categories/WooPosSettingsCategoriesState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/categories/WooPosSettingsCategoriesViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/WooPosSettingsDetailPaneScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/WooPosHardwareSettingsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/WooPosHardwareSettingsState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/WooPosHardwareSettingsViewModel.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: unit-tests-exemption, feature: POS

#14462 [Shipping Labels] Migrate config cache from DataStore to Room
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/GetShipments.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/SplitShipment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/datasource/WooShippingConfigDataStore.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/DTOs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingNetworkingMapper.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/ObserveShippingLabelStatus.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/refund/WooShippingLabelRefundViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/GetShipmentsTests.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/SplitShipmentTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/ObserveShippingLabelStatusTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/refund/WooShippingLabelRefundViewModelTest.kt
  libs/fluxc-plugin/schemas/org.wordpress.android.fluxc.persistence.WCAndroidDatabase/56.json
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/di/WCDatabaseModule.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCAndroidDatabase.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/dao/WooShippingDao.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/WooShippingLabelEntity.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/WooShippingShipmentEntity.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/utils/JsonUtils.kt
Labels: type: technical debt, feature: shipping labels, unit-tests-exemption

#14463 [POS] Better error handling for eligibility
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/AppPrefsTest.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/WooPOSIsRemotelyEnabled.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/util/WooPosCouldNotDetermineValueException.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/eligibility/WooPosEligibilityViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/tab/WooPosCanBeLaunchedInTab.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/tab/WooPosTabController.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/tab/WooPosTabShouldBeVisible.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsEvent.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPOSIsRemotelyEnabledTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/tab/WooPosCanBeLaunchedInTabTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/tab/WooPosTabShouldBeVisibleTest.kt
Labels: type: task

#14477 [Shipping Labels] Improvements to the Customs Form screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/WCOutlinedSpinner.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/components/RoundedBorderDropdownWithLabel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/customs/WooShippingCustomsFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/customs/WooShippingCustomsFormScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/customs/products/WooShippingCustomsProductListItem.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: type: enhancement, feature: shipping labels

#14473 Add GitHub warning to constraint layout dependency updates
  .github/workflows/dependabot-constraintlayout-check.yml
Labels: category: tooling

#14476 [Shipping Labels ] Fix UI issues on edit address screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/WooShippingEditAddressScreen.kt
Labels: feature: shipping labels, Bug

#14431 Fix UserAgent ANR - Take 2
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/web/WCWebView.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/UserAgent.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/BaseWPAPIRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/ApplicationPasswordsNetwork.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/WPApiApplicationPasswordsRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpackai/JetpackAITranscriptionRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/wporg/BaseWPOrgAPIClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/BaseXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/tools/FluxCImageLoader.java
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/network/UserAgentTest.kt
Labels: type: crash

#14482 [WOOMOB-1083][Woo POS][Settings] Implement card reader update flow from settings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/update/CardReaderUpdateDialogFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/developer/DeveloperOptionsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/cardreader/WooPosSettingsHardwareCardReaderScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/cardreader/WooPosSettingsHardwareCardReaderViewModel.kt
  WooCommerce/src/main/res/navigation/nav_graph_payment_flow.xml
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/settings/details/hardware/cardreader/WooPosSettingsHardwareCardReaderViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
Labels: feature: POS

#14491 Update `WooPosPreview` to render Phone layout in POS in previews
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/common/composeui/WooPosComposePreviewAnnotation.kt
Labels: feature: point of sale

#14492 [POS][Local Catalog] PosVariation table and DAO
  libs/fluxc-plugin/schemas/org.wordpress.android.fluxc.persistence.WCAndroidDatabase/59.json
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCAndroidDatabase.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/dao/pos/PosVariationsDao.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/pos/WCPosProductModel.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/pos/WCPosVariationModel.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/persistence/dao/pos/PosVariationsDaoTest.kt
Labels: type: task

#14488 [Shipping Labels] Update buttons logic on hazmat selection screen
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/hazmat/WooShippingLabelHazmatFormFragment.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/hazmat/WooShippingLabelHazmatFormScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/hazmat/WooShippingLabelHazmatFormViewModel.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/hazmat/WooShippingLabelHazmatFormViewModelTest.kt
Labels: feature: shipping labels, Task (new)

#14493 [Shipping Labels] Show refund notice about refunded labels in Order Details screen
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailWooShippingShipmentListView.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/GetShipments.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShippingLabelSampleData.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/ShipmentUIModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/models/ShippingLabelModel.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModelTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/split/GetSplitMovementsTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/split/WooShippingSplitShipmentViewModelTest.kt
Labels: type: enhancement, feature: shipping labels

#14490 Issue/woomob 1052 woo poslocal catalog store products requested from pos to
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/PosProductResponseToEntityMapper.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/PosProductRestClient.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/store/pos/PosLocalCatalogStore.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/store/pos/PosLocalCatalogStoreTest.kt
Labels: feature: POS

#14504 Update release notes - 23.1
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#14508 Fix R8 minification error after Crypto library update
  WooCommerce/proguard-rules.pro
Labels: Releases

#14484 Fix detekt rule to exclude Android tests
  libs/detektrules/src/main/kotlin/com/woocommerce/android/detektrules/test/UnitTestNamingRule.kt
Labels: type: technical debt

#14502 [POS][Local Catalog] GET Endpoint and Store for variations incremental sync
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/di/WCDatabaseModule.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/model/pos/PosVariationApiResponse.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/PosProductResponseToEntityMapper.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/PosProductRestClient.kt
  libs/fluxc-plugin/src/main/kotlin/org/wordpress/android/fluxc/store/pos/PosLocalCatalogStore.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/pos/PosVariationMapperTest.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/store/pos/PosLocalCatalogStoreTest.kt
Labels: type: task

#14497 [WOOMOB-1128][Woo POS][Settings] Implement analytics events
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/util/analytics/WooPosAnalyticsEvent.kt
Labels: feature: POS

#14514 [WOOMOB-1161][Woo POS][Settings]Remove email field from the store settings
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsReceiptRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsStoreRepository.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsStoreScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsStoreState.kt
  WooCommerce/src/main/res/values/strings.xml
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsReceiptRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsStoreRepositoryTest.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/settings/details/store/WooPosSettingsStoreViewModelTest.kt
Labels: feature: POS

#14524 [Login] Improve root endpoint response deserialization to fix login issues
  RELEASE-NOTES.txt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/NamespacesDeserializer.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/RootWPAPIRestResponse.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/network/discovery/RootWPAPIRestResponseTest.kt
Labels: type: bug, feature: login, unit-tests-exemption

#14521 [WOOMOB-1175][Woo POS][Settings] Update empty cart state UI with integrated barcode scanning option
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartScreen.kt
  WooCommerce/src/main/res/values/strings.xml
Labels: feature: POS

#14513 Propagate Headers to RestClients
  RELEASE-NOTES.txt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/plans/networking/SitePlanRestClient.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClientTest.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClientTest.kt
  libs/fluxc-plugin/src/test/java/org/wordpress/android/fluxc/utils/WPAPIResponseExtTests.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/jetpacktunnel/JetpackTunnelGsonRequestTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/WPComGsonRequestTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpapi/NonceRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpapi/plugin/PluginWPApiRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/blaze/BlazeCampaignsRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jitm/JitmRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/mobile/FeatureFlagsRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/mobile/JetpackMigrationRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/mobilepay/MobilePayRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/products/ProductsRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/qrcodeauth/QRCodeAuthRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteHomepageRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/GatewayRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/WooExperimentalNetworkTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/CustomerRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClientTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/store/ProductsStoreTest.kt
  libs/fluxc-tests/src/test/java/org/wordpress/android/fluxc/store/SiteStoreTest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/GsonRequest.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/Header.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/ResponseWithHeaders.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIEncodedBodyRequest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIEncodedBodyRequestBuilder.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIGsonRequest.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIGsonRequestBuilder.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIResponse.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/ApplicationPasswordsNetwork.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/WPApiApplicationPasswordsRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/JetpackTunnelWPAPINetwork.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/WPComGsonRequest.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/WPComGsonRequestBuilder.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountClosure.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/auth/Authenticator.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTimeoutRequestHandler.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequestBuilder.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/wpv2/WPComV2MediaRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/reader/ReaderRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/ThemeRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/wporg/WPOrgAPIGsonRequest.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/ApplicationPasswordsNetworkTests.kt
Labels: category: architecture

#14529 Add ReaderNotConnected enum value
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: Tech Debt

#14517 Updates or removes dependecies to prepare app for 16KB page size requirement
  WooCommerce-Wear/build.gradle
  WooCommerce-Wear/src/debug/AndroidManifest.xml
  WooCommerce-Wear/src/debug/java/com/woocommerce/android/app/WooCommerceWearDebug.kt
  WooCommerce-Wear/src/debug/java/com/woocommerce/android/di/DebugInterceptorModule.kt
  WooCommerce/build.gradle
  WooCommerce/src/androidTest/kotlin/com/woocommerce/android/di/DummyInterceptorModule.kt
  WooCommerce/src/debug/kotlin/com/woocommerce/android/WooCommerceDebug.kt
  WooCommerce/src/debug/kotlin/com/woocommerce/android/di/DebugInterceptorModule.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/CardReaderPaymentViewModelTest.kt
  gradle/libs.versions.toml
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt
  libs/cardreader/src/main/java/com/woocommerce/android/cardreader/payments/CardPaymentStatus.kt
  libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapperTest.kt
Labels: Tech Debt

#14531 Update secrets to fix "real api" tests
  .configure
  .configure-files/secrets.properties.enc
Labels: type: bug, category: ui tests

#14528 [WOOMOB-1198][Woo POS][Settings] Add back navigation icon to settings toolbar
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbar.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbarAccessibilityLabels.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbarState.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbarUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbarViewModel.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarUIEvent.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/WooPosSettingsScreen.kt
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/settings/details/WooPosSettingsDetailPaneScreen.kt
  WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosHomeFloatingToolbarViewModelTest.kt
Labels: feature: POS

#14536 Update surface container colors of Material 3 theme
  WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/theme/WooColors.kt
  WooCommerce/src/main/res/values-night/colors_base.xml
Labels: type: bug, feature: order details
